Discord4J/Discord4J

src/main/java/sx/blah/discord/api/internal/DiscordWS.java
Helps with the CPU time with seemingly no drifting. Running a bot with it for 12 hours without losing connection so far.
=> Using a scheduled executor to do keep-alive requests

.gitignore, src/main/java/sx/blah/discord/api/IDiscordClient.java, src/main/java/sx/blah/discord/api/MissingPermissionsException.java, src/main/java/sx/blah/discord/api/internal/DiscordClientImpl.java, src/main/java/sx/blah/discord/handle/impl/obj/Channel.java, src/main/java/sx/blah/discord/handle/impl/obj/Guild.java, src/main/java/sx/blah/discord/handle/impl/obj/Message.java, src/main/java/sx/blah/discord/util/Lambdas.java
=> Use streams where practical

src/main/java/sx/blah/discord/handle/EventDispatcher.java
Allows you to make handlers for any class `x`, where `Event.class.isAssignableFrom(x)` is true.
Also theoretically speeds up event distribution by using a stream...?
And for some reason, the annotation wasn't being checked, so I threw in a check for that too.
=> Improvements to EventDispatcher logic

src/test/java/sx/blah/discord/examples/AccountBot.java, src/test/java/sx/blah/discord/examples/ParrotBot.java, src/test/java/sx/blah/discord/examples/ReadyBot.java, src/test/java/sx/blah/discord/examples/RoleBot.java
Added example bots to demonstrate some uses of the library.
=> Added Example Bots

src/main/java/sx/blah/discord/api/internal/DiscordClientImpl.java
NoSuchElementExceptions are bad
=> Fail more gracefully if guild is unavailable

src/main/java/sx/blah/discord/Discord4J.java, src/main/java/sx/blah/discord/api/DiscordStatus.java, src/main/java/sx/blah/discord/api/internal/DiscordClientImpl.java, src/main/java/sx/blah/discord/api/internal/DiscordUtils.java, src/main/java/sx/blah/discord/api/internal/DiscordWS.java, src/main/java/sx/blah/discord/handle/impl/obj/Channel.java, src/main/java/sx/blah/discord/handle/impl/obj/Guild.java, src/main/java/sx/blah/discord/handle/impl/obj/Role.java, src/main/java/sx/blah/discord/util/Image.java, src/main/java/sx/blah/discord/util/Requests.java
By request from discord's sedmelluq. I use this to always keep a record since I run a 24/7 bot, hope it's useful.
=> Ensure that all exceptions are logged

src/main/java/sx/blah/discord/Discord4J.java
Previously, only logging in with the now-deprecated method of email/password was supported.
=> Added support for independent execution with bot token

src/main/java/sx/blah/discord/handle/AudioChannel.java
* I figured it can be helpful to get the volume, not only set it. For example my bot will return the current volume if no volume was specified for the volume command.
* Added JavaDoc for the getter and setter
=> Add AudioChannel#getVolume() and docs for setVolume()

README.md
* Fix a typo for the Discord4J module 'Instructability'
=> Fix typo for 'Instructability'

src/main/java/sx/blah/discord/util/RoleBuilder.java
* Added a utility RoleBuilder class to help in the creation of new roles for guilds.
=> Added a utility RoleBuilder class

src/main/java/sx/blah/discord/api/internal/DiscordWS.java, src/main/java/sx/blah/discord/handle/impl/obj/VoiceChannel.java
**Issues Fixed:** #39 
* Modified how it handles voice channels so it can deal with channels in the same guild and in different ones better. 
Here are screenshots of the tests before and after the changes.
http://y.zxq.co/tzrqje.png ---> http://y.zxq.co/jtabkr.png (The initial issue)
http://y.zxq.co/uwsnhc.png ---> http://y.zxq.co/zevphq.png (The issue after b00e8e7)
http://y.zxq.co/lzjvii.png ---> http://y.zxq.co/esftsz.png (The issue after 4030d42)
=> Fixes voice state logic (again, again)

src/main/java/sx/blah/discord/api/internal/DiscordWS.java, src/main/java/sx/blah/discord/handle/impl/obj/User.java, src/main/java/sx/blah/discord/handle/obj/IUser.java
* Added support for self_deaf and self_mute
* Updates deaf and mute when it's changed
...
=> Adds support for self_mute and self_deaf

src/test/java/sx/blah/discord/examples/AccountBot.java, src/test/java/sx/blah/discord/examples/AnnotationListenerExample.java, src/test/java/sx/blah/discord/examples/BaseBot.java, src/test/java/sx/blah/discord/examples/InterfaceListenerExample.java, src/test/java/sx/blah/discord/examples/ParrotBot.java, src/test/java/sx/blah/discord/examples/ReadyBot.java, src/test/java/sx/blah/discord/examples/RoleBot.java
* Updated the quite outdated examples.
=> Updated examples

src/main/java/sx/blah/discord/handle/impl/obj/Channel.java
**Issues Fixed:** #56 
* Using the correct request method for adding a pinned message. See https://discordapp.com/developers/docs/resources/channel#add-pinned-channel-message
=> Fix message pinning by using correct request method

src/main/java/sx/blah/discord/api/internal/DiscordUtils.java, src/main/java/sx/blah/discord/handle/impl/obj/VoiceChannel.java, src/main/java/sx/blah/discord/handle/obj/IVoiceChannel.java, src/main/java/sx/blah/discord/json/requests/ChannelEditRequest.java, src/main/java/sx/blah/discord/json/responses/ChannelResponse.java
* Support for getting and modifying the voice channel bitrate
* Support for changing the voice channel user limit
Techtony96 pointed out that there wasn't a way to change the bitrate so here we are
I went with bits over kilobits because that's what the API accepts and documents, let me know if you want kilobits instead
=> Add support for bitrate in voice channels

src/main/java/sx/blah/discord/api/IDiscordClient.java, src/main/java/sx/blah/discord/api/internal/DiscordClientImpl.java, src/main/java/sx/blah/discord/handle/impl/obj/Guild.java
\+ Added `IDiscordClient#getRoles()` which returns a collection of all of the roles in each of the guilds the client is connected to.
\+ Added `IDiscordClient#getRoleByID()` which returns a role with the given ID.
\+ Added `IDiscordClient#getUsers()` which returns a collection of all of the users in each of the guilds the client is connected to.
\* Changed `DiscordClientImpl#getUserByID()` to use a stream.
\* Changed `Guild#getEveryoneRole()` to use `Guild#getRoleByID()`.
=> Added role methods to IDiscordClient and cleaned up some

src/main/java/sx/blah/discord/handle/impl/obj/Channel.java, src/main/java/sx/blah/discord/handle/obj/IChannel.java
* Corrected typo for Channel#roleOverrides and IChannel#getRoleOverrides (Pointed out by BroManDudeGuyPhD)
...
=> Fixed javadoc typos

pom.xml, src/main/java/sx/blah/discord/handle/impl/obj/Channel.java, src/main/java/sx/blah/discord/handle/obj/IChannel.java
added `sendFile(stream, filename, content)` and `sendFile(stream, filename)`
=> Change sendFile parameter to InputStream

src/main/java/sx/blah/discord/util/audio/AudioPlayer.java
* Added supported filetypes of AudioPlayer#queue into Javadoc
=> Added supported filetypes of AudioPlayer#queue into Javadoc

src/main/java/sx/blah/discord/handle/impl/obj/User.java, src/main/java/sx/blah/discord/handle/obj/IUser.java
**Issues Fixed:** None, new feature.
* Added .addRole and .removeRole to User
...
=> Added the methods .addRole and .removeRole to User

src/main/java/sx/blah/discord/handle/impl/obj/User.java, src/main/java/sx/blah/discord/handle/obj/IUser.java
Reverts austinv11/Discord4J#85
=> Revert "Added the methods .addRole and .removeRole to User"

src/main/java/sx/blah/discord/api/internal/DiscordWS.java, src/main/java/sx/blah/discord/handle/impl/obj/Channel.java, src/main/java/sx/blah/discord/handle/obj/IChannel.java
**Issues Fixed:** Added a setTypingStatus method, which was missing
* Added the setTypingStatus(boolean)
* Renamed the old internal setTypingStatus into SetCachedTypingStatus
...
=> Add setTypingStatus(boolean) to IUser

src/main/java/sx/blah/discord/handle/impl/obj/User.java
- `IUser#addRole` and `IUser#removeRole` no longer modify `IUser#getRolesForGuild`. [This would become inconsistent if `IGuild#editUserRoles` fails.](https://u.pomf.is/ldzdyb.png)
* Both methods create a copy of `getRolesForGuild` and modify that instead.
=> Fixes role caching

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, README.md
* Fix "I have read and __understand__" in the PR template
* Fix inconsistent capitalization in the README (stuff like Discord, CI, API, etc.)
* Remove the readthedocs link because it's very outdated and will mislead new users
* Add our D4J server invite to the issue template
* Add space between `//` in code example comments (on the README) to fit with the project's code style
=> Cleanup miscellaneous text files

src/main/java/sx/blah/discord/api/internal/DiscordClientImpl.java
**Issues Fixed:** The `token` field in `DiscordClientImpl` was being accessed directly instead of using `getToken()`, resulting in the "Bot " suffix not being appended properly.
=> Fixed "Bot" appending for auth token

src/main/java/sx/blah/discord/handle/impl/obj/Channel.java, src/main/java/sx/blah/discord/handle/obj/IChannel.java
* Send files from a URL
* Send text files from a String
=> Improves IChannel#sendFile

src/main/java/sx/blah/discord/util/MessageTokenizer.java
* Add support for everyone and here mentions for MessageTokenizer
* `EveryoneMentionToken` and `HereMentionToken`
=> Add support for everyone and here mentions in MessageTokenizer

src/main/java/sx/blah/discord/api/ClientBuilder.java, src/main/java/sx/blah/discord/api/IDiscordClient.java, src/main/java/sx/blah/discord/api/internal/DiscordClientImpl.java, src/main/java/sx/blah/discord/api/internal/DiscordWS.java, src/main/java/sx/blah/discord/json/requests/ConnectRequest.java
**Issues Fixed:** #67 
* Adds sharding via ClientBuilder#withShard()
Unfortunately, sharding is extremely inflexible. So hotswapping is impossible, each client requires a seperate shard and discord will reject multiple login requests by sending an INVALID_SESSION op code. Apparently this is due to a hidden rate limit for logins. I am leaving this as a pull request until 2.6.0 in case people have feedback/suggestions.
=> Implements sharding

src/main/java/sx/blah/discord/api/ClientBuilder.java, src/main/java/sx/blah/discord/api/IDiscordClient.java, src/main/java/sx/blah/discord/api/internal/DiscordClientImpl.java, src/main/java/sx/blah/discord/api/internal/DiscordUtils.java, src/main/java/sx/blah/discord/api/internal/DiscordVoiceWS.java, src/main/java/sx/blah/discord/api/internal/DiscordWS.java, src/main/java/sx/blah/discord/handle/impl/obj/VoiceChannel.java, src/test/java/sx/blah/discord/TestBot.java
* Shards not longer require a new instance of IDiscordClient
* Shards can change size after logged in via setShardCount
=> Shard no longer need different IDiscordClient instances

src/main/java/sx/blah/discord/api/internal/DiscordUtils.java, src/main/java/sx/blah/discord/handle/impl/obj/Guild.java, src/main/java/sx/blah/discord/handle/obj/IGuild.java
* Fixed not using an unsigned long to get the shard
* Added getShard to IGuild
=> Changed to an unsigned long and added getShard to IGuild

src/main/java/sx/blah/discord/api/internal/DiscordWS.java
* Fixed the logic behind async which fixes the ReadyEvent being called too early
=> Fixed async logic

.github/PULL_REQUEST_TEMPLATE.md
* [Proof of testing](http://i.imgur.com/sL4UdH4.png)
* Add a sub-bullet under "I have tested this feature thoroughly" for the author to add evidence that they've tested their fix
=> Update PR template to have proof of testing

README.md
* Fix a typo in README
* Fix a link in README
=> Fixes a typo and wrong linking

src/main/java/sx/blah/discord/api/internal/DiscordUtils.java, src/main/java/sx/blah/discord/api/internal/DiscordWS.java, src/main/java/sx/blah/discord/api/internal/json/responses/GuildEmojiUpdateResponse.java, src/main/java/sx/blah/discord/api/internal/json/responses/GuildResponse.java, src/main/java/sx/blah/discord/handle/impl/events/GuildEmojisUpdateEvent.java, src/main/java/sx/blah/discord/handle/impl/obj/Emoji.java, src/main/java/sx/blah/discord/handle/impl/obj/Guild.java, src/main/java/sx/blah/discord/handle/obj/IEmoji.java, src/main/java/sx/blah/discord/handle/obj/IGuild.java, src/main/java/sx/blah/discord/util/MessageTokenizer.java
* [Testing getting emojis](http://i.imgur.com/R6LAGyL.png)
* [Testing emoji update event](http://i.imgur.com/c39JsRf.png)
* Adds IEmoji
* Getters for ID, emoji name, roles, image URL, isManaged, requiresColons
* Adds GuildEmojisUpdateEvent
* Has getters for the old list and new list
=> Add ability to get server custom emojis

src/main/java/sx/blah/discord/util/RequestBuffer.java
* http://imgur.com/gallery/mA8hB
* http://imgur.com/gallery/O8EY4
**Issues Fixed:** None
* adds RequestBuffer.incompleteRequestCount()
=> Adds Incomplete Request Count Tracking

src/main/java/sx/blah/discord/handle/impl/obj/Guild.java, src/main/java/sx/blah/discord/handle/obj/IGuild.java
* Example of IGuild#getUsersByRole http://prnt.sc/cvk5dp
* Example of IGuild#getConnectedVoiceChannel http://prnt.sc/cvk7ya
**Issues Fixed:** None, just adding some useful methods to IGuild
* Adds IGuild#getUsersByRole
* Adds IGuild#getConnectedVoiceChannel
=> Iguildmethods

src/main/java/sx/blah/discord/api/internal/DispatchHandler.java
* [Proof of testing](https://u.pomf.is/ypxyld.webm)
* Ignore MESSAGE_REACTION_ADD and MESSAGE_REACTION_REMOVE events until they are finalized and the documentation is released.
=> Ignore reaction events until feature is finalized

src/main/java/sx/blah/discord/handle/impl/obj/Channel.java, src/main/java/sx/blah/discord/handle/impl/obj/User.java, src/main/java/sx/blah/discord/handle/obj/IUser.java, src/main/java/sx/blah/discord/util/MessageList.java, src/main/java/sx/blah/discord/util/RequestBuffer.java
* http://i.imgur.com/lbrqN8j.png
* http://i.imgur.com/NgW54mK.png
* Fixes issue where MessageList#bulkDelete would not check if the channel is private
* Adds IUser#getPermissionsForGuild and User implementation to do the obvious
=> Adds private check to MessageList#bulkDelete and adds IUser#getPermissionsForGuild

src/main/java/sx/blah/discord/api/internal/DiscordEndpoints.java, src/main/java/sx/blah/discord/api/internal/DiscordUtils.java, src/main/java/sx/blah/discord/api/internal/DispatchHandler.java, src/main/java/sx/blah/discord/api/internal/json/objects/EmbedObject.java, src/main/java/sx/blah/discord/api/internal/json/objects/MessageObject.java, src/main/java/sx/blah/discord/api/internal/json/objects/WebhookObject.java, src/main/java/sx/blah/discord/api/internal/json/requests/WebhookCreateRequest.java, src/main/java/sx/blah/discord/api/internal/json/requests/WebhookEditRequest.java, src/main/java/sx/blah/discord/handle/impl/events/MessageEmbedEvent.java, src/main/java/sx/blah/discord/handle/impl/events/WebhookCreateEvent.java, src/main/java/sx/blah/discord/handle/impl/events/WebhookDeleteEvent.java, src/main/java/sx/blah/discord/handle/impl/events/WebhookUpdateEvent.java, src/main/java/sx/blah/discord/handle/impl/obj/Channel.java, src/main/java/sx/blah/discord/handle/impl/obj/Embed.java, src/main/java/sx/blah/discord/handle/impl/obj/Embedded.java, src/main/java/sx/blah/discord/handle/impl/obj/Guild.java, src/main/java/sx/blah/discord/handle/impl/obj/Message.java, src/main/java/sx/blah/discord/handle/impl/obj/PrivateChannel.java, src/main/java/sx/blah/discord/handle/impl/obj/VoiceChannel.java, src/main/java/sx/blah/discord/handle/impl/obj/Webhook.java, src/main/java/sx/blah/discord/handle/obj/IChannel.java, src/main/java/sx/blah/discord/handle/obj/IEmbed.java, src/main/java/sx/blah/discord/handle/obj/IEmbedded.java, src/main/java/sx/blah/discord/handle/obj/IGuild.java, src/main/java/sx/blah/discord/handle/obj/IMessage.java, src/main/java/sx/blah/discord/handle/obj/IWebhook.java, src/main/java/sx/blah/discord/handle/obj/Permissions.java
* [Proof of testing](http://imgur.com/a/tWDIB)
* Added DiscordEndpoints#WEBHOOKS
* Added DiscordUtils#getWebhookFromJson
* Change DiscordUtils#getEmbedsFromJSON to support the extracted EmbedObject
* Add webhook_id to MessageObject, IMessage, and change DiscordUtils#getMessageFromJSON to support it
* Support WEBHOOKS_UPDATE in DispatchHandler, and load web hooks in DispatchHandler#guildCreate, DispatchHandler#channelUpdate, DispatchHandler#guildRoleUpdate, and DispatchHandler#guildMemberUpdate
* Extracted EmbedObject to its own file, and add the other embedded objects supported by Discord
* Add WebhookObject, WebhookCreateRequest, WebhookEditRequest, WebhookCreateEvent, WebhookDeleteEvent, WebhookUpdateEvent, IWebhook and Webhook
* Change MessageEmbedEvent to support the extracted …
=> Add Webhook support

src/main/java/sx/blah/discord/api/internal/DiscordUtils.java, src/main/java/sx/blah/discord/api/internal/DispatchHandler.java, src/main/java/sx/blah/discord/handle/impl/events/AllUsersReceivedEvent.java, src/main/java/sx/blah/discord/handle/impl/events/GuildMemberChunkReadyEvent.java, src/main/java/sx/blah/discord/handle/impl/obj/Guild.java, src/main/java/sx/blah/discord/handle/obj/IGuild.java
* Added GuildMemberChunkReadyEvent that gets called when all users included offline are loaded
=> Added GuildMemberChunkReadyEvent

src/main/java/sx/blah/discord/util/MissingPermissionsException.java
Add a getter for the missing permissions in MissingPermissionsException.
=> Add getter for missing perms in MPE

.github/ISSUE_TEMPLATE.md
* [Proof of testing](http://i.imgur.com/fAeyEtJ.png)
* Update issue template removing unnecessary line break after link
NOTE: Decided to open this PR against the master branch, since that proposed change has no code changes.
=> Remove unnecessary line break in issue template

README.md
* [Change 1] Reformatted Das section
* [Change 2] Added docs location
=> Added location for Dash documentation

src/main/java/sx/blah/discord/api/ClientBuilder.java, src/main/java/sx/blah/discord/api/internal/DiscordClientImpl.java, src/main/java/sx/blah/discord/api/internal/Requests.java, src/main/java/sx/blah/discord/util/DiscordException.java
* [Proof of testing](https://cdn.discordapp.com/attachments/208023865127862272/265063762778783744/Peek_2017-01-01_11-25.gif)
**Issues Fixed:** Requests which hit a 5xx response would fail. This changes that and makes it retry a few times.
* Add a retry with an exponential backoff with a jitter upon hitting a 5xx
=> Adds 5xx retry

src/main/java/sx/blah/discord/Discord4J.java, src/main/java/sx/blah/discord/api/internal/DiscordUtils.java, src/main/java/sx/blah/discord/modules/IModule.java, src/main/java/sx/blah/discord/modules/ModuleLoader.java, src/main/java/sx/blah/discord/util/MessageBuilder.java, src/main/java/sx/blah/discord/util/RoleBuilder.java
**Issues Fixed:** The possibility to manually load a module without version checking if its class wasn't loaded at runtime. It is also possible to add an already existing or invalid (interface or abstract) module class to the list of module classes.
* Remove unused imports
* Fixed some documentation formatting
* ModuleLoader checks
* Version check when loading modules manually
* Check existence and validity of classes
=> Add ModuleLoader checks and Javadoc fixes

src/main/java/sx/blah/discord/api/internal/DiscordWS.java
Proof of testing:
Triggered an outage situation by blocking outgoing traffic (ABNORMAL_CLOSE), then restoring it.
The image shows increase thread usage while the reconnect was in course, going back to the usual number after it succeeds. The following is the log of this procedure:
https://gist.github.com/quanticc/2a06b4fd9697399131fb8329618c15bd
Also discussed the issue/changes in #bug-reports
I have not tested this change against other kinds of outages, but they all go to the same ReconnectManager#beginReconnect method which in turn calls DiscordWS#connect, where most of the code changed belongs.
* Add a call to stop WebSocketClient upon a reconnect, allowing it to release its resources, avoiding the case where threads would stay running/waiting after a successful reconnect.
* Manage …
=> Release unused websocket threads after a reconnect

src/main/java/sx/blah/discord/api/internal/DispatchHandler.java
Gathering evidence... looking for your feedback @manuelgu 
Dependency: `com.github.quanticc:Discord4j:60d8667`
**Proof of testing:** Thanks to Kagumi#1690
- Ready event not firing due to ConcurrentModificationException
* Use a concurrent collection instead of ArrayList + manual synchronization
=> Fix ReadyEvent not being dispatched

src/main/java/sx/blah/discord/api/ClientBuilder.java, src/main/java/sx/blah/discord/api/internal/json/responses/GatewayBotResponse.java
* http://imgur.com/a/Tq1S7
* Add ClientBuilder#withRecommendedShardCount and all required stuff
=> Add ClientBuilder#withRecommendedShardCount

src/main/java/sx/blah/discord/api/internal/DiscordUtils.java, src/main/java/sx/blah/discord/handle/impl/obj/Channel.java, src/main/java/sx/blah/discord/handle/impl/obj/Guild.java, src/main/java/sx/blah/discord/handle/impl/obj/User.java
Reverts austinv11/Discord4J#223
=> Revert "Fixed user/guild/channel data getting reset"

src/main/java/sx/blah/discord/util/MessageBuilder.java, src/test/java/sx/blah/discord/TestBot.java, src/test/java/sx/blah/discord/examples/ParrotBot.java
* [Proof of testing](http://imgur.com/a/8ZQ0q)
* Add MessageBuilder#withFile
=> Add MessageBuilder#withFile

src/main/java/sx/blah/discord/api/internal/DiscordUtils.java, src/main/java/sx/blah/discord/handle/impl/obj/Channel.java, src/main/java/sx/blah/discord/handle/impl/obj/Guild.java, src/main/java/sx/blah/discord/handle/impl/obj/User.java
* ![image](https://cloud.githubusercontent.com/assets/1905336/24025601/2293eb4a-0b07-11e7-98d4-6927e3ad92ea.png)
* Fixes issue with MAPPER_NO_NULLS not ignoring nulls.
* Fixed sending data which resets User properties
=> Fixed issue with sending data which resets user properties

src/main/java/sx/blah/discord/util/MessageBuilder.java
* Add MessageBuilder#withTTS(boolean)
=> Add MessageBuilder#withTTS(boolean)

src/main/java/sx/blah/discord/util/EmbedBuilder.java
* [Proof of testing](http://imgur.com/a/9c46V)
**Issues Fixed:** None
* Allows copying of fields from other embeds.
=> Allow copying of an IEmbedField

src/main/java/sx/blah/discord/handle/impl/obj/Channel.java, src/main/java/sx/blah/discord/handle/obj/IChannel.java, src/main/java/sx/blah/discord/util/AttachmentPartEntry.java
* trust me bb i TOTALLY tested the SHIT out of this
**Issues Fixed:** you couldn't send multi-attachment messages!!!!
* Support for multi-attachment messages!!!
=> Multi-attachment messages

src/main/java/sx/blah/discord/api/internal/UDPVoiceSocket.java, src/main/java/sx/blah/discord/util/HighPrecisionRecurrentTask.java
* Removes three independent threads and merges into one.
* Better control over the precision of the recurrent sound task.
=> Improvement of audio resources.

src/main/java/sx/blah/discord/api/IDiscordClient.java, src/main/java/sx/blah/discord/api/internal/DiscordClientImpl.java
* [Proof of testing](http://i.imgur.com/XZFD4Jy.png)
**Issues Fixed:** Added missing method to IDiscordClient
* Add getUsersByName method to IDiscordClient
=> Add getUsersByName method to client

src/main/java/sx/blah/discord/api/events/EventDispatcher.java
* Manually tested, cannot write an automated tests since the behavior is not observable other than thru logs
* ClassCastException when using waitFor with a predicate.
=> fixed class cast exception under waitFor

src/main/java/sx/blah/discord/util/EmbedBuilder.java
* Add EmbedBuilder#clearFields
=> Add EmbedBuilder#clearFields

src/main/java/sx/blah/discord/api/internal/UDPVoiceSocket.java
* tested with local bot
When the udpsocket is closed, the recurrent voice handling task might be half thru receiving a socket closed exception
=> fix concurrent usage of the udpsocket

src/main/java/sx/blah/discord/api/internal/UDPVoiceSocket.java
* I've been using this logic for a while
incrementally lagging behind due to packets arriving late and only consuming at most one every frame.
=> handle audio packet bursts

src/main/java/sx/blah/discord/util/audio/AudioPlayer.java
Tried to simplify the title but it's a bit complicated to explain it.
It's pretty much similar to my older pull request, #151.
Basically: when calling the **Track** constructor with `IAudioProvider` parameter type, it implies that this provider has no `AudioInputStream` available, but it could have if it was an instance of `AudioInputStreamProvider`.
Even though there is a overloaded constructor for `AudioInputStreamProvider` instances (which handle it correctly), **polymorphism** is not taken into account, because, if I have a `AudioInputStreamProvider` instance, but it's declared type (into a variable, etc) is `IAudioProvider`, it would call the first constructor (with `IAudioProvider` parameter type).
* In my last PR, I posted some screenshots and it got downvoted on imgur, so I won't …
=> Unify the Track's constructors with IAudioProvider and AudioInputStreamProvider parameter types into a single one

src/main/java/sx/blah/discord/api/internal/DispatchHandler.java
MessageUpdateEvent not being sent 
- due to comparing equality of old and new message content
=> Fix MessageUpdateEvent not being dispatched

docs/Reactions.md
Docs page detailing reactions
**Issues Fixed:** PR broke last time
* Reactions.md
...
=> Reactions.md

README.md
* [It's just text](#)
**Issues Fixed:** I had a difficult time figuring out how to add this when using SBT
* Add SBT section to README.MD
=> SBT with D4J

docs/FAQ.md, docs/MessageHistory.md
* Just text
**Issues Fixed:** We didn't have these
* I added MessageHistory and FAQ pages
...
=> More doc things

docs/FAQ.md
Added dec's example bot for music playing
* Literally text
**Issues Fixed:** Wasn't there
* Added the link, changed sentence structure.
...
=> Added Dec's example bot the FAQ for music playing

src/main/java/sx/blah/discord/api/internal/DiscordEndpoints.java, src/main/java/sx/blah/discord/handle/impl/obj/User.java
* [Proof of testing](http://nope/)
**Issues Fixed:** getAvatar() would return an invalid avatar instead of `null`
* Add an if check
=> Fix avatar not being null when it's null

docs/RateLimitExceptions-and-you.md
* It's markdown, it's visually fine
**Issues Fixed:** *None*
* Added an example of `RequestBuilder` to the wiki as suggested by @decyg as an alternative to `RequestBuffer`.
=> Added RequestBuilder example to wiki as an alternative to RequestBuffer

src/main/java/sx/blah/discord/api/events/EventDispatcher.java, src/test/java/sx/blah/discord/api/events/EventDispatcherTest.java
* I have tested custom executors features extensively, and added a test that verifies that backpressure logic.
**Issues Fixed:** Unbounded resources usage under congestion leading to system halting.
* New default for the dispatcher that will never exhaust resources
* Library user now has the ability to choose the executor where his listeners are used.
=> Dispatcher custom executors + backpressure

src/main/java/sx/blah/discord/api/internal/DiscordUtils.java
**Issues Fixed:** Fixed pattern
* Fixed twitch pattern
Copied from JDA source
=> Fixed twitch regex to allow www prefix

src/main/java/sx/blah/discord/api/internal/DiscordUtils.java, src/main/java/sx/blah/discord/api/internal/ShardImpl.java, src/main/java/sx/blah/discord/api/internal/json/objects/GameObject.java, src/main/java/sx/blah/discord/api/internal/json/objects/PresenceObject.java, src/main/java/sx/blah/discord/api/internal/json/requests/PresenceUpdateRequest.java, src/main/java/sx/blah/discord/handle/impl/obj/Presence.java
This changes internal functionality of presences to be cleaner than previously. This presents no external changes for the user. I'm just submitting this as a PR for the sake of public review.
=> Refactored internal presence usage

src/main/java/sx/blah/discord/api/internal/DiscordUtils.java, src/main/java/sx/blah/discord/handle/impl/events/guild/channel/ChannelEvent.java
* Sending a message with the bot and receiving one in a private message is not throwing any errors anymore with the TestBot.
**Issues Fixed:** UOEs thrown when receiving or sending messages from/to private channels.
* Fixed some checks that should've been done originally
=> Fixed UOEs on Private Channel

src/main/java/sx/blah/discord/api/ClientBuilder.java
* It's small enough change to not really warrant it. How / why this was implemented as *this* is beyond me.
**Issues Fixed:** Make `setShard` actually work. Additionally, add a check to not do negative indexes.
* Fixed comparison between `totalShards` and `shardIndex`
* Added a check for `shardIndex` and negative values
=> Fixed sharding check

src/main/java/sx/blah/discord/api/ClientBuilder.java, src/main/java/sx/blah/discord/api/IDiscordClient.java, src/main/java/sx/blah/discord/api/IShard.java, src/main/java/sx/blah/discord/api/internal/DiscordClientImpl.java, src/main/java/sx/blah/discord/api/internal/DiscordUtils.java, src/main/java/sx/blah/discord/api/internal/ShardImpl.java, src/main/java/sx/blah/discord/api/internal/json/objects/GameObject.java, src/main/java/sx/blah/discord/api/internal/json/requests/PresenceUpdateRequest.java, src/main/java/sx/blah/discord/handle/impl/obj/Presence.java, src/main/java/sx/blah/discord/handle/obj/ActivityType.java, src/main/java/sx/blah/discord/handle/obj/IPresence.java, src/main/java/sx/blah/discord/handle/obj/PresenceType.java, src/test/java/sx/blah/discord/SpoofBot.java, src/test/java/sx/blah/discord/TestBot.java, src/test/java/sx/blah/discord/examples/AccountBot.java
* [Proof of testing](https://glorantq-cloud.s-ul.eu/7eEvYj4Z.gif)
**Issues Fixed:** No issues fixed
* Added support for different presence types (watching and listening to)
=> Added support for other presence types

docs/index.md
* It's text
**Issues Fixed:** Javadocs weren't easy to find.
* Add the Javadocs to the wiki.
...
=> Add javadocs to wiki

src/main/java/sx/blah/discord/handle/impl/obj/Presence.java
**Issues Fixed:** [The issues fixed by this pull request]
Fixed presence lack of toString method. making logs a bit messy printing the object refrence instead of the value of presence 
* [Change 1] Added toString method
=> Added to string method to presence

.gitignore
* [Proof of testing](https://i.imgur.com/vQ0KsNI.png)
**Issues Fixed:** Setting up an eclipse workspace would cause a lot of local files to be tracked by git.
* Add some eclipse files to the .gitignore file
* Make the /bin/ entry more inclusive
...
=> Improve gitignore, add entries for different IDEs

core/src/main/java/discord4j/core/object/entity/Member.java, core/src/main/java/discord4j/core/spec/GuildMemberEditSpec.java, core/src/main/java/discord4j/core/spec/GuildMemberModifySpec.java, rest/src/main/java/discord4j/rest/json/request/GuildMemberModifyRequest.java
**Issues Fixed:** Previously this was only accessible through the RestClient
* Add Member#modifyGuildMember
* Add Member#changeNickname
=> Add ModifyGuildMember endpoint for core

src/main/java/sx/blah/discord/api/internal/DiscordVoiceWS.java
* [Proof of voice disconnecting in the same second after calling IVoiceChannel#leave](https://i.imgur.com/ujcma8j.png)
**Issues Fixed:** Fixes the delay that happens from disconnecting a voice websocket.
* Fixes the approximately 30 second delay it takes for a voice websocket to close
=> Fixes delay when disconnecting a voice websocket (Supersedes #445)

src/main/java/sx/blah/discord/handle/impl/obj/Message.java
**Issues Fixed:** [The issues fixed by this pull request]
Fixes #431
* [Change 1] Fix mention list condition so it adds everyone to list of mentions only when everyone mention is valid(user has permission).
=> #431 add to mentions everyone only when everyone mention is valid

core/src/main/java/discord4j/core/spec/AuditLogQuerySpec.java, core/src/main/java/discord4j/core/spec/AuditSpec.java, core/src/main/java/discord4j/core/spec/BanQuerySpec.java, core/src/main/java/discord4j/core/spec/CategoryCreateSpec.java, core/src/main/java/discord4j/core/spec/CategoryEditSpec.java, core/src/main/java/discord4j/core/spec/EmbedCreateSpec.java, core/src/main/java/discord4j/core/spec/GuildCreateSpec.java, core/src/main/java/discord4j/core/spec/VoiceChannelCreateSpec.java
**Description:** This pull request is the start of documenting classes in core which do not have documentation. This is the first iteration and is open to revision and adding more documentation to other classes.
**Justification:** Add documentation so users know what methods and classes do in core.
=> Core Javadocs

common/src/main/java/discord4j/common/json/Mention.java, common/src/main/java/discord4j/common/json/MessageMember.java, core/src/main/java/discord4j/core/event/dispatch/MessageDispatchHandlers.java, core/src/main/java/discord4j/core/object/data/stored/MemberBean.java, core/src/main/java/discord4j/core/object/data/stored/MessageBean.java, gateway/src/main/java/discord4j/gateway/json/dispatch/MessageCreate.java, gateway/src/main/java/discord4j/gateway/json/dispatch/MessageUpdate.java
Added the missing attributes to the `MessageUpdate` dispatch:
- type
- tts
- timestamp
- pinned
- nonce
- mentions*
- mention_roles*
- mention_everyone*
- edited_timestamp*
- author
- attachments
_`*` means useful for users. Any other properties are added either for completeness or because D4J could use it to be as true to Discord's payloads as possible._
Implemented `Bean` updating for:
- mentions
- mention_roles
- mention_everyone
- edited_timestamp
Without this, significant parts of the `MessageUpdate` dispatch are missing and inaccessible through the API.
Note: mention_everyone is not currently included in `MessageCreateEvent` or `MessageUpdateEvent`, so I couldn't test it. I have however tested it via the GatewayClient.
**Tests:**
Code:
```java …
```
=> Add missing properties to MessageUpdate dispatch and implement Bean update

core/src/main/java/discord4j/core/object/audit/ChangeKey.java, core/src/main/java/discord4j/core/object/data/stored/BaseGuildBean.java, core/src/main/java/discord4j/core/object/entity/Guild.java, core/src/main/java/discord4j/core/spec/GuildEditSpec.java, gateway/src/main/java/discord4j/gateway/json/dispatch/GuildCreate.java, gateway/src/main/java/discord4j/gateway/json/dispatch/GuildUpdate.java, rest/src/main/java/discord4j/rest/json/request/GuildModifyRequest.java, rest/src/main/java/discord4j/rest/json/response/GuildResponse.java
**Description:** Look into docs where the banner parameter work same as splash, i make a support for this parameter of guild
**Justification:** https://github.com/Discord4J/Discord4J/issues/520
**Note**: a have i little question about this... the https://discordapp.com/developers/docs/resources/guild#modify-guild not show about the banner, dont know exactly if cant change the parameter or discord forget add this (i can test this because dont have a verified server for test)
=> Support to Banner image in Guild

core/src/main/java/discord4j/core/object/entity/Guild.java, core/src/main/java/discord4j/core/object/entity/GuildEmoji.java, core/src/main/java/discord4j/core/object/entity/User.java, core/src/main/java/discord4j/core/object/util/Image.java
Add `Mono<Image> forUrl(String)` and make use of it anywhere we provide the url of an image.
This is a useful QoL feature that was requested.
=> Add some image utilities and docs

common/src/main/java/discord4j/common/json/GuildMemberResponse.java, common/src/main/java/discord4j/common/json/MessageMember.java, core/src/main/java/discord4j/core/object/data/stored/BaseGuildBean.java, core/src/main/java/discord4j/core/object/data/stored/GuildBean.java, core/src/main/java/discord4j/core/object/data/stored/MemberBean.java, core/src/main/java/discord4j/core/object/entity/Guild.java, core/src/main/java/discord4j/core/object/entity/Member.java, core/src/main/java/discord4j/core/object/entity/Message.java, gateway/src/main/java/discord4j/gateway/json/dispatch/GuildCreate.java, gateway/src/main/java/discord4j/gateway/json/dispatch/GuildUpdate.java, rest/src/main/java/discord4j/rest/json/response/GuildResponse.java
**Description:** Well discord release the boost feature for guilds, and add new values in Guild properties 
https://discordapp.com/developers/docs/resources/guild#guild-object-premium-tier
https://discordapp.com/developers/docs/resources/guild
**Justification:** Support to boost features (read values)
=> Support for new values in boost feature

core/src/main/java/discord4j/core/object/data/stored/GuildBean.java, gradle.properties
**Description:** Im not sure why is this cause in createguild, but this can fix or patch the issue.
=> Fix for duplicate members

core/src/main/java/discord4j/core/object/entity/Message.java, core/src/main/java/discord4j/core/spec/GuildMemberEditSpec.java, core/src/main/java/discord4j/core/spec/TextChannelEditSpec.java
**Description:** Like https://github.com/Discord4J/Discord4J/pull/541 another PR with changes in docs for little changes (like the new rateLimitPerUser in channel or warn about mute/deaf in user)
**Note:** Im looking if another docs need changes like this.
=> Improvement in docs for limits and another discord docs

common/src/main/java/discord4j/common/json/MessageReferenceResponse.java, common/src/main/java/discord4j/common/json/MessageResponse.java, core/src/main/java/discord4j/core/object/MessageReference.java, core/src/main/java/discord4j/core/object/data/stored/MessageBean.java, core/src/main/java/discord4j/core/object/data/stored/MessageReferenceBean.java, core/src/main/java/discord4j/core/object/entity/Guild.java, core/src/main/java/discord4j/core/object/entity/Message.java, core/src/main/java/discord4j/core/object/util/Permission.java, gateway/src/main/java/discord4j/gateway/json/dispatch/MessageCreate.java, rest/src/main/java/discord4j/rest/json/request/SuppressEmbedsRequest.java, rest/src/main/java/discord4j/rest/route/Routes.java, rest/src/main/java/discord4j/rest/service/ChannelService.java
**Description:** Its a WIP about little changes in discord messages (WIP Because its working but not document) and anothe changes for discord features.
Reference: Tests in servers and https://github.com/discordapp/discord-api-docs/pull/1051
=> Support missing message fields

rest/src/main/java/discord4j/rest/http/client/ClientException.java, rest/src/test/java/discord4j/rest/service/UserServiceTest.java
Change the return type of ClientException#getErrorResponse() from a Nullable ErrorResponse to an Optional<ErrorResponse>.
This change was requested in Issue #517
=> Change return type of ClientException#getErrorResponse

core/src/main/java/discord4j/core/object/ExtendedInvite.java, core/src/main/java/discord4j/core/object/data/ExtendedInviteBean.java, rest/src/main/java/discord4j/rest/json/response/InviteResponse.java
**Description:** In fact, this field does not exist.
**Justification:** https://github.com/discordapp/discord-api-docs/pull/1115
=> Remove revoked field

core/src/main/java/discord4j/core/object/presence/Activity.java
**Description:** Update streaming activity documentation.
**Justification:** https://github.com/discordapp/discord-api-docs/commit/c2877c795d1f6f7eeee0a80f1645f8a260c0c3f1
=> Update streaming activity documentation

core/src/main/java/discord4j/core/object/audit/ChangeKey.java
**Description:** Add missing audit log change keys
**Justification:** https://github.com/discordapp/discord-api-docs/commit/7f1c991e1f481455bf7ffd9246d0f06d97693c65
=> Add missing audit log change keys

core/src/main/java/discord4j/core/object/audit/ActionType.java
**Description:** Add the new audit log events
**Justification:** https://github.com/discordapp/discord-api-docs/commit/63643f23f64b0a80c4e589507dd8a6fd14c5f992
=> Add the new audit log events

core/src/main/java/discord4j/core/event/dispatch/MessageDispatchHandlers.java, core/src/main/java/discord4j/core/event/domain/message/ReactionAddEvent.java, gateway/src/main/java/discord4j/gateway/json/dispatch/MessageReactionAdd.java
**Description:** Add member to reaction add event.
**Justification:** https://github.com/discordapp/discord-api-docs/commit/74fbed9ec3e54fea84abaf14f4c3bffa729f02a1
=> Add member to reaction add event

core/src/main/java/discord4j/core/event/dispatch/DispatchHandlers.java, core/src/main/java/discord4j/core/event/domain/InviteCreateEvent.java, core/src/main/java/discord4j/core/event/domain/InviteDeleteEvent.java, gateway/src/main/java/discord4j/gateway/json/dispatch/EventNames.java, gateway/src/main/java/discord4j/gateway/json/dispatch/InviteCreate.java, gateway/src/main/java/discord4j/gateway/json/dispatch/InviteDelete.java, gateway/src/main/java/discord4j/gateway/json/jackson/PayloadDeserializer.java
**Description:** Support for incoming new invite events
**Justification:** https://github.com/discordapp/discord-api-docs/pull/1309
=> Support for Invite Events

core/src/main/java/discord4j/core/event/dispatch/DispatchHandlers.java, core/src/main/java/discord4j/core/event/domain/InviteCreateEvent.java, gateway/src/main/java/discord4j/gateway/json/dispatch/InviteCreate.java
**Description:** Invite create inviter field if now nullable.
**Justification:** Fix #617
=> Fix inviter is now nullable

core/src/main/java/discord4j/core/object/entity/User.java
**Description:** Adds a util method to the user object
**Justification:** This method is often used to display the user's unique name, but currently you have to build your own (util) methods for this.
=> Added method "getTag" to User object

core/src/main/java/discord4j/core/event/domain/PresenceUpdateEvent.java, core/src/main/java/discord4j/core/object/Embed.java, core/src/main/java/discord4j/core/object/entity/Guild.java, core/src/main/java/discord4j/core/object/entity/channel/BaseMessageChannel.java
**Description:** Fixes some issues similar to https://github.com/Discord4J/Discord4J/pull/626
=> Fix NoSuchElementException

core/src/main/java/discord4j/core/object/entity/Guild.java
**Description:** Supports `Guild#discoverySplash()`, `Guild#systemChannelFlags()` and updates default max presences.
Replaces #605 .
**Justification:** https://github.com/discordapp/discord-api-docs/blob/ee6a2190abc160e11a319ec49b1b0eb58a659fd9/docs/resources/Guild.md#guild-object
https://github.com/discordapp/discord-api-docs/pull/1428
=> Update Guild fields

rest/src/main/java/discord4j/rest/util/Permission.java
**Description:** Adds `VIEW_GUILD_INSIGHTS` permission.
**Justification:** https://github.com/discordapp/discord-api-docs/pull/1421
=> Add VIEW_GUILD_INSIGHTS permission

common/src/main/java/discord4j/common/ReactorResources.java
**Description:** Adds ReactorResources.Builder.
**Justification:** This allows to easily create a custom ReactorResources without having to recreate the whole object.
=> Add ReactorResources.Builder

core/src/main/java/discord4j/core/event/dispatch/DispatchHandlers.java, core/src/main/java/discord4j/core/event/dispatch/GuildDispatchHandlers.java
* When a member disconnects from a voice channel, their associated `VoiceState` will now be removed from stores
* When a member leaves a guild, it will now delete the `Presence`, and if the bot no longer has mutual servers with the user, it will also delete the `User`.
The stores should always be cleaned properly when a user leaves a voice channel or a guild. For voice channels it didn't clean up the voice state, and for guilds it didn't clean up the Presence, causing orphan entities to remain in the stores and taking up memory for nothing.
Since users can be in many guilds, the user data should be removed when they leave the last guild they had in common with the bot.
=> Fix entities not being properly removed from stores on voice disconnect and guild leave

core/src/main/java/discord4j/core/shard/DefaultShardingStrategy.java
**Description:** Sharding factor must always be a power of 2
=> Validate sharding factor

core/src/test/java/discord4j/core/logback/GatewayEventFilter.java
**Description:** Changes `GatewayEventFilter` to be able to exclude / include multiple events.
**Justification:** The example [here](https://github.com/Discord4J/Discord4J/blob/c1dd95d2812d73ce30a262f3fae7c168c3766223/core/src/test/resources/logback.xml#L16) is showing usage of this filter with multiple `<Include>` tags but the current version is not allowing this type of setup. By calling `setInclude` on each tag, it is reset and only the last tag is taken into account. This PR aims to fix this.
=> GatewayEventFilter can now exclude/include multiple events

core/src/main/java/discord4j/core/shard/GatewayBootstrap.java, gateway/src/main/java/discord4j/gateway/IdentifyOptions.java, gateway/src/main/java/discord4j/gateway/PayloadHandlers.java, gateway/src/main/java/discord4j/gateway/intent/Intent.java, gateway/src/main/java/discord4j/gateway/intent/IntentSet.java, gateway/src/test/java/discord4j/gateway/GatewayClientTest.java
**Description:** Added intents field to the identify payload, which will be mandatory soon, according to https://gist.github.com/msciotti/223272a6f976ce4fda22d271c23d72d9
**Justification:** https://gist.github.com/msciotti/223272a6f976ce4fda22d271c23d72d9
=> New Identify Field: Intents

gateway/src/main/java/discord4j/gateway/DefaultGatewayClient.java
**Description:** Added a list of close codes which should not retry
**Justification:** Issue #656
=> Close codes which shouldn't retry

core/src/main/java/discord4j/core/object/entity/Message.java, rest/src/main/java/discord4j/rest/route/Routes.java, rest/src/main/java/discord4j/rest/service/ChannelService.java
**Description:** Added support for Delete All Reactions for Emoji endpoint.
**Justification:** Issue #630
=> Add REST support for "Delete All Reactions for Emoji"

gateway/src/main/java/discord4j/gateway/intent/Intent.java
**Description:** Updates Intent documentation.
**Justification:** https://github.com/discord/discord-api-docs/pull/1495
=> Update Intent documentation

core/src/main/java/discord4j/core/event/dispatch/DispatchHandlers.java, core/src/main/java/discord4j/core/event/dispatch/MessageDispatchHandlers.java, core/src/main/java/discord4j/core/event/domain/message/ReactionRemoveEmojiEvent.java
Implements a missing event, this PR depends on a discordjson PR:
https://github.com/Discord4J/discord-json/pull/12
https://discordapp.com/developers/docs/topics/gateway#message-reaction-remove-emoji
=> Implemented event for ReactionRemoveEmoji-Event

core/src/main/java/discord4j/core/object/data/stored/MessageBean.java, core/src/main/java/discord4j/core/object/entity/Message.java, rest/src/main/java/discord4j/rest/route/Routes.java, rest/src/main/java/discord4j/rest/service/ChannelService.java
**Description:** Support in Message for crosspost and add new types of messages.
https://github.com/discord/discord-api-docs/issues/1161
https://github.com/discord/discord-api-docs/issues/1510
https://github.com/discord/discord-api-docs/blob/8468643e78741af8d7d3186e11ac22c0a7486d60/docs/resources/Channel.md
=> Support for Crosspost a message and other changes

core/src/main/java/discord4j/core/object/data/stored/BaseGuildBean.java, core/src/main/java/discord4j/core/object/data/stored/GuildBean.java, core/src/main/java/discord4j/core/object/entity/Guild.java, gateway/src/main/java/discord4j/gateway/json/dispatch/GuildCreate.java, gateway/src/main/java/discord4j/gateway/json/dispatch/GuildUpdate.java, rest/src/main/java/discord4j/rest/json/response/GuildResponse.java
- ReWork of premiumSubscriptionsCount (Confused for my last PR about this)
- Support of the Public Update Channel (Featured Guilds)
- Support of the Rules Channel in Guild
- Flags of System Channel in Guild
**Justification:** Support for the documented fields in Guild (https://github.com/discord/discord-api-docs/blob/master/docs/resources/Guild.md)
=> Support for new elements in Guilds

core/src/main/java/discord4j/core/object/entity/channel/VoiceChannel.java
**Description:** Provides a simple option to connect to a voice channel through the VoiceChannel API without having to send a raw gateway payload.
**Justification:** At the moment you need to do a raw gateway call to connect to a voice-channel with an external library.
=> Voice channel distribution

core/src/main/java/discord4j/core/event/domain/message/ReactionRemoveEmojiEvent.java, core/src/main/java/discord4j/core/object/audit/ActionType.java, core/src/main/java/discord4j/core/object/audit/AuditLogEntry.java, core/src/main/java/discord4j/core/object/audit/ChangeKey.java, core/src/main/java/discord4j/core/object/entity/Message.java, core/src/main/java/discord4j/core/object/presence/Status.java, core/src/main/java/discord4j/core/util/OrderUtil.java
**Description:** This pull request aims to add some missing documentations. It also fixes one unused import and three `public static` fields that were not `final`.
_Note:_ During the documentation, I have found a Change key `changeKey("banner_hash")` that does not exist on the discord documentation and that does not seem to have ever existed.
**Justification:** Documentation is for cool guys.
=> Adds some documentations

core/src/main/java/discord4j/core/object/ExtendedInvite.java, core/src/main/java/discord4j/core/object/data/ExtendedInviteBean.java
**Description:** Fix a issue related to InviterId
**Justification:** https://discord.com/developers/docs/resources/invite#invite-object
=> Fix Discord4J/Discord4J#701 (Inviter Optional)

core/src/main/java/discord4j/core/object/entity/Guild.java
**Description:** Adds `Guild#getMaxVideoChannelUsers()`
**Justification:** https://github.com/Discord4J/discord-json/pull/16
=> Adds Guild#getMaxVideoChannelUsers()

core/src/main/java/discord4j/core/event/dispatch/ChannelDispatchHandlers.java, core/src/main/java/discord4j/core/event/domain/channel/PinsUpdateEvent.java
**Description:** Fix https://github.com/Discord4J/Discord4J/issues/691
https://github.com/Discord4J/discord-json/pull/18
=> PinsUpdateEvent#last_pin_timestamp is nullable

core/src/main/java/discord4j/core/GatewayResources.java, core/src/main/java/discord4j/core/retriever/StoreEntityRetriever.java, core/src/main/java/discord4j/core/shard/GatewayBootstrap.java
**Description:** Add a filter for guild intent and if the member list is 1 in size, also add a copy of IntentSet to GatewayResources
**Justification:** Fixes #708
=> Fix members list only containing the bot user with guild intent declared

core/src/main/java/discord4j/core/object/VoiceState.java
**Description:** Adds `VoiceState#isSelfVideoEnabled`
**Justification:** https://github.com/Discord4J/discord-json/pull/21
=> Adds VoiceState#isSelfVideoEnabled

core/src/main/java/discord4j/core/event/dispatch/LifecycleDispatchHandlers.java, core/src/main/java/discord4j/core/event/domain/lifecycle/DisconnectEvent.java, gateway/src/main/java/discord4j/gateway/DefaultGatewayClient.java, gateway/src/main/java/discord4j/gateway/retry/ClosingStateChange.java, gateway/src/main/java/discord4j/gateway/retry/GatewayStateChange.java
**Description:** Adds the disconnect cause and status to DisconnectEvent
**Justification:** It is useful to have the cause and status as user so you can collect metrics and other things
=> add disconnect cause and status to DisconnectEvent

core/src/main/java/discord4j/core/object/data/stored/BaseGuildBean.java, core/src/main/java/discord4j/core/object/data/stored/GuildBean.java, core/src/main/java/discord4j/core/object/entity/Guild.java
**Description:** Fix issue with Guild::getPremiumSubscriptionsCount
=> Fix issue related with Premium Count.

common/src/main/java/discord4j/common/close/CloseStatus.java
**Justification:** Having getReason return an empty string doesn't make sense
=> make CloseStatus#getReason return empty if reason is blank

common/src/main/java/discord4j/common/json/GuildEmojiResponse.java, core/src/main/java/discord4j/core/object/data/stored/GuildEmojiBean.java, core/src/main/java/discord4j/core/object/entity/GuildEmoji.java
**Description:** Give a method for get if Emoji is available or not (this can happen in most cases when lost boost level)
**Justification:** Discord Docs https://discord.com/developers/docs/resources/emoji#get-guild-emoji
=> Method isAvailable in GuildEmoji

common/src/main/java/discord4j/common/json/UserResponse.java, core/src/main/java/discord4j/core/object/data/stored/UserBean.java, core/src/main/java/discord4j/core/object/entity/User.java
**Description:** Add support for get public flags avaible for User
=> Support for Public Flags of User

gateway/src/main/java/discord4j/gateway/SessionInfo.java, gateway/src/main/java/discord4j/gateway/ShardInfo.java, gateway/src/main/java/discord4j/gateway/intent/IntentSet.java, rest/src/main/java/discord4j/rest/util/Color.java, rest/src/main/java/discord4j/rest/util/Image.java, rest/src/main/java/discord4j/rest/util/PermissionSet.java
There were surprisingly few needed :3.
=> Add @Nullable annotation to equals methods.

docs/Frequently-Asked-Questions.md, docs/Migrating-from-v2.x-to-v3.1.md, docs/Music-Bot-Tutorial.md, docs/index.md
**Description:** Update links to discordapp.com to use discord.com instead (Note: cdn.discord.com doesn't work yet)
**Justification:** Use the new Discord domain
=> Update Discord URL

core/src/main/java/discord4j/core/spec/AuditLogQuerySpec.java
**Description:** More query in the Spec in base of https://discord.com/developers/docs/resources/audit-log#get-guild-audit-log
**Justification:** TheNumeralOne >.<
=> Support for more querys in AuditLogQuerySpec

rest/src/main/java/discord4j/rest/entity/RestMessage.java
**Description:** In another PR i see a //TODO for a rest method to remove all reactions for emoji, not sure if the TODO refer only to this class because the method in implemented in anothers.
=> REST for remove emoji reaction

core/src/main/java/discord4j/core/object/entity/Guild.java
**Description:** Little angry men are gone.
**Justification:** https://github.com/discord/discord-api-docs/pull/2140/files
=> Update Guild documentation

core/src/main/java/discord4j/core/object/entity/Guild.java
**Description:** "Public" has been renamed to "Community".
**Justification:** https://github.com/discord/discord-api-docs/pull/1763
=> Update Community Guild documentation

rest/src/main/java/discord4j/rest/request/RequestStream.java
**Description:** Automatically retry on CloudFlare's error 520
**Justification:** Closes https://github.com/Discord4J/Discord4J/issues/802
=> Automatically retry on CloudFlare's error 520

core/src/main/java/discord4j/core/object/entity/Message.java, core/src/main/java/discord4j/core/spec/MessageCreateSpec.java, core/src/main/java/discord4j/core/spec/MessageReferenceSpec.java, rest/src/main/java/discord4j/rest/util/AllowedMentions.java
- Adds support for inline replies
Fixes: https://github.com/Discord4J/Discord4J/issues/789
https://github.com/Discord4J/discord-json/pull/36/files
https://github.com/discord/discord-api-docs/pull/2118
=> Add support for inline replies

core/src/main/java/discord4j/core/object/RoleTags.java, core/src/main/java/discord4j/core/object/entity/Role.java
**Description:** Support role tags.
Fixes: https://github.com/Discord4J/Discord4J/issues/741
Depends on: https://github.com/Discord4J/discord-json/pull/37
=> Support role tags

core/src/main/java/discord4j/core/object/entity/Member.java, gradle.properties
**Description:** Adds member `pending` field.
**Justification:** https://github.com/Discord4J/discord-json/pull/41
=> Add member pending field

rest/src/main/java/discord4j/rest/route/Routes.java, rest/src/main/java/discord4j/rest/service/ApplicationService.java
**Description:** Adds GET routes for commands.
**Justification:** https://github.com/discord/discord-api-docs/commit/093ea60e52e86d78ae22635abf5b64c358e6d04d
=> Adds GET .../command/:id

rest/src/main/java/discord4j/rest/route/Routes.java
**Description:** Updates `GUILD_MEMBER_MODIFY` Route documentation.
**Justification:** https://github.com/discord/discord-api-docs/pull/2505
=> Update GUILD_MEMBER_MODIFY Route doc

core/src/main/java/discord4j/core/event/domain/VoiceStateUpdateEvent.java
Missed javadoc descriptor character (@). 
I accidentally noticed this and decided to fix it.
=> Correct javadoc descriptor

core/src/main/java/discord4j/core/object/Ban.java, core/src/main/java/discord4j/core/object/Embed.java, core/src/main/java/discord4j/core/object/FollowedChannel.java, core/src/main/java/discord4j/core/object/MessageReference.java, core/src/main/java/discord4j/core/object/Region.java, core/src/main/java/discord4j/core/object/RoleTags.java, core/src/main/java/discord4j/core/object/VoiceState.java, core/src/main/java/discord4j/core/object/audit/AuditLogEntry.java, core/src/main/java/discord4j/core/object/entity/ApplicationInfo.java, core/src/main/java/discord4j/core/object/entity/Attachment.java, core/src/main/java/discord4j/core/object/entity/Guild.java, core/src/main/java/discord4j/core/object/entity/GuildEmoji.java, core/src/main/java/discord4j/core/object/entity/Member.java, core/src/main/java/discord4j/core/object/entity/Message.java, core/src/main/java/discord4j/core/object/entity/Role.java, core/src/main/java/discord4j/core/object/entity/Sticker.java, core/src/main/java/discord4j/core/object/entity/User.java, core/src/main/java/discord4j/core/object/entity/Webhook.java, core/src/main/java/discord4j/core/object/presence/Activity.java, core/src/main/java/discord4j/core/object/reaction/Reaction.java
**Description:** Exposes data of entities to make the use of lower level parts possible.
**Justification:** https://github.com/Discord4J/Discord4J/issues/829
=> Add exposing data of entities

core/src/main/java/discord4j/core/object/audit/ChangeKey.java
**Description:** `ChangeKey` class was missing some values, some values were incorrect and the awt.Color class was still used.
**Justification:** https://discord.com/developers/docs/resources/audit-log#audit-log-change-object-audit-log-change-key
=> Updates ChangeKey

core/src/main/java/discord4j/core/shard/GatewayBootstrap.java, core/src/main/java/discord4j/core/shard/ShardingStrategy.java
This changes the interface of the `ShardingStrategy` in a backwards-compatible way to allow fetching the max concurrency from the Discord, and changes the `recommended` ShardingStrategy to do that.
The recommended ShardingStrategy NOT using the maxConcurrency as recommended by Discord caught me by surprise. Let's avoid surprises for future devs using this strategy with large bots.
=> Recommended ShardStrategy should use maxConcurrency as recommended by Discord

core/src/main/java/discord4j/core/object/entity/Message.java
**Description:** Adds loading message flag.
**Justification:** https://github.com/discord/discord-api-docs/pull/2685
=> Adds loading message flag

core/src/main/java/discord4j/core/event/dispatch/GuildDispatchHandlers.java, core/src/main/java/discord4j/core/event/domain/guild/MemberUpdateEvent.java
**Description:** Adds pending field to MemberUpdateEvent
**Justification:** https://github.com/Discord4J/discord-json/commit/f2db2fd0290ebad1d58bda32823898f9089bc6e3
=> Add pending field to MemberUpdateEvent

core/src/main/java/discord4j/core/object/command/Interaction.java, gradle.properties
**Description:** Adds `InteractionData#getApplicationId`.
**Justification:** https://github.com/Discord4J/discord-json/commit/ae8d903024e93f9edff5b142ec703ff3c368d1cd
=> Add InteractionData#getApplicationId

core/src/main/java/discord4j/core/object/VoiceState.java, core/src/main/java/discord4j/core/object/entity/channel/Channel.java, gradle.properties, rest/src/main/java/discord4j/rest/route/Routes.java, rest/src/main/java/discord4j/rest/service/GuildService.java, rest/src/main/java/discord4j/rest/service/VoiceService.java, rest/src/main/java/discord4j/rest/util/Permission.java
**Description:** Adds Stage channels.
https://github.com/Discord4J/discord-json/pull/55
https://github.com/discord/discord-api-docs/pull/2751
=> Adds Stage channel

rest/src/main/java/discord4j/rest/entity/RestGuild.java, rest/src/main/java/discord4j/rest/route/Routes.java, rest/src/main/java/discord4j/rest/service/GuildService.java
**Description:** Adds RestGuild#searchMembers
**Justification:** https://github.com/Discord4J/discord-json/pull/66
=> Adds RestGuild#searchMembers

core/src/main/java/discord4j/core/object/entity/Guild.java, core/src/main/java/discord4j/core/object/entity/Message.java
**Description:** Adds GUILD_INVITE_REMINDER. This could be targetting `3.1.x` but it is not indicated if the value would be 0 or 22.
**Justification:** https://github.com/discord/discord-api-docs/pull/2753/files
=> Add GUILD_INVITE_REMINDER

core/src/main/java/discord4j/core/event/ReactiveEventAdapter.java, core/src/main/java/discord4j/core/event/dispatch/DispatchHandlers.java, core/src/main/java/discord4j/core/event/domain/integration/IntegrationCreateEvent.java, core/src/main/java/discord4j/core/event/domain/integration/IntegrationDeleteEvent.java, core/src/main/java/discord4j/core/event/domain/integration/IntegrationUpdateEvent.java, core/src/main/java/discord4j/core/event/domain/integration/package-info.java, core/src/main/java/discord4j/core/object/Embed.java, core/src/main/java/discord4j/core/object/IntegrationAccount.java, core/src/main/java/discord4j/core/object/Invite.java, core/src/main/java/discord4j/core/object/audit/AuditLogEntry.java, core/src/main/java/discord4j/core/object/entity/ApplicationInfo.java, core/src/main/java/discord4j/core/object/entity/Attachment.java, core/src/main/java/discord4j/core/object/entity/Guild.java, core/src/main/java/discord4j/core/object/entity/Integration.java, core/src/main/java/discord4j/core/object/entity/IntegrationApplication.java, core/src/main/java/discord4j/core/object/entity/Webhook.java, core/src/main/java/discord4j/core/object/entity/channel/VoiceChannel.java, core/src/main/java/discord4j/core/spec/GuildEditSpec.java, core/src/main/java/discord4j/core/spec/InviteCreateSpec.java, core/src/main/java/discord4j/core/spec/MessageReferenceSpec.java, core/src/main/java/discord4j/core/spec/VoiceChannelEditSpec.java, gradle.properties, rest/src/main/java/discord4j/rest/service/GuildService.java
**Description:** Implements discord-json changes.
**Justification:** #894
Missing PRs:
- https://github.com/Discord4J/discord-json/pull/54
- https://github.com/Discord4J/discord-json/pull/57
- https://github.com/Discord4J/discord-json/pull/62
=> Implements discord-json changes

gradle.properties, rest/src/main/java/discord4j/rest/route/Routes.java, rest/src/main/java/discord4j/rest/service/ApplicationService.java
**Description:** Adds Slash Commands Permissions.
https://github.com/Discord4J/discord-json/pull/52
https://github.com/discord/discord-api-docs/pull/2737
=> Adds Slash Commands Permissions

rest/src/main/java/discord4j/rest/RestClientBuilder.java, rest/src/main/java/discord4j/rest/http/client/DiscordWebClient.java, rest/src/main/java/discord4j/rest/request/DefaultRouter.java, rest/src/main/java/discord4j/rest/request/RouterOptions.java, rest/src/test/java/discord4j/rest/RestTests.java, rest/src/test/java/discord4j/rest/http/WebClientTest.java
Allow providing a custom discord base url.
More customizability for the library users.
=> Customizable Discord base url

core/src/main/java/discord4j/core/object/entity/Guild.java, core/src/main/java/discord4j/core/object/entity/Sticker.java
**Description:** Adds `Guild#isNsfw`.
**Justification:** https://github.com/Discord4J/discord-json/pull/73
**Info:**
What are NSFW Guild? 
https://support.discord.com/hc/en-us/articles/1500005389362-NSFW-Server-Designation
=> Adds Guild#isNsfw

common/src/main/java/discord4j/common/store/legacy/LegacyStoreLayout.java
**Description:** Fix `IllegalArgumentException: Unhandled channel type 13`
https://sentry.io/share/issue/d0f9416be5b247ba9b1bc314cdf313a0/
**Justification:** https://discord.com/developers/docs/resources/channel#channel-object-channel-types
=> LegacyStoreLayout: Support Guild Stage Voice

core/src/main/java/discord4j/core/object/ApplicationTeamMember.java, core/src/main/java/discord4j/core/object/entity/ApplicationInfo.java, core/src/main/java/discord4j/core/object/entity/ApplicationTeam.java
**Description:** Add `ApplicationInfo#getTeam`
**Justification:** https://discord.com/developers/docs/resources/application#application-resource
=> Add ApplicationInfo#getTeam

core/src/main/java/discord4j/core/object/entity/User.java
**Description:** This pull request adds the Discord Certified Moderator badge flag to the User Flags
**Justification:** PR in discord-api-docs: https://github.com/discord/discord-api-docs/pull/2946
=> New Discord Certified Moderator Flag Add

core/src/main/java/discord4j/core/event/ReactiveEventAdapter.java, core/src/main/java/discord4j/core/event/dispatch/DispatchHandlers.java, core/src/main/java/discord4j/core/event/domain/interaction/ApplicationCommandInteractEvent.java, core/src/main/java/discord4j/core/event/domain/interaction/ButtonInteractEvent.java, core/src/main/java/discord4j/core/event/domain/interaction/InteractionCreateEvent.java, core/src/main/java/discord4j/core/object/command/ApplicationCommandInteraction.java, core/src/main/java/discord4j/core/object/command/Interaction.java, core/src/test/java/discord4j/core/ExampleApplicationCommandInteractEvent.java, core/src/test/java/discord4j/core/ExampleButtons.java
This PR follows #935 and adds inherited events for the available interaction types.
=> Add inherited interaction events

core/src/main/java/discord4j/core/object/entity/Guild.java, gradle.properties
**Description:** Add `Guild#getNsfwLevel()`
**Justification:** https://github.com/Discord4J/discord-json/pull/88
=> Add Guild#getNsfwLevel

core/src/main/java/discord4j/core/object/component/Button.java
- Introduces a new function `Button#disabled(boolean value)` which should allow for dynamic button states (for disabling/enabling) them.
**Justification:**  https://github.com/Discord4J/Discord4J/commit/e1040f32cd3c51d3d8938cbd98d352e48dea51b4#r52741236
=> Introduces Button#disabled(boolean value)

core/src/main/java/discord4j/core/object/entity/channel/BaseTopLevelGuildMessageChannel.java
Fixes the NullPointerException when attempting to create a Message
#972
=> Fix NPE occurring when creating a message via ImmutableSpec

common/src/main/java/discord4j/common/store/impl/EmptyPartialUser.java, common/src/main/java/discord4j/common/store/impl/EmptyUser.java, common/src/main/java/discord4j/common/store/impl/LocalStoreLayout.java, core/src/main/java/discord4j/core/object/entity/User.java
**Description:** Add methods User#getBannerUrl(ImageFormat) and User#getBannerAccentColor()
Closes #965 
Require https://github.com/Discord4J/discord-json/pull/103
=> Add support for user banner and bannerAccentColor

.github/README_TEMPLATE.md, README.md
Add "interactions" section to d4j version table since discord is pushing this major feature set.
And update the large bots section with more recent statistics since its been several months since its original inclusion.
=> Update bot stats and version table in README

core/src/main/java/discord4j/core/event/domain/interaction/MessageInteractionEvent.java, core/src/main/java/discord4j/core/event/domain/interaction/UserInteractionEvent.java, core/src/main/java/discord4j/core/object/command/ApplicationCommandInteractionResolved.java
**Description:** Adds `getResolved` methods to context menu interactions.
**Justification:** #1007
This depends on Discord4J/discord-json#107
=> Add resolve methods to context menu interactions

core/src/main/java/discord4j/core/object/audit/AuditLogEntry.java
**Description:** The method getChange use the wrong field to get the new value
**Justification:** N/A
=> Fix issue in AuditLogEntry::getChange

.github/README_TEMPLATE.md, README.md
**Description:** This PR change the code used for create a embed in README for new users.
**Justification:** The code used in README is for a deprecated method then in teory is better show the new form for make this.
=> [ci skip] Change use of Embeds in README

README.md
**Description:** This PR change the version of repository for imports
**Justification:** N/A
=> [ci skip] Update repository version

build.gradle, common/build.gradle, core/src/main/java/discord4j/core/object/audit/AuditLogChangeParser.java, core/src/main/java/discord4j/core/object/audit/ChangeKey.java, core/src/main/java/discord4j/core/object/entity/PartialMember.java, core/src/main/java/discord4j/core/object/entity/channel/BaseMessageChannel.java, core/src/main/java/discord4j/core/spec/GuildMemberEditSpecGenerator.java, rest/src/main/java/discord4j/rest/util/Permission.java
**Description:** This add support for the timeout system (called in docs "communication_disabled_until")
**Justification:** https://discord.com/developers/docs/resources/guild#modify-guild-member and https://github.com/discord/discord-api-docs/commit/b51c34f8f50ae8455f351f869ed22d025c1d2852 | https://github.com/discord/discord-api-docs/commit/c63a4d5a604b6c2dbb5e5b5c1e3c2a101e96df44
Depends of: https://github.com/Discord4J/discord-json/pull/113
=> Support for timeout (communication_disabled_until)

core/src/main/java/discord4j/core/event/dispatch/GuildDispatchHandlers.java, core/src/main/java/discord4j/core/event/domain/guild/MemberUpdateEvent.java
**Description:** Adds methods for `avatar`/`communicationDisabledUntil` fields
=> Add missing methods to GuildMemberUpdate

.github/README_TEMPLATE.md, README.md
- Update Declan's GitHub profile link from "decyg" to "d-g-n"
- README.md should contain up-to-date links to sponsors.
=> Update Declan's GitHub profile link

rest/src/main/java/discord4j/rest/service/ChannelService.java
**Description:** Change request type of startThreadWithoutMessage to new StartThreadWithoutMessageRequest
**Justification:** See Discord4J/discord-json#117
=> Change request type of startThreadWithoutMessage

core/src/main/java/discord4j/core/object/entity/channel/ThreadChannel.java, core/src/main/java/discord4j/core/spec/ThreadChannelEditSpecGenerator.java, core/src/test/java/discord4j/core/ExampleThread.java, rest/src/main/java/discord4j/rest/service/ChannelService.java
Editing a thread.
This code isn't tested
Discord4J/discord-json#120
=> Edit a thread

core/src/main/java/discord4j/core/object/command/ApplicationCommandInteraction.java, core/src/main/java/discord4j/core/object/command/ApplicationCommandInteractionOption.java, core/src/main/java/discord4j/core/object/command/ApplicationCommandInteractionOptionValue.java
**Justification:** Resolves #1091
=> Add asAttachment() method to option value

core/src/main/java/discord4j/core/event/domain/message/MessageBulkDeleteEvent.java
**Description:** Fixes https://github.com/Discord4J/Discord4J/issues/1088
=> Replace TextChannel with MessageChannel in MessageBulkDeleteEvent

common/src/main/java/discord4j/common/store/impl/EmptyPartialUser.java, common/src/main/java/discord4j/common/store/impl/EmptyUser.java, core/src/main/java/discord4j/core/object/entity/User.java, gradle.properties
**Description:** Currently based in a issue the flags of a user can be longer than currently expected.
**Justification:** Close https://github.com/Discord4J/Discord4J/issues/1086 this also depend in a PR https://github.com/Discord4J/discord-json/pull/126
=> Make User flags support long values

.github/README_TEMPLATE.md, README.md
**Description:** Fix the workflow badge to display correctly.
**Justification:** https://github.com/badges/shields/issues/8671
This also can be send to master but need change the branch argument to point.
=> [ci skip] Fix Workflow status badge

rest/src/main/java/discord4j/rest/service/ApplicationService.java
**Description:** This add a method for get the global/guild commands with the query for localizations.
**Justification:** Currently the only way to make this is making a copy paste of the service to add the query.
=> Add query with_localizations for ApplicationService

core/src/main/java/discord4j/core/object/entity/User.java
**Description:** This PR add the new flag for active developer also add the url for the docs to check descriptions.
**Justification:** https://github.com/discord/discord-api-docs/commit/26a4fe42d3b344c2ec67078731d6346bf0dc24e7
=> Add ACTIVE_DEVELOPER User Flag

core/src/test/java/discord4j/core/ExampleButtons.java
**Description:** examples: replace deprecated createMessage
**Justification:** avoid deprecated api usage
=> examples: replace deprecated createMessage

core/src/main/java/discord4j/core/object/entity/PartialMember.java
**Description:** Add a new Enum in Member related to Flags added by Guild
**Justification:** https://github.com/discord/discord-api-docs/commit/5a6c4e10858ae736b09d352b67387a096b4adcdb
**Needs:** https://github.com/Discord4J/discord-json/pull/135
=> Add Flags to Member

core/src/main/java/discord4j/core/object/audit/AuditLogEntry.java
**Description:** This close #1135 by adding docs about when this exception can happen and also handle the null parent for make all return the same type of exception.
=> Minor improvement for AuditLogEntry#getResponsibleUser

core/src/main/java/discord4j/core/object/entity/ApplicationInfo.java
Description: This add the support for the flags in interactions
Justification: https://discord.com/developers/docs/resources/application#application-object-application-flags
=> Implement Flags for Application

core/src/main/java/discord4j/core/object/entity/Message.java
https://github.com/discord/discord-api-docs/blob/main/docs/resources/Channel.md#message-flags
https://github.com/discord/discord-api-docs/blob/main/docs/resources/Channel.md#message-types
=> Update message flags and types

rest/src/main/java/discord4j/rest/util/Permission.java
**Description:** Add new permission related to the use of external sounds (nitro feature)
**Justification:** https://github.com/discord/discord-api-docs/commit/f45e97068f26cbc6444c7c2bdcd1410c2c862bbc
=> Add Permission.USE_EXTERNAL_SOUNDS

core/src/main/java/discord4j/core/object/entity/Guild.java
https://github.com/discord/discord-api-docs/blob/main/docs/resources/Guild.md#system-channel-flags
=> Update system channel flags

core/src/main/java/discord4j/core/object/entity/Role.java
**Description:** Implement the Flag to Roles
**Justification:** https://github.com/Discord4J/discord-json/commit/4ad34d8c1b3e998c57c632f82bfb79e23cec0e94
=> Implement Flags in Role

common/src/main/java/discord4j/common/store/impl/LocalStoreLayout.java, core/src/main/java/discord4j/core/object/reaction/Reaction.java, core/src/main/java/discord4j/core/object/reaction/ReactionCountDetails.java, gradle.properties, rest/src/main/java/discord4j/rest/util/Color.java, rest/src/test/java/discord4j/rest/util/ColorTest.java
**Description:** This PR handle two things.
- Add support for Create a Color using hex color string (including a few tests)
- Implement SuperReactions and CountDetails in reactions, the methods are called "burst" based in discord docs, not sure if this is a good name or is better in this side of the API call Super...
**Justification:** https://github.com/Discord4J/discord-json/pull/155
=> Implement SuperReactions (Burst)

core/src/main/java/discord4j/core/object/component/SelectMenu.java, core/src/test/java/discord4j/core/ExampleSelectMenu.java
**Description:** Adds support for default Values for Auto-populated Select Menus (https://discord.com/developers/docs/change-log#default-value-in-autopopulated-select-menus)
Requires https://github.com/Discord4J/discord-json/pull/157
=> feat: added support for default values for SelectMenu

core/src/main/java/discord4j/core/object/audit/OptionKey.java, core/src/main/java/discord4j/core/util/AuditLogUtil.java, gradle.properties
**Description:** This PR handle missing OptionKey for AutoMod and add the recently added option for Integration Type (https://github.com/Discord4J/discord-json/pull/154)
=> Add OptionKey for AutoMod and Integrations

core/src/test/java/discord4j/core/ExampleModal.java
**Description:** Update the ExampleModal file
**Justification:** The example previously provided was using SelectMenu in modals, which are not allowed. For now only TextInput are allowed in modals.
=> fix: correct the ExampleModal file

core/src/main/java/discord4j/core/object/entity/ApplicationInfo.java, core/src/main/java/discord4j/core/spec/ApplicationEditSpecGenerator.java, gradle.properties, rest/src/main/java/discord4j/rest/route/Routes.java, rest/src/main/java/discord4j/rest/service/ApplicationService.java
**Description:** Adds support for editing the current application info
**Justification:** https://discord.com/developers/docs/resources/application#edit-current-application
**Depends on:** https://github.com/Discord4J/discord-json/pull/158
=> Edit Current Application

core/src/main/java/discord4j/core/object/command/ApplicationCommand.java
**Description:** added missing nsfw field for application command
Requires https://github.com/Discord4J/discord-json/pull/163
=> fix: added missing nsfw field for application command

core/src/main/java/discord4j/core/object/automod/AutoModRule.java, core/src/main/java/discord4j/core/object/automod/AutoModRuleAction.java
**Description:** Include Changes in AutoMod related to Member Profiles
**Justification:** https://github.com/discord/discord-api-docs/commit/60a711d841394492fc3a36c8d14c19fea00c2ccd
=> Include AutoMod for Member Profile actions

rest/src/main/java/discord4j/rest/util/Permission.java
**Description:** Add recently discord permission for external apps
**Justification:** https://github.com/discord/discord-api-docs/commit/f09244029c6ff3c99f75b9443c6af95d8767524f
=> Add Permission#USE_EXTERNAL_APPS

core/src/main/java/discord4j/core/object/command/ApplicationCommand.java, core/src/main/java/discord4j/core/object/command/ApplicationCommandContexts.java, core/src/main/java/discord4j/core/object/command/ApplicationIntegrationType.java, core/src/main/java/discord4j/core/object/command/Interaction.java
**Description:** Add support for user-installed applications
https://github.com/discord/discord-api-docs/pull/6723
Requires https://github.com/Discord4J/discord-json/pull/162
=> feat: added support for user-installed applications

rest/src/main/java/discord4j/rest/entity/RestGuild.java, rest/src/main/java/discord4j/rest/entity/RestRole.java, rest/src/main/java/discord4j/rest/service/GuildService.java
Closes #1191 
Requires https://github.com/Discord4J/discord-json/pull/180
=> fix: split PositionModifyRequest to ChannelPositionModifyRequest and RolePositionModifyRequest

core/src/main/java/discord4j/core/object/ApplicationInstallParams.java, core/src/main/java/discord4j/core/object/ApplicationIntegrationTypeConfiguration.java, core/src/main/java/discord4j/core/object/ApplicationTeamMember.java, core/src/main/java/discord4j/core/object/entity/ApplicationInfo.java, core/src/test/java/discord4j/core/ExampleVoice.java, core/src/test/java/discord4j/core/support/VoiceSupport.java
Closes #1190 
Requires https://github.com/Discord4J/discord-json/pull/179
Depends on https://github.com/Discord4J/Discord4J/pull/1183
=> feat: add missing fields in ApplicationInfo (#1190)

build.gradle
**Description:** Just a minor bump of reactor, also update the javadocs related to reactor.
=> Bump Reactor to 2023.0.8

gradle.properties
**Justification:** Required for #1248
=> feat: bump discord-json to 1.6.21

gradle.properties
**Justification:** Required for #1248
=> feat: bump discord-json version

core/src/main/java/discord4j/core/object/command/ResolvedChannel.java, core/src/main/java/discord4j/core/object/command/ResolvedMember.java
**Justification:** #1176 did not get merged into 3.2.x due to thread-related data. This PR is a clone, without theses.
=> fix: port #1176 to 3.2.x

core/src/main/java/discord4j/core/object/entity/ApplicationInfo.java
**Description:** Change required by https://github.com/Discord4J/discord-json/pull/185 to fix https://github.com/Discord4J/Discord4J/issues/1243
=> fix: fix application info optional fields

core/src/main/java/discord4j/core/event/domain/interaction/DeferrableInteractionEvent.java, core/src/main/java/discord4j/core/object/component/Button.java, core/src/main/java/discord4j/core/object/entity/ApplicationInfo.java, core/src/main/java/discord4j/core/object/monetization/SKU.java, rest/src/main/java/discord4j/rest/util/InteractionResponseType.java
Closes #1239 
Depends on #1184 
Requires https://github.com/Discord4J/discord-json/pull/182
https://discord.com/developers/docs/change-log#premium-apps-new-premium-button-style-deep-linking-url-schemes
=> feat: add support for the new premium button style

core/src/main/java/discord4j/core/object/entity/ApplicationEmoji.java, core/src/main/java/discord4j/core/object/entity/ApplicationInfo.java, core/src/main/java/discord4j/core/object/entity/Emoji.java, core/src/main/java/discord4j/core/object/entity/Guild.java, core/src/main/java/discord4j/core/object/entity/GuildEmoji.java, core/src/main/java/discord4j/core/object/reaction/ReactionEmoji.java, core/src/main/java/discord4j/core/spec/ApplicationEmojiCreateSpecGenerator.java, core/src/main/java/discord4j/core/spec/ApplicationEmojiEditSpecGenerator.java, rest/src/main/java/discord4j/rest/route/Routes.java, rest/src/main/java/discord4j/rest/service/EmojiService.java
**Description:** This PR add Support for Application Emoji (List, Get, Create, Update, Delete) also make a improvement for the GuildEmoji based in how Guild Emojis and Application Emoji share the same data (ignoring roles)
=> Add support for Application Emoji

gradle.properties
**Description:** Update the version of Stores from https://github.com/Discord4J/Stores
**Justification:** Match the last dependencies updates here and minor improvements
=> Update D4J Stores dependency to 3.2.3

core/src/main/java/discord4j/core/GatewayDiscordClient.java, core/src/main/java/discord4j/core/object/entity/PartialMember.java, core/src/main/java/discord4j/core/retriever/EntityRetriever.java, core/src/main/java/discord4j/core/retriever/FallbackEntityRetriever.java, core/src/main/java/discord4j/core/retriever/RestEntityRetriever.java, core/src/main/java/discord4j/core/retriever/StoreEntityRetriever.java, rest/src/main/java/discord4j/rest/route/Routes.java, rest/src/main/java/discord4j/rest/service/GuildService.java
**Description:** This PR add support for the new endpoints for get the voice state for user in guild using REST
**Justification:** https://discord.com/developers/docs/change-log#voice-state-endpoints
=> Support for get Voice State using REST

rest/src/main/java/discord4j/rest/route/Routes.java, rest/src/main/java/discord4j/rest/service/StickerService.java
**Description:** Basic support for request the Sticker Pack using ID
**Justification:** https://github.com/discord/discord-api-docs/commit/1a9e949f1be126a1b2e6797de4c0713dc868d438
=> Support for get StickerPack by ID

core/src/main/java/discord4j/core/object/entity/PartialMember.java
https://github.com/discord/discord-api-docs/pull/7113
=> Add PartialMember.Flag for id 4,5,6,7,9

core/src/main/java/discord4j/core/object/entity/PartialMember.java
**Description:** This PR just add new member flags and include the editable field based in docs
**Justification:** https://github.com/discord/discord-api-docs/commit/493d5098630dd15b324c45395f98eb1edfd61614
=> Feat: add new Guild Member Flags and expose editable field

core/src/main/java/discord4j/core/object/component/Container.java, core/src/main/java/discord4j/core/object/component/Section.java, gradle.properties
**Description:** Fixs a issue where accent colour for Container Component can be null in response of data
=> fix: nullable accent for Container Component

core/src/main/java/discord4j/core/object/component/Separator.java
**Description:** Fixes an issue with the separator sizes, and rename a few parameters to be more user friendly
=> fix: fix an issue with separator spacing size, and add more clarity

gradle.properties
**Description:** Dependency update
**Justification:** #1289 #1288
=> chore: update discord-json dependency

core/src/main/java/discord4j/core/object/component/Container.java, core/src/main/java/discord4j/core/object/component/Section.java, core/src/test/java/discord4j/core/ExampleComponentsV2.java
**Description:** removes the `MessageComponent` requirement in method parameter as it is not possible to create a `List<MessageComponent & ICanBeUsedInContainerComponent>` in Java :(
=> fix: bad bounded type parameters in Container and Section

common/src/main/java/discord4j/common/store/legacy/LegacyStoreLayout.java
Add missing Guild Forum Enum Value for Legacy Store Layout to be able to handle Forum Channel Updates in Store Implementations
Closes https://github.com/Discord4J/Discord4J/issues/1308
=> fix: add missing Guild Forum Type to Legacy Store Layout

core/src/main/java/discord4j/core/object/entity/Message.java, core/src/main/java/discord4j/core/object/entity/PinnedMessageReference.java, core/src/main/java/discord4j/core/object/entity/channel/MessageChannel.java, core/src/main/java/discord4j/core/spec/PinnedMessagesQuerySpecGenerator.java, core/src/test/java/discord4j/core/ExamplePinnedMessages.java, rest/src/main/java/discord4j/rest/entity/RestChannel.java, rest/src/main/java/discord4j/rest/route/Routes.java, rest/src/main/java/discord4j/rest/service/ChannelService.java, rest/src/main/java/discord4j/rest/util/Permission.java
**Description:** Handle the last changes in pinned messages
- https://discord.com/developers/docs/change-log#paginated-pin-endpoints
- https://discord.com/developers/docs/change-log#pin-permission-split
**Depends on:** https://github.com/Discord4J/discord-json/pull/209
=> feat: Support changes in Pinned Messages
