dependency-reduced-pom.xml, pom.xml
Let's give IDEs some love. This adds the ``Discord4J-{version}-javadoc.jar`` and ``Discord4J-{version}-sources.jar`` artifacts on deploy.
=> Adding javadoc and sources as deployable artifacts

src/main/java/sx/blah/discord/util/MessageList.java
- Fixes an issue where reaching the beginning of message history would return `true` even if it didn't load any message
- Allows a user to handle potential 429 errors occurred when querying channel messages
- Increases the number of messages queried from 50 to the current API maximum (100)
=> MessageList improvements and fixes

src/main/java/sx/blah/discord/api/internal/DiscordWS.java, src/main/java/sx/blah/discord/handle/impl/events/UserVoiceChannelJoinEvent.java, src/main/java/sx/blah/discord/handle/impl/events/UserVoiceChannelLeaveEvent.java, src/main/java/sx/blah/discord/handle/impl/events/UserVoiceChannelMoveEvent.java
I haven't tested it yet, but it's a small change and I can't see why it shouldn't work.
**Issues Fixed:** none
* Added a IUser field and getter to `UserVoiceChannel(Join/Leave/Move)Event`
Before, you couldn't check which user joined, left or moved to another channel.
=> Added user to UserVoiceChannel(Join/Leave/Move)Event

src/main/java/sx/blah/discord/modules/ModuleLoader.java
**Issues Fixed:** Fixes a minor bug in ModuleLoader that was reading all MANIFEST 'module-requires' keys as false.
=> Fixes ModuleLoader not being able to read 'module-requires'

src/main/java/sx/blah/discord/handle/impl/obj/VoiceChannel.java, src/main/java/sx/blah/discord/handle/obj/IVoiceChannel.java, src/test/java/sx/blah/discord/VoiceBot.java
**Issues Fixed:** Someone( can't remember your name D: ) brought up how `IVoiceChannel#join` doesn't properly check if you don't have permissions to join the voice channel, so now it does before doing anything.
* join() now checks for the VOICE_CONNECT permission before trying to do anything.
* As a result it throws MIssingPermissionException now
* Updated VoiceBot to reflect that change
=> Made IVoiceChannel#join check for valid permissions.

src/main/java/sx/blah/discord/handle/impl/obj/Guild.java
**Issues Fixed:** [The issues fixed by this pull request]
N/A
Instead of creating a new ArrayList and streaming that, we just stream a copy of the original ArrayList's backing array. Shouldn't actually impact functionality, as the previously used ArrayList constructor already calls Collection#toArray() anyways.
=> More efficient Guild#getUserById()

src/main/java/sx/blah/discord/api/internal/DiscordWS.java
MessagePinEvent and MessageUnpinEvent were not firing due to the wrong Message object being checked for past-pinning.
=> Fix message pin/unpin events not firing

src/main/java/sx/blah/discord/api/internal/DiscordWS.java, src/main/java/sx/blah/discord/api/internal/Requests.java
* Added a separate error message for DiscordException when the text "cloudflare-nginx" is detected in the message.
* This also removes the "probably caused by cloudflare" message in the original 502 exception. This was added because some developers (like myself) detect for a CloudFlare 502 and use that to attempt to retry sending the message at a later point.
=> Differentiate CloudFlare 502 vs Discord 502 ("probably caused by cloudflare") 

src/main/java/sx/blah/discord/api/internal/DiscordUtils.java, src/main/java/sx/blah/discord/handle/impl/obj/Channel.java, src/main/java/sx/blah/discord/handle/impl/obj/VoiceChannel.java
**Issues Fixed:** #39 (Change 2 >.>)
* `IChannel.getModifedPermissions(IUser)` is slightly reworked to add and/or remove permissions based on any role override that a user is a part of.
* `IVoiceChannel#join` no longer adds channels to the cache because `DiscordWS#voiceStateUpdate` already does that and makes sure the user has actually joined the channel before doing so.
* Permission overrides are properly cached now. Previously if a role/user was already in the override cache, the new overrides from `ChannelResponse` would be ignored and the cache would remain unchanged.
The reason for the 1st change is because say the Everyone role had normal permissions but a user has another role which excludes `SEND_MESSAGE` in a certain channel, running `DiscordUtils.checkPermissions(client, …
=> Fixes override caching, connectedVoiceChannels caching and permission checks

src/main/java/sx/blah/discord/handle/impl/obj/User.java
**Issues Fixed:** Bot trying to move user to a channel when it doesn't have the perms for it instead of throwing MissingPermissionsException
* A new permission check in moveToVoiceChannel to see if the bot can join the voice channel before moving itself or others.
=> Added permission check to moveToVoiceChannel

src/main/java/sx/blah/discord/handle/impl/obj/VoiceChannel.java, src/main/java/sx/blah/discord/json/requests/ChannelEditRequest.java
* Editing a text channel would throw DiscordException because of the default bitrate being 0 instead of 8000.
* Editing a voice channel's name or position would reset it's bitrate and user limit due to using Channel's edit instead of VoiceChannel's
* VoiceChannel now overrides changeName and changePosition from Channel to use VoiceChannel#edit
* ChannelEditRequest now has a default value of 8000 (the minimum) for bitrate to avoid errors editing text channels
...
=> Fixes channel editing

src/main/java/sx/blah/discord/api/internal/Requests.java
* Wouldn't pick up CF errors that didn't have "cloudflare-nginx" for 502s, fixed.
=> CloudFlare 502 detection not working for non-nginx errors

src/main/java/sx/blah/discord/api/internal/DiscordUtils.java, src/main/java/sx/blah/discord/handle/impl/obj/Message.java, src/main/java/sx/blah/discord/handle/obj/IMessage.java
* Adds a method to IMessage allowing you to get the channel mentions in a message, since for whatever reason, Discord does not send these out like it sends out role and user mentions.
Also cleans up some things in Message, shout-out to IntelliJ
=> Adds getChannelMentions to IMessage

src/main/java/sx/blah/discord/api/internal/DiscordUtils.java
**Issues Fixed:** #102 
* Instead of using UTC+0, `DiscordUtils.getSnowflakeTimeFromID` now uses the system's timezone.
=> getSnowflakeTimeFromID now uses the system's timezone instead of UTC

src/main/java/sx/blah/discord/util/MessageTokenizer.java
The MessageTokenizer allows you to take an IMessage (or IDiscordClient + String) and do `hasNextX` and `nextX` methods on it. The supported tokens are characters, words, lines, mentions (role, user, channel), and a regex expression (Pattern class). For example, if you wanted to get the first mention after a word, you would do:
```java
MessageTokenizer tokenizer = new MessageTokenizer(message);
if (tokenizer.hasNextWord()) {
// get the word, and advance the tokenizer past it
String firstWord = tokenizer.nextWord();
if (tokenizer.hasNextMention()) {
// get the mention, (and advance the tokenizer past it)
MentionToken token = tokenizer.nextMention();
// get the object which will be a type of the mention type (IUser, IRole, IChannel)
IDiscordObject obj = token.getMentionObject();
}
}
```
You …
=> Add MessageTokenizer utility

src/main/java/sx/blah/discord/handle/impl/obj/Message.java
**Issues Fixed:** #101 [would crash when there is an embed link](https://u.pomf.is/idsryj.png)
* Everything in setChannelMentions is now wrapped with a null check
Content is null when something is embedded, I forgot that was a thing
kotlin spoils me™
=> Null check on content when getting channel mentions

src/main/java/sx/blah/discord/api/events/EventDispatcher.java, src/main/java/sx/blah/discord/api/internal/DiscordWS.java
**Issues Fixed:** [The issues fixed by this pull request]
* Preventing the session from closing after a successful reconnect, as well as during reconnect, which allows the bot to reconnect successfully. This was caused because after a successful reconnect there was nothing preventing it from continuing to disconnect, adding the if statement on line 221 prevents that from happening
* Allows the DiscordDisconnectedEvent to fire when disconnected (Found by theIglooo)
* Prevents onClose from calling disconnect when isConnected is set to false preventing a reconnect attempt on logout
* Preventing the session from closing after a successful reconnect also allows for reconnect to work when the disconnect is due to internet outage. Ex. the bot can reconnect after unplugging Ethernet cable and …
=> Reconnect fix, logout fix, and allow DiscordDisconnectedEvent to fire

src/main/java/sx/blah/discord/api/internal/DiscordUtils.java, src/main/java/sx/blah/discord/handle/impl/obj/User.java
* Give DiscordUtils all the `checkPermissions` methods, but for IUser
* This means all the IDiscordClient variants of the methods are synthetic, and pass onto the IUser equivalents using `IDiscordClient#getOurUser`
* Fix the permissions check in `IUser#moveToVoiceChannel`
* This correctly checks the requirements needed to move a user (that isn't the client's user):
* Move Members actually bypasses the role hierarchy
* Both the client and the moved user must be able to connect to the new voice channel
=> Fix moveToVoiceChannel not having proper permissions checks

src/main/java/sx/blah/discord/handle/impl/obj/Guild.java, src/main/java/sx/blah/discord/handle/obj/IGuild.java
* Allows you to specify whether or not you'd like to ignore the casing
of the role's name. Defaults to `false` if not specified.
=> Add 'ignoreCase' parameter to ByName methods in IGuild

.gitignore, src/main/java/sx/blah/discord/api/internal/Requests.java
**Issues Fixed:** A CloudFlare caused 502 would usually cancel and skip that request, now it is more robust by re trying the request.
* When a CloudFlare interruption occurs, instead of throwing an exception, we re make the same exact request
=> Make CloudFlare blocked requests be re-made

src/main/java/sx/blah/discord/api/IDiscordClient.java, src/main/java/sx/blah/discord/api/internal/DiscordClientImpl.java
* Add `getResponseTime` with no parameters (defaults to shard 0)
* Add `getAverageResponseTime`
* Also fixed a tiny spelling error in a doc
=> Add default getResponseTime, add getAverageResponseTime

src/main/java/sx/blah/discord/api/internal/DiscordClientImpl.java
* Status and presence changes were only being sent to shard 0
* The fix is that it's now sent to all shards
* Ideally, I'd like to be able to control each presence/status for each shard individually but it'd be a bigger overhaul
=> Propagate status and presence changes throughout all shards

src/main/java/sx/blah/discord/api/IDiscordClient.java, src/main/java/sx/blah/discord/api/internal/DiscordClientImpl.java, src/main/java/sx/blah/discord/api/internal/DiscordUtils.java, src/main/java/sx/blah/discord/api/internal/DiscordWS.java, src/main/java/sx/blah/discord/handle/impl/events/PresenceUpdateEvent.java, src/main/java/sx/blah/discord/handle/impl/events/StatusChangeEvent.java, src/main/java/sx/blah/discord/handle/impl/obj/User.java, src/main/java/sx/blah/discord/handle/obj/IUser.java, src/main/java/sx/blah/discord/handle/obj/Presences.java
* As noted in #124, I wanted the ability to __set presences and statuses per shard__
* That is the change in this PR
* Users that aren't the client only have one presence and status, though (since we can't see their shards, obviously)
* Added `changePresence` and `changeStatus` with a shard number
* Not passing a shard number defaults to all shards to allow backwards compatibility
* Added index parameters for `getStatus` and `getPresence`
* Only works on index 0 for non-clients, but the parameter-less version of the getters defaults to 0
* Passing a shard number outside of the range (less than zero or more than shard count) will result in an IllegalArgumentException being thrown for the `getX` and `changeX` methods
=> Add status and presence changing per shard

src/main/java/sx/blah/discord/api/internal/DiscordClientImpl.java
* Removed setting isReady to false if the websocket isn't ready
=> Fixed ReadyEvent being called on reconnect

src/main/java/sx/blah/discord/api/internal/DiscordUtils.java, src/main/java/sx/blah/discord/api/internal/DiscordVoiceWS.java, src/main/java/sx/blah/discord/api/internal/DiscordWS.java, src/main/java/sx/blah/discord/api/internal/DispatchHandler.java, src/main/java/sx/blah/discord/api/internal/GatewayOps.java, src/main/java/sx/blah/discord/api/internal/VoiceOps.java, src/main/java/sx/blah/discord/handle/impl/obj/Guild.java, src/main/java/sx/blah/discord/handle/obj/Presences.java, src/main/java/sx/blah/discord/handle/obj/VerificationLevel.java
* [Proof of testing](https://u.pomf.is/jrqlia.png)
**Issues Fixed:** Opcodes, presences and verification levels that were not supported would cause an error.
* A get method in the opcode enums to safely get an opcode or return UNKNOWN if it can't.
* Same as above, for the Presences and VerificationLevel enums.
=> Handle unknown enum constants cleanly

src/main/java/sx/blah/discord/api/internal/DiscordVoiceWS.java, src/main/java/sx/blah/discord/api/internal/DiscordWS.java
* [Proof of testing](http://imgur.com/a/3HjXR)
**Issues Fixed:** NPE in client logout which happens because getSession() returns null after websockets are closed.
* Add a null check in send method for DiscordWS
=> Fix a NPE in DiscordWS

src/main/java/sx/blah/discord/util/audio/AudioPlayer.java
* [Proof of testing](http://imgur.com/gallery/jRUzI)
**Issues Fixed:** None available about this bug.
* `Track(AudioInputStream)` and `Track(AudioInputStreamProvider)` constructors no longer declare `IOException` as being throwable (since, actually, it's never thrown)
* `AudioPlayer::queue(IAudioProvider)` now calls the correct `Track` constructor for `AudioInputStreamProvider` instances passed as parameter
=> AudioPlayer::queue now calls the correct Track constructor for AudioInputStreamProvider instances

src/main/java/sx/blah/discord/api/internal/DispatchHandler.java, src/main/java/sx/blah/discord/handle/impl/obj/Channel.java, src/main/java/sx/blah/discord/handle/impl/obj/Guild.java, src/main/java/sx/blah/discord/handle/impl/obj/Message.java, src/main/java/sx/blah/discord/handle/impl/obj/PrivateChannel.java, src/main/java/sx/blah/discord/handle/impl/obj/Role.java, src/main/java/sx/blah/discord/handle/impl/obj/VoiceChannel.java, src/main/java/sx/blah/discord/handle/obj/IChannel.java, src/main/java/sx/blah/discord/handle/obj/IGuild.java, src/main/java/sx/blah/discord/handle/obj/IMessage.java, src/main/java/sx/blah/discord/handle/obj/IRole.java
* [Proof of testing](http://i.imgur.com/9wl3Ilb.png)
**Issues Fixed:** Before these changes were made, trying to edit a deleted message would result in a null pointer exception. What I've done is added isDeleted() boolean and a check to the edit() function. 
* Add isDeleted()
* Make a check which throws a DiscordException when trying to edit a deleted message
=> Add isDeleted() to IMessage (re made after failing to use git)

src/main/java/sx/blah/discord/api/internal/json/objects/OverwriteObject.java, src/main/java/sx/blah/discord/handle/impl/obj/Channel.java
* [Test code](https://u.pomf.is/xfvbei.png)
* [Role outcome](https://u.pomf.is/bchxmg.png)
* [User outcome](https://u.pomf.is/xpyoqb.png)
**Issues Fixed:** ![Report in bug-reports channel](https://u.pomf.is/ylbhwu.png)
* Fills the constructor for OverwriteObject so it actually assigns values.
* Use GSON_NO_NULLS and pass id as null because it doesn't take an id param when you're editing the permissions, it's already in the url.
* Flipped allow and deny params when putting them in the constructor so what you deny is actually being denied instead of allowed. _whoops_
=> Fixes role and user permission overriding

src/main/java/sx/blah/discord/api/internal/DispatchHandler.java
This pull request should fix #166 where a ConcurrentModificationException is thrown while dispatching a GuildCreateEvent. Since I have made this change locally, I have not encountered this error at all on my main bot with over 1400 servers, and I have tested it on a bot with around 10 servers to make sure my change did not affect smaller bots.
Changes:
* Added a synchronized block while iterating over an ArrayList of guild objects
=> Fix for #166 ConcurrentModificationException while dispatching GuildCreateEvent

src/main/java/sx/blah/discord/api/internal/DiscordWS.java
* [Proof of testing](https://gist.github.com/theIglooo/ecedac8d8fb25e7dfca6613059a74bcf)
**Issues Fixed:** Reported in the bug-reports channel, Discord4J would attempt to reconnect on logouts because it had the wrong state set when logging out.
* Changes the state from IDLE to DISCONNECTING
* Moves the state change above the other code in DiscordWS#shutdown
=> Fix reconnecting on logout

src/main/java/sx/blah/discord/api/internal/DiscordWS.java
Every time I close an application via CTRL-C or ![exit](https://dl.dropboxusercontent.com/s/32xxrfleerk3cof/idea_2017-01-25_00-27-00.png) "Exit" button under IntelliJ run panel, the last log lines I see before the JVM shutdowns, are attempts from Discord4J to reconnect the bot, most of the time succeeding, only to just be killed shortly afterwards.
The source is [Jetty issuing a 1001 code + "Shutdown" reason](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/WebSocketSession.java#L169) whenever this happens, which is not caught by the WS who interprets this as grounds for a normal reconnect. This PR adds a minor check that allows this type of shutdowns to be completed properly.
I hope it doesn't …
=> Don't reconnect on graceful jetty shutdowns

src/main/java/sx/blah/discord/api/internal/DiscordWS.java
* [Proof of testing](https://gist.github.com/quanticc/f52174d007ae464c1d57a7617c4e4b4c)
- Reconnect breaking because I fail at logic
* Properly catch the case of code 1001 + reason Shutdown and all other combos should perform the reconnect.
=> Fix for not reconnecting on jetty shutdown (part II)

src/main/java/sx/blah/discord/api/internal/DiscordWS.java
While still fulfilling #207's original idea. Partially reverts de7db30 that *might* break reconnects.
Jetty WS manages the provided HttpClient with its own lifecycle system `addBean`, `unmanage`, etc. therefore subject to release upon the ``wsClient.close()`` call. This PR also moves the call towards the end of the connect() method.
Trace of the 1001 + null happenings on all commits on dev between #205 and this PR:
https://gist.github.com/quanticc/70ece0c96cf6db7741b68543cd346cb2
NPE log only visible when using ``Discord4J.enableJettyLogging()`` and proper jetty logger level. Adding a null check to `DiscordWS#onWebSocketClose` fixes it.
* Revert a change in #207 - Purpose of that PR still holds
* Patch a NPE with #205 to handle the 1001 code + null reason
=> Fix reconnects

src/main/java/sx/blah/discord/handle/impl/obj/PresenceImpl.java
```
2017-02-25 14:29:41.483 DEBUG 10912 --- [nt@474017583-50] sx.blah.discord.Discord4J                : User "quantic" changed presence to DND
2017-02-25 14:29:49.058 DEBUG 10912 --- [nt@474017583-59] sx.blah.discord.Discord4J                : User "quantic" changed presence to ONLINE
2017-02-25 14:30:02.205 DEBUG 10912 --- [nt@474017583-63] sx.blah.discord.Discord4J                : User "quantic" changed presence to ONLINE - playing Guild Wars 2
2017-02-25 14:30:27.126 DEBUG 10912 --- [nt@474017583-61] sx.blah.discord.Discord4J                : User "quantic" changed presence to ONLINE
2017-02-25 14:51:06.514 DEBUG 10912 --- [nt@474017583-85] sx.blah.discord.Discord4J                : User "quantic" changed presence to STREAMING - playing  with streaming URL …
```
=> Display presence details only when they are present

src/main/java/sx/blah/discord/api/internal/DiscordUtils.java, src/main/java/sx/blah/discord/api/internal/DispatchHandler.java, src/main/java/sx/blah/discord/api/internal/json/objects/MessageObject.java
* [Proof of testing - Client](http://imgur.com/a/ICQZT)
* [Proof of testing - Bot trace](https://gist.github.com/quanticc/f5f42c97501bcb136035cf9d7febb2b1)
* Message update events with a partial message payload would result in incorrectly sent unpin events, or deletion of some of the cached fields. Reported by UnderMybrella#4076
* Use Boolean instead of boolean for the pinned field in MessageObject, so that it could be null instead of false when updating messages from an incomplete payload.
* Add a getUpdatedMessageFromJSON to DiscordUtils and use it to handle message update events.
* Wrap json.pinned with Boolean.TRUE.equals to ensure we never pass null to those fields, which would cause an NPE.
=> Handle message update events with partial contents

src/main/java/sx/blah/discord/api/internal/DiscordClientImpl.java, src/main/java/sx/blah/discord/api/internal/OpusPacket.java, src/main/java/sx/blah/discord/api/internal/UDPVoiceSocket.java, src/main/java/sx/blah/discord/handle/impl/obj/VoiceChannel.java
* [Audio's a bit difficult, but here's 5 seconds of audio data](https://gist.github.com/UnderMybrella/a7a8a45fe8f0545cd7ef860f513162db)
* Audio decryption
* NullPointerExceptions in IVoiceChannel#getConnectedUsers (And therefore IVoiceChannel#getUsersHere), and NPEs while iterating over IDiscordClient#getConnectedVoiceChannels
* Changed OpusPacket to use the DatagramPacket's length when constructing with a packet, rather than the packet data's length
* Added OpusPacket#getAudio, which returns a clone of the audio data in the packet
* Removed debug code from UDPVoiceSocket's receiveRunnable, replacing with the (existing) code to initialise an OpusPacket from a DatagramPacket
* Changed the receiveAudio call in UDPVoiceSocket's receiveRunnable, to only supply the audio …
=> Fixed audio decryption

src/main/java/sx/blah/discord/api/internal/DiscordUtils.java, src/main/java/sx/blah/discord/handle/impl/obj/Channel.java, src/main/java/sx/blah/discord/handle/impl/obj/Guild.java, src/main/java/sx/blah/discord/handle/impl/obj/User.java
`System.out.println(DiscordUtils.MAPPER_NO_NULLS.writeValueAsString(new MemberEditRequest("Test Nick Please Ignore", true)));`
`Before {"roles":null,"nick":"Test Nick Please Ignore","mute":null,"deaf":null,"channel_id":null}`
`After {"nick":"Test Nick Please Ignore"}`
Fixed DiscordUtils.MAPPER_NO_NULLS not ignoring nulls
Fixed methods not using DiscordUtils.MAPPER_NO_NULLS
=> Fixed user/guild/channel data getting reset

src/main/java/sx/blah/discord/api/ClientBuilder.java
* Added a default, no-params `withRecommendedShardCount()` method for `ClientBuilder` which calls `withRecommendedShardCount(true)` to use Discord's recommended shard count.
=> Add a default, no-params ClientBuilder#withRecommendedShardCount method

src/main/java/sx/blah/discord/handle/impl/obj/Channel.java
Check didn't exist, so when we receive an event for a channel we couldn't see we would request from it.
```
2017-03-19 20:59:16 [HttpClient@963046409-281] TRACE sx.blah.discord.Discord4J - Received: {"t":"MESSAGE_REACTION_ADD","s":3070,"op":0,"d":{"user_id":"83632458699923456","message_id":"293186650501021696","emoji":{"name":"ðŸ¤žðŸ¼","id":null},"channel_id":"245284059578630145"}}
2017-03-19 20:59:16 [HttpClient@963046409-281] ERROR sx.blah.discord.Discord4J - Received 403 forbidden error for url https://discordapp.com/api/channels/245284059578630145/messages/293186650501021696. If you believe this is a Discord4J error, report this!
```
Check added, won't request from channels we can't see.
```
2017-03-21 19:24:36 [HttpClient@101286873-17] TRACE sx.blah.discord.Discord4J - Received: …
```
=> Check for permissions before get messages request

src/main/java/sx/blah/discord/api/internal/DiscordUtils.java
* NullPointerException whenever a webhook message is sent, due to no user having the ID for the author object (which is the webhook ID)
* Use the code committed in 296f311 for webhook retrieval in message retrieval - attempt to get the user from the guild's user list, but fallback on the JSON provided if no user can be found.
=> Fix NPE for webhook messages

src/main/java/sx/blah/discord/handle/impl/obj/User.java
* [Proof of testing](http://image.prntscr.com/image/75a5d3a7f2d248c585fd7f4d192ef36e.png)
* [I blame brella if this somehow doesn't compile](http://image.prntscr.com/image/6aa2db6ad0cc4001bc3b4a2935d61bff.png)
**Issues Fixed:** If you do `getPermissionsForGuild` on the owner, it grabs the Permissions from their roles, while this works as intended it should return all permissions as the Guild owner can do it all.
* Return an EnumSet of all Permissions when calling the Guild owner
...
=> Fix permissions not returning properly for guild owner

src/main/java/sx/blah/discord/api/internal/DispatchHandler.java
* Set a breakpoint to set event.guild_id to null before the check, and no error was logged. Not exactly thorough, but it worked
* When a presence update event was dispatched with a null or missing guild_id, `Long.parseUnsignedLong` would throw a `java.lang.NumberFormatException`, due to it being null. 
* Add a ternary operator to the retrieval of the guild for a presence update, checking if `event.guild_id` is null, and if so it returns null, otherwise it does what it did before to retrieve the guild.
=> Add a null check to event.guild_id for presenceUpdates

src/main/java/sx/blah/discord/api/internal/DispatchHandler.java
* Proof of testing: Hard to show but got no errors.
**Issues Fixed:** [#289](https://github.com/austinv11/Discord4J/issues/289)
* Just return and don't send the event if the client can't see the channel.
...
=> Fixed MPE on ReactionAdd and ReactionRemove

src/main/java/sx/blah/discord/api/IDiscordClient.java, src/main/java/sx/blah/discord/api/internal/DiscordClientImpl.java, src/main/java/sx/blah/discord/handle/impl/obj/VoiceChannel.java, src/main/java/sx/blah/discord/handle/impl/obj/VoiceState.java
* [Proof of testing](https://gist.github.com/theIglooo/fdae2f675e626892bb6df194008f3733)
* It isn't much, just logs of me changing server deafen/mute and self deafen/mute to make sure it's cached and working properly.
**Issues Fixed:** #294 
* Add `IDiscordClient.mute(IGuild, boolean)` and `IDiscordClient.deafen(IGuild, boolean)` to control the bot user's local mute and deafened state.
* Switches the parameters provided on voice join/leave from server mute/deafen to self mute/deafen.
* Removed final from `VoiceState#isSelfMuted` and `VoiceState#isSelfDeafened` and added setters for each.
=> Implement the ability to self mute and deafen

src/main/java/sx/blah/discord/util/MessageTokenizer.java
* Fixes `MessageTokenizer#nextRegex` not using the argument pattern
=> Fix MessageTokenizer#nextRegex ignoring the pattern argument

src/main/java/sx/blah/discord/handle/impl/obj/PrivateChannel.java, src/main/java/sx/blah/discord/handle/impl/obj/VoiceChannel.java, src/main/java/sx/blah/discord/handle/obj/IPrivateChannel.java, src/main/java/sx/blah/discord/handle/obj/IVoiceChannel.java
* At the very most I used the TestBot and tested voice related commands and all of which worked. However, more testing is probably required to ensure that no part of D4J is blindly using the newly deprecated methods.
**Issues Fixed:** It is well known that the choice to have IVoiceChannel extend IChannel was...questionable. It simply does not make sense to "send a file" to a voice channel or to "get a message history" from a voice channel. To better clarify that this is problematic behavior, I have updated the documentation and deprecated methods that all would throw an `UnsupportedOperationException` for IVoiceChannel.
Additionally, I standardized behavior for a few other methods. It doesn't make sense to "get a topic" for an IVoiceChannel, for instance, so that has been changed to throw …
=> Clarified Behavior and Documentation for IVoiceChannel

src/main/java/sx/blah/discord/util/EmbedBuilder.java
* sx.blah.discord.util.DiscordException: Error on request to https://discordapp.com/api/channels/313745225954623498/messages. Received response code 400. With response text: {"embed": ["Embed size exceeds maximum size of 6000"]}
**Issues Fixed:** Fixed max from 4K -> 6K
*
...
=> 6000 characters is the max for embeds

src/main/java/sx/blah/discord/api/internal/DiscordUtils.java, src/main/java/sx/blah/discord/handle/impl/obj/Channel.java, src/main/java/sx/blah/discord/handle/obj/IChannel.java, src/main/java/sx/blah/discord/util/MessageHistory.java
#316 
#319 
1. Rewrote all message history methods to use `getMessageHistoryIn()`.
The rationale behind this change is to consolidate the logic of each history method to improve maintainability. All these methods are simply forms of getting a set of messages in a range so why not use the method for that purpose?
- `getMessageHistoryFrom()` is range `given time -> creation time`
- `getMessageHistoryTo()` is range `current time -> given time`
- `getFullMessageHistory()` is range `current time -> creation time`
2. Reworked history fetching to be based on timestamps
Discord's history API was made to be used in this way. Because snowflakes are (effectively) sequential, and they contain timestamps, we can calculate the minimum snowflake for a given timestamp and fetch history …
=> Message History Cleanup

src/main/java/sx/blah/discord/api/internal/DispatchHandler.java
* Properly fix internal reaction issues using the pre-existing utils
=> Fix Discord sending reaction events in unreadable channels

src/main/java/sx/blah/discord/handle/impl/obj/User.java, src/main/java/sx/blah/discord/handle/obj/IUser.java
* Probably works
* Add a getColorForGuild(IGuild) method in IUser that returns the displayed color of the user in the given guild
=> Added displayed color for users in guilds

src/main/java/sx/blah/discord/util/EmbedBuilder.java
* I didn't test it but it small enough to not warrant any bugs.
**Issues Fixed:** EmbedBuilder now checks if author name does not exceed the limit (See https://discordapp.com/developers/docs/resources/channel#embed-limits)
=> Added author name limit check

src/main/java/sx/blah/discord/api/internal/DiscordClientImpl.java, src/main/java/sx/blah/discord/api/internal/DiscordUtils.java, src/main/java/sx/blah/discord/handle/impl/obj/Guild.java
* ![hover](https://cdn.discordapp.com/attachments/208023865127862272/363925836744753153/unknown.png)
**Issues Fixed:** Issue #356 
* Moved updating of region cache to Guild object.
The current methodology of getting regions uses the [voice region](https://discordapp.com/developers/docs/resources/voice#list-voice-regions) endpoint (and it only does it once, when `IDiscordClient#getRegions` is first called). This is problematic because that endpoint does not return VIP regions.
So the logical step to fix this would be to simply check if a guild's region is VIP and just simply add it to the cache. The problem with this is guild's can initially be instantiated with that region, so you would have to use to use the [guild regions](https://discordapp.com/developers/docs/resources/guild#get-guild- …
=> Fixed Regions to Allow VIP

src/main/java/sx/blah/discord/api/internal/DispatchHandler.java
* [Proof of testing](https://i.imgur.com/ZnG29kx.png)
* [Proof of testing](https://i.imgur.com/kfu7Bxf.png)
Currently ReactionEvent's user variable is set to the recipient regardless of which account adds or removes the reaction, this fixes that.
=> Fix reaction events distributing incorrect user info in DMs

src/main/java/sx/blah/discord/handle/impl/obj/Message.java, src/main/java/sx/blah/discord/handle/impl/obj/User.java
* [Proof of testing](https://i.imgur.com/yFD7QrW.png)
```ERROR [Discord4J/Dispatch Handler] Unable to process JSON!
java.lang.NumberFormatException: Error at index 19 in: "234567685432245676876543"
at java.base/java.lang.NumberFormatException.forCharSequence(NumberFormatException.java:81)
at java.base/java.lang.Long.parseLong(Long.java:775)
at java.base/java.lang.Long.parseUnsignedLong(Long.java:883)
at java.base/java.lang.Long.parseUnsignedLong(Long.java:1087)
at sx.blah.discord.handle.impl.obj.Message.setChannelMentions(Message.java:227)
at sx.blah.discord.handle.impl.obj.Message.<init>(Message.java:176)
at sx.blah.discord.handle.impl.obj.Message.<init>(Message.java:183)
at sx.blah.discord.api.internal.DiscordUtils.getMessageFromJSON(DiscordUtils.java:454)
at …
```
=> Fix possible NumberFormatException when parsing channel ID

src/main/java/sx/blah/discord/api/internal/DiscordUtils.java, src/main/java/sx/blah/discord/api/internal/DispatchHandler.java, src/main/java/sx/blah/discord/api/internal/json/objects/ReactionEmojiObject.java, src/main/java/sx/blah/discord/handle/impl/obj/ReactionEmoji.java
* ![result](https://i.imgur.com/4wGJk8u.png)
Custom emoji inserted in embed using
)
**Issues Fixed:** ReactionEmoji::toString was not including the first `:` for custom emojis, support for animated emojis was also missing.
* Added `:` before emoji name in toString (`<:name:id>`)
* For animated emojis also added `a` before first `:` (`<a:name:id>`)
=> Fix ReactionEmoji::toString and add support for animated emojis

src/main/java/sx/blah/discord/handle/impl/obj/Message.java, src/main/java/sx/blah/discord/handle/impl/obj/User.java
* I've tested this fix with my bot, nothing bad happened
**Issues Fixed:** https://github.com/austinv11/Discord4J/issues/392
* Remove null elements contained in `retrievedRoles.getObject()` leading to a NullPointerException while cheking permissions in PermissionUtils.
=> Remove null elements from User#getRolesForGuild()

build.gradle
* Javadocs aggregation for documentation build. All sub-projects will be aggregate into one place. All of it is uploading into website. Just use `./gradlew aggregatedJavadocs`
* Gradle Wapper have `distributionType` filed - it was setted into `Wrapper.DistributionType.ALL` works same like `distributionUrl` last time.
I was notice your site for D3J is in progress, so I thinking adding this one. I think it will be helpful for some shading your Javadocs in one place. I tried it many times. Having some questions? I'm in on Discord or try put your expressions in this PR. 😉
=> Aggregate javadocs

src/main/java/sx/blah/discord/util/MessageTokenizer.java
Modify MessageTokenizer custom emoji regex to also accept animated custom emojis.
* [Proof of testing](https://lyrth.github.io/img/d4j-emreg-1.PNG)
**Issues Fixed:** `hasNextEmoji` and `nextEmoji` not matching animated custom emojis (for example `<a:idk:471662328983715851>`).
* Modify the MessageTokenizer custom emoji regex `<:[A-Za-z0-9_]{2,}:\\d+>` to also accept animated custom emojis (to `<a?:[A-Za-z0-9_]{2,}:\\d+>`).
=> Modify MessageTokenizer custom emoji regex

src/main/java/sx/blah/discord/handle/audit/AuditLog.java
* **Scenario:** I banned and unbanned a testing account 5 times. Each time, I put the ban reason as a number in order from 1-5; 1 being the first ban and 5 being the last. The ban reasons are printed to the console in the order that they come from the list returned by `AuditLog#getEntries()`
* [List of ban reasons before ordering](https://i.imgur.com/TSOo5kl.png)
* [List of ban reasons after ordering correctly](https://i.imgur.com/qm5twG3.png)
**Issues Fixed:** This pull request makes sure that Audit Log Entries are ordered when retrieved. They have the possibility of being out of order, which can cause problems depending on what the user is doing with the entries. (Fixes the bug mentioned by Panda in #411)
* Ensures there is order in audit log entries (ordered from most recent to oldest)
=> Ensure audit log entries are correctly ordered

src/main/java/sx/blah/discord/handle/impl/obj/Message.java
* [*] I have read and understood the [contribution guidelines](CONTRIBUTING.md)
* [*] This pull request follows the code style of the project
* [*] I have tested this feature thoroughly
[Screenshot](https://cdn.discordapp.com/attachments/504804309884469270/505558381189267456/Untitled.png)
**Issues Fixed:** IUser is no longer null when mentioned in a previous message if the discord user left the guild.
IMessage now stores List<IUser> instead of List<Long> for mentions. Previously when a user was mentioned and then leaves the guild, Message#getMentions would return a null object for that user. The issue is now gone because the IUser objects are cached.
...
=> Issue #370 Fix

core/src/main/java/discord4j/core/object/audit/AuditLogEntry.java
* This change does not need to be tested.
As discussed [here](https://github.com/discordapp/discord-api-docs/issues/811), the X-Audit-Log-Reason length ~~is~~ should be documented. Documented constants are allowed in Discord4J, this is why I propose to add it in the AuditLogEntry class.
=> Add documented audit log reason length constant

core/src/main/java/discord4j/core/spec/MessageCreateSpec.java, rest/src/main/java/discord4j/rest/http/MultipartWriterStrategy.java, rest/src/main/java/discord4j/rest/service/ChannelService.java, rest/src/main/java/discord4j/rest/util/MultipartRequest.java, rest/src/test/java/discord4j/rest/service/ChannelServiceTest.java
Add the ability to send multiple files in a message. Involves changes both to `rest` and `core` (it was not possible previously at either level). 
This is allowed by Discord.
=> Allow multiple files to be sent with a message

core/src/main/java/discord4j/core/spec/VoiceChannelJoinSpec.java, voice/src/main/java/discord4j/voice/AudioReceiver.java
Deprecate AudioReceiver.
The functionality is not supported by Discord. I don't think it should be entirely removed, but it should be clear to users that it is unsupported. If they can get it to work, that's fine.
See discordapp/discord-api-docs#808
=> Deprecate AudioReceiver

core/src/main/java/discord4j/core/object/entity/Attachment.java, core/src/main/java/discord4j/core/spec/MessageCreateSpec.java
Add `MessageCreateSpec#addFileSpoiler()` and `Attachment#isSpoiler()` to deal with the `"SPOILER_"` file name prefix used for spoiler attachments.
These are simply for convenience. You can see the implementations are incredibly simple and could be done by a user, but they're nice to have. 
#481
=> Add convenience methods for spoiler attachments

core/src/main/java/discord4j/core/event/dispatch/ChannelDispatchHandlers.java, gateway/src/main/java/discord4j/gateway/json/dispatch/ChannelCreate.java, gateway/src/main/java/discord4j/gateway/json/dispatch/MessageDelete.java, gateway/src/main/java/discord4j/gateway/json/dispatch/TypingStart.java
Expands on 522bb7755f53d97b078bbc89d38ef9aac98c3b6a to replace all possible problems with a primitive long representing an optional property.
Fixes potential issues with `guildId` being set to `0` in a DM channel, as non null is assumed to mean guild exists in other places.
=> Change ChannelCreate, MessageDelete and TypingStart to use Nullable Long

src/main/java/sx/blah/discord/api/internal/DispatchHandler.java
* [Proof of testing](https://i.imgur.com/a3TdY8N.png)
**Issues Fixed:** If a guild create event is dispatched before the bot user is logged in, it now waits before proceeding
* If the bot user is null, an `EventDispatcher#waitFor` line is called that proceeds only after a `LoginEvent` with the shard of the guild is received
=> Race Condition Fix on Guild Create

core/src/main/java/discord4j/core/object/entity/Member.java
**Description:** Add `Member#isHigher(Member)` and `Member#isHigher(Snowflake)`, two utility methods  to easily determine if a member is higher in the role hierarchy than another.
`Member#isHigher(Member)` has been tested with my bot in production and works as expected. The second one has not been tested but is largely based on the first one.
**Justification:** These are two very useful and non trivial methods to determine if a member can interact with another.
=> Add Member#isHigher(Member) and Member#isHigher(Snowflake)

core/src/main/java/discord4j/core/object/entity/Member.java
Add `Member#getHighestRole()`.
This is a useful method (can be used in methods like `Member#getColor()` and `Member#hasHigherRoles()` in #504) which is more performant than the current technique of `getRoles().last()`. 
It makes sense why it should be more performant, but just for fun, I tried to do a little [benchmark](https://gist.github.com/GrandPanda/9ffef86df8a6a5eff91bc96b25ea669c).
=> Add Member#getHighestRole()

core/src/main/java/discord4j/core/object/util/PermissionSet.java, core/src/test/java/discord4j/core/object/util/PermissionSetTest.java
* Add `PermissionSet#andNot(PermissionSet)`
* Deprecate `PermissionSet#subtract(PermissionSet)` (replaced by `andNot`)
* Improve docs and add examples (taken from tests)
* Add tests for all `PermissionSet` operations
* Fix behavior of `PermissionSet#not()`
* Improve `equals()` and `hashCode()` by providing our own implementation.
Discussion in the guild led to the decision to replace `subtract` with `andNot` because it isn't clear why there is "subtract" but not "add." These names are consistent with the JDK's `BitSet` which is essentially what `PermissionSet` is.
Improved docs and tests are always nice.
`PermissionSet#not()` previously allowed the bits for undefined permissions to be flipped to true resulting in a set with size larger than max (e.g., …
=> Improve PermissionSet functionality, docs, and tests

core/src/main/java/discord4j/core/object/entity/Member.java
**Description:** Add the method `Member#hasHigherRoles` to determine if the position of the member's highest role is greater than the highest position of the provided roles.
**Justification:** The permission `Manage Roles` from Discord allows to create new roles and to edit/delete roles lower than the member's highest role. This method allows to easily determine if the bot can actually add/remove a list of roles from another member.
**Concerns:**
- ~~This method cannot check if the provided roles come from the same guild as the member.~~
- ~~The guild is requested two times if the method `Member#isHigher(Member)` is used, I don't know if it can be optimized.~~
- ~~`Member#getRoles` emits items in order based off their natural position but is it conserved when using `Flux#collectList` and …
=> Add Member#hasHigherRoles

rest/src/main/java/discord4j/rest/request/GlobalRateLimiter.java, rest/src/main/java/discord4j/rest/request/RequestStream.java, rest/src/test/java/discord4j/rest/request/GlobalRateLimiterTest.java
**Description:** Include a fix for #513 by making each request acquire a common resource before being executed, allowing proper limiting even under parallel scenarios. Moving from a purely scheduled GRL -that could cause starvation of the parallel pool- into a transactional one.
**Justification:** Global rate limiter must be respected at the cost of throughput under very bursty scenarios. Since we currently share our event loop group across REST and gateway we must also protect that resource and avoid starvation scenarios. 
In the future we might want to explore the [reactor-pool](https://github.com/reactor/reactor-pool) project to avoid relying on blocking structures.
=> Fix #513 parallel requests vs rate limiting 

core/src/main/java/discord4j/core/DiscordClientBuilder.java, core/src/test/java/discord4j/core/ExampleBot.java, core/src/test/resources/logback.xml, rest/src/main/java/discord4j/rest/http/client/ClientException.java, rest/src/main/java/discord4j/rest/http/client/ClientRequest.java, rest/src/main/java/discord4j/rest/http/client/DiscordWebClient.java, rest/src/main/java/discord4j/rest/request/BucketKey.java, rest/src/main/java/discord4j/rest/request/DefaultRouter.java, rest/src/main/java/discord4j/rest/request/DefaultRouterFactory.java, rest/src/main/java/discord4j/rest/request/DiscordRequest.java, rest/src/main/java/discord4j/rest/request/RequestStream.java, rest/src/main/java/discord4j/rest/request/RouteMatcher.java, rest/src/main/java/discord4j/rest/request/RouterFactory.java, rest/src/main/java/discord4j/rest/request/RouterOptions.java, rest/src/main/java/discord4j/rest/request/SingleRouterFactory.java, rest/src/main/java/discord4j/rest/response/EmptyResponseTransformer.java, rest/src/main/java/discord4j/rest/response/ResponseFunction.java, rest/src/main/java/discord4j/rest/response/ResumingTransformer.java, rest/src/main/java/discord4j/rest/response/RetryingTransformer.java, rest/src/main/java/discord4j/rest/response/package-info.java, rest/src/main/java/discord4j/rest/route/Route.java, rest/src/main/java/discord4j/rest/util/RouteUtils.java, rest/src/test/java/discord4j/rest/RestTests.java
**Description:** Enable special handling of each HTTP request according to their response code.
**Justification:** Feature request. Opens up use cases to suppress expected errors for an easier to handle response.
Example usage:
```java
DiscordClient client = new DiscordClientBuilder(token)
.setRouterOptions(RouterOptions.builder()
// globally suppress any not found (404) error
.onClientResponse(ResponseFunction.emptyIfNotFound())
// wait 1 second and retry any server error (500)
.onClientResponse(ResponseFunction.retryOnceOnErrorStatus(500))
// bad requests (400) while adding reactions will be suppressed
.onClientResponse(ResponseFunction.emptyOnErrorStatus(RouteMatcher.route(Routes.REACTION_CREATE), 400))
// server error (500) while creating a message will be retried, with backoff, until …
```
=> Allow registering custom error functions

core/src/test/java/discord4j/core/ExampleBot.java, rest/src/main/java/discord4j/rest/request/DefaultRouter.java, rest/src/main/java/discord4j/rest/request/GlobalRateLimiter.java, rest/src/main/java/discord4j/rest/request/RequestStream.java, rest/src/test/java/discord4j/rest/request/GlobalRateLimiterTest.java
**Justification:** *(it makes more sense for me to start with this section)*
A few weeks ago I reported a bug affecting the global rate limiter (#513) that has been fixed as of Discord4J v3.0.3. In that issue I provided an example code which consisted of calling `client.getChannelById()` hundreds of times with fake snowflakes, so that it would result in cache misses and hit REST on each call. The bugfix works well for this specific test case, however when I deployed the Discord4J update to my production bot, I was kinda disappointed because basically I am experiencing a regression where the request throughput for some REST calls such as `channel.createMessage()` would be too slow to reach global rate limit. In this pull request I brought some optimizations to the global rate limiter in …
=> Global Rate Limiter performance improvements

core/src/main/java/discord4j/core/object/data/stored/ChannelBean.java, core/src/main/java/discord4j/core/object/entity/BaseGuildMessageChannel.java
**Description:** Fixes the NPE being thrown sometimes when getting the nsfw property from a guild message channel.
**Justification:** It seems that the nsfw property for channels can be null even on guild message channels (news and text channels). This PR fixes this by using an old boolean statement that was previously used in TextChannel before #524.
=> Fix broken nsfw property

core/src/main/java/discord4j/core/shard/ShardAwareStore.java, core/src/main/java/discord4j/core/shard/ShardAwareStoreService.java, core/src/main/java/discord4j/core/shard/ShardingClientBuilder.java, core/src/test/java/discord4j/core/StoreBotTest.java, core/src/test/resources/logback.xml
**Description**:
- Adds a new class `ShardAwareStoreService`, a wrapper `StoreService` that allows to make any implementation of `Store` shard-aware
- Adds a new method `ShardingClientBuilder#setStoreService` that provides a higher level of abstraction to configure shard-aware stores when building a sharding client
- Adds toString method to `ShardAwareStore`
- Added docs and tests for the aforementioned changes
Currently the support for configuring shard-aware stores is very limited. Discord4J provides only one class to achieve this, `ShardingJdkStoreService`, which is the default implementation used when building multi-sharded DiscordClients, and is only applicable for the `JdkStore` implementation.
When I switched to Caffeine for messages store, the only way I found …
=> Improve support for configuring shard-aware stores

core/src/main/java/discord4j/core/spec/GuildMemberEditSpec.java
**Description:** A little changes for understand you can "kick" members from channel voice
**Justification:** The actual docs not specific you can pass a null Snowflake channelid for kick a member.
**Note:** i dont know is is necesary a method like (Member::kick) for kickVoice because its strange use newchannel for kick cases.
=> Add docs for voice kick to setNewVoiceChannel

core/src/main/java/discord4j/core/object/entity/Guild.java, core/src/main/java/discord4j/core/object/entity/GuildEmoji.java, core/src/main/java/discord4j/core/object/entity/Member.java, core/src/main/java/discord4j/core/object/entity/Role.java, core/src/main/java/discord4j/core/object/entity/channel/BaseChannel.java, core/src/main/java/discord4j/core/object/entity/channel/BaseGuildChannel.java, core/src/main/java/discord4j/core/object/entity/channel/GuildChannel.java, core/src/main/java/discord4j/core/util/OrderUtil.java
* The order of emitted items from the following methods is now unspecified:
- `Guild#getRoles()`
- `Guild#getChannels()`
- `GuildEmoji#getRoles()`
- `Member#getRoles()`
* Centralize sorting behavior in `OrderUtil`.
* Change `Member#hasHigherRoles()`
- Now accepts `Set<Snowflake>`
- No longer defensively checks that roles belong to the same guild
* Defaulting to sorted is inefficient when most people don't care about the ordering. If they do care, they can still very easily access the sorted roles/channels.
* Centralized code in `OrderUtil` deduplicates sorting logic and will allow for testing.
* `Member#hasHigherRoles()` is more efficient by only sorting all of the guild roles once (instead of three times) and by making a maximum of 1 HTTP request. 
* …
=> Improve handling of sorting for guild channels and roles

core/src/main/java/discord4j/core/object/entity/ApplicationInfo.java, core/src/main/java/discord4j/core/object/entity/Guild.java, core/src/main/java/discord4j/core/object/entity/User.java, core/src/main/java/discord4j/core/object/util/Image.java, core/src/main/java/discord4j/core/spec/GuildCreateSpec.java, core/src/main/java/discord4j/core/spec/GuildEditSpec.java, core/src/main/java/discord4j/core/spec/GuildEmojiCreateSpec.java, core/src/main/java/discord4j/core/spec/UserEditSpec.java, core/src/main/java/discord4j/core/spec/WebhookCreateSpec.java, core/src/main/java/discord4j/core/spec/WebhookEditSpec.java
* Remove filtering based on image format
This is a form of local validation which breaks with our philosophy of letting Discord take care of validation. In this case, an image url with an unsupported format will 404. As with other forms of local validation, it is a burden to maintain and doesn't gain us very much.
* Refactor `Image` to keep raw image data and to be value-based.
* Add `ApplicationInfo#getIconUrl()` and change `getIcon()` to be consistent with the rest of the image-getting methods.
=> Image refactor

core/src/main/java/discord4j/core/object/data/stored/BaseGuildBean.java, core/src/main/java/discord4j/core/object/data/stored/GuildBean.java, core/src/main/java/discord4j/core/object/entity/Guild.java, gateway/src/main/java/discord4j/gateway/json/dispatch/GuildCreate.java, gateway/src/main/java/discord4j/gateway/json/dispatch/GuildUpdate.java, rest/src/main/java/discord4j/rest/json/response/GuildResponse.java
- Adds support for `preferred_locale` to get the preferred locale of a guild. 
- Adds support for `vanity_url_code` to get the vanity url code of a guild, if present. 
- Adds support for `description` to get the description of a guild, if present. 
- Adds support for `max_presences` to get the maximum amount of presences for the guild (the default value, currently 5000, is in effect when null is returned).
- Adds support for `max_members` to get the maximum amount of members for the guild, if present.
- Adds support for `unavailable` to get whether this guild is unavailable, if present. 
- Adds support for `widget_enabled` to get whether or not the server widget is enabled, if present. 
Support all guild missing fields: …
=> Support missing guild fields

core/src/main/java/discord4j/core/object/ExtendedInvite.java, core/src/main/java/discord4j/core/object/Invite.java, core/src/main/java/discord4j/core/object/data/ExtendedInviteBean.java, core/src/main/java/discord4j/core/object/data/InviteBean.java, rest/src/main/java/discord4j/rest/json/response/InviteResponse.java
- Adds support for `revoked` to get whether an invite is revoked.
- Adds support for `target_user` to get the target user this invite is associated to, if present.
- Adds support for `approximate_presence_count` to get an approximate count of online members (only present when target_user is set), if present. 
- Adds support for `approximate_member_count` to get an approximate count of total members, if present.
Support all invite missing fields: https://discordapp.com/developers/docs/resources/invite
=> Support missing invite fields

core/src/main/java/discord4j/core/object/reaction/ReactionEmoji.java
**Description:** As described here: https://github.com/discordapp/discord-api-docs/issues/812, reaction emoji name and isAnimated fields are inconsistent and Discord4J should not rely on these values to check for equality between two emojis. The id is unique across Discord and should be suffisent. 
**Reference:** cc @HunterCop224 https://github.com/Discord4J/Discord4J/issues/552
**Justification:** Fix `ReactionEmoji.Custom#equals`
=> Fix 552: ReactionEmoji.Custom#equals() is inconsistent

core/src/main/java/discord4j/core/object/VoiceState.java, core/src/main/java/discord4j/core/object/data/stored/VoiceStateBean.java, gateway/src/main/java/discord4j/gateway/json/dispatch/GuildCreate.java, gateway/src/main/java/discord4j/gateway/json/response/VoiceStateResponse.java
- Removes `self_video` field from `VoiceStateResponse` and `GuildCreate.VoiceState` because it was not used, is experimental and will be removed.
- Adds support for `self_stream` to get whether a user is streaming using "Go Live".
- Re-order `GuildCreate.VoiceState` fields to be consistent with the documentation and the `VoiceStateResponse` fields order.
**Note:** I didn't update `VoiceStateUpdate` because I don't know if the `self_stream` field should be there.
**Reference:** https://github.com/discordapp/discord-api-docs/issues/1104 and https://github.com/discordapp/discord-api-docs/pull/1108
**Justification:** Update Voice State fields: https://discordapp.com/developers/docs/resources/voice#voice-state-object
=> Update voice state fields

core/src/main/java/discord4j/core/DiscordClient.java, gateway/src/main/java/discord4j/gateway/DefaultGatewayClient.java, gateway/src/main/java/discord4j/gateway/GatewayClient.java, gateway/src/main/java/discord4j/gateway/PayloadHandlers.java
Change the return type of GatewayClient#getResponseTime() and DiscordClient#getResponseTime() to Duration and remove DefaultGatewayClient#getResponseTimeDuration()
This change was requested in issue #517
=> Change return type of getResponseTime to Duration

core/src/main/java/discord4j/core/object/presence/Activity.java
**Description:** This pull request closes issue https://github.com/Discord4J/Discord4J/issues/571 by returning an unknown activity type with ID -1 instead of throwing an exception.
**Justification:** As described in the issue linked above, `D4J enums representing discord values should be made with forwards compatibility in mind, and accept IDs that could be future additions to the Discord API.`
=> Add UNKNOWN activity type

core/src/main/java/discord4j/core/object/data/stored/RichActivityBean.java, core/src/main/java/discord4j/core/object/presence/Activity.java, gateway/src/main/java/discord4j/gateway/json/response/GameResponse.java
- Adds support for `instance` to get whether or not the activity is an instanced game session.
- Adds support for `emoji` to get the emoji used for a custom status, if present.
- Adds support for `CUSTOM` activity type.
Support all activity missing fields: https://github.com/discordapp/discord-api-docs/blob/8c70711e39df52a66de9672f1a4025a201ff0176/docs/topics/Gateway.md#activity-structure
=> Support missing activity fields

core/src/main/java/discord4j/core/object/audit/OptionKey.java, core/src/main/java/discord4j/core/util/AuditLogUtil.java, rest/src/main/java/discord4j/rest/json/response/AuditLogEntryOptionsResponse.java
**Description:** Adds message_id to optional audit entry info
**Justification:** https://github.com/discordapp/discord-api-docs/commit/ec98780def1d1bd9e860a7d907b0f35ed0495226
=> Add message_id to optional audit entry info

core/src/main/java/discord4j/core/object/entity/channel/TextChannel.java
**Description:** isNsfw method which was package-private changed to public
**Justification:** Currently you need to call the REST-API to get wether a TextChannel is NSFW flagged or not.
=> Make TextChannel#isNsfw public

common/src/main/java/discord4j/common/json/GuildMemberResponse.java, core/src/main/java/discord4j/core/object/entity/Message.java, gateway/src/main/java/discord4j/gateway/json/dispatch/MessageReactionAdd.java
**Description:** Add new message flags and add a missing @Nullable annotation. 
I didn't add the new `system?` User field because I don't really know how to deal with User fields. Some require OAuth and some not as discussed here: https://github.com/Discord4J/Discord4J/pull/560 and I don't know if this new field is also an Oauth field or not.
**Justification:** https://github.com/discordapp/discord-api-docs/commit/caca88a333010f13cdc5f695f93bc9974c32a77b
=> Add new message flags

core/src/main/java/discord4j/core/event/dispatch/DispatchHandlers.java, core/src/main/java/discord4j/core/event/domain/channel/TypingStartEvent.java, gateway/src/main/java/discord4j/gateway/json/dispatch/TypingStart.java
**Description:** Add member and guild id to starting type event
**Justification:** https://github.com/discordapp/discord-api-docs/pull/1220
**Reference:** https://github.com/Discord4J/Discord4J/issues/596
=> Add member and guild id to starting type event

core/src/main/java/discord4j/core/event/dispatch/GuildDispatchHandlers.java, core/src/main/java/discord4j/core/event/domain/guild/MemberUpdateEvent.java, core/src/main/java/discord4j/core/object/data/stored/MemberBean.java, gateway/src/main/java/discord4j/gateway/json/dispatch/GuildMemberUpdate.java
**Description:** Add `premium_since` field to Member Update Event
**Justification:** https://github.com/discordapp/discord-api-docs/pull/1261
**Reference:** https://github.com/Discord4J/Discord4J/issues/596
=> Add premium_since field to Member Update Event

gateway/src/main/java/discord4j/gateway/json/dispatch/PresenceUpdate.java
**Description:** Add premium_since and nick fields to presence update event. I didn't add corresponding methods in PresenceUpdate because I don't know how to do this. In fact, a lot of fields from the PresenceUpdate class are just ignored and not accessible.
**Justification:** https://github.com/discordapp/discord-api-docs/pull/1222
**Reference:** #596
=> Add premium_since and nick fields to presence update event

core/src/main/java/discord4j/core/object/ExtendedInvite.java, core/src/main/java/discord4j/core/object/Invite.java, core/src/main/java/discord4j/core/object/data/ExtendedInviteBean.java, core/src/main/java/discord4j/core/object/data/InviteBean.java, rest/src/main/java/discord4j/rest/json/response/InviteResponse.java
- Moves `inviter` to invite object instead of extended invite object.
- Adds supports for `target_user_type` to get the type of target user for an invite, if present.
**Justification:** https://github.com/discordapp/discord-api-docs/pull/1270 and https://discordapp.com/developers/docs/resources/invite#invite-object
=> Update invite fields

core/src/main/java/discord4j/core/spec/EmbedCreateSpec.java
**Description:** Minor change. This PR adds a `setColor` method to `EmbedCreateSpec` that accepts a raw RGB integer.
**Justification:** Using `java.awt.Color` in a modular context requires `java.desktop` to be added to the module's dependencies. This is a rather hefty addition (with a module size of 11.6MB in AdoptOpenJDK 11.0.6.10), especially since it's likely going to be used for no reason other than to access `Color` constants.
=> Permit raw RGB values in EmbedCreateSpec#setColor

core/src/main/java/discord4j/core/spec/GuildCreateSpec.java, rest/src/main/java/discord4j/rest/json/request/GuildCreateRequest.java
**Description:** Updates `GuildCreateRequest` and `GuildCreateSpec` to make all fields optional except `name`.
**Justification:** https://github.com/discordapp/discord-api-docs/pull/1312
=> All POST /guilds fields are optional except name

core/src/main/java/discord4j/core/event/dispatch/DispatchHandlers.java, core/src/main/java/discord4j/core/event/domain/InviteCreateEvent.java, core/src/main/java/discord4j/core/event/domain/InviteDeleteEvent.java, gateway/src/main/java/discord4j/gateway/json/dispatch/InviteCreate.java, gateway/src/main/java/discord4j/gateway/json/dispatch/InviteDelete.java
**Description:** The `guild_id` field inside invite create / delete events is now nullable.
**Justification:** https://github.com/discordapp/discord-api-docs/commit/33ecdc9d9402996f82bcd01c2fe33ab1da8d6613
=> Invite create/delete event guild_id is now nullable

core/src/main/java/discord4j/core/object/entity/Member.java
**Description:** If `nick` is not provided, `Member#getNickname()` will throw a `NoSuchElementException`.
=> Fix Member#getNickname

core/src/main/java/discord4j/core/object/presence/Activity.java
**Description:** Supports `Activity#createdAt()` and adds some documentations
**Justification:** Closes https://github.com/Discord4J/Discord4J/issues/611
=> Update Activity fields

core/src/main/java/discord4j/core/event/dispatch/GuildDispatchHandlers.java
Quoting DAPI documentation about guild delete event: 
`Sent when a guild becomes unavailable during a guild outage, or when the user leaves or is removed from a guild. The inner payload is an unavailable guild object. If the unavailable field is not set, the user was removed from the guild.`
If the bot has been removed from the guild, unavailable field is not present so .get() throws an exception. It can be fixed by assuming a default value or by returning an Optional<Boolean> for unavailable field to inform when the bot has been kicked.
This pull request is assuming a default value to false but discussion is opened.
EDIT: After discussing with xaanit, it seems that `false` value is never set, this field is either true or empty. In this case, a default value set to false …
=> Fix NoSuchElementException in GuildDeleteEvent

rest/src/main/java/discord4j/rest/request/ProcessorRequestQueueFactory.java, rest/src/main/java/discord4j/rest/request/RequestQueue.java, rest/src/main/java/discord4j/rest/request/RequestQueueFactory.java, rest/src/main/java/discord4j/rest/request/RequestStream.java, rest/src/main/java/discord4j/rest/request/RouterOptions.java
This PR exposes a `RequestQueue<T>` interface to add an abstraction level to the REST request queuing logic. Providing a custom queue implementation is done via a generic factory pattern and configurable via `RouterOptions`.
A single `RequestQueueFactory` object has the ability to create `RequestQueue<T>` instances of any type `T`. This magic is possible by placing the `<T>` on the `create()` method instead of the `RequestQueueFactory` class:
```java
public interface RequestQueueFactory {
<T> RequestQueue<T> create();
}
```
It's then up to the implementor of this factory to guarantee that the create method works for any `T` without causing cast problems. The default implementation is `ProcessorRequestQueueFactory` which simply creates a queue backed by a custom …
=> Added abstraction for REST request queue

core/src/main/java/discord4j/core/object/entity/Message.java, core/src/main/java/discord4j/core/object/entity/User.java, core/src/main/java/discord4j/core/object/entity/channel/BaseGuildChannel.java, core/src/main/java/discord4j/core/object/entity/channel/BaseGuildMessageChannel.java, core/src/main/java/discord4j/core/object/presence/Activity.java, core/src/main/java/discord4j/core/spec/CategoryEditSpec.java, core/src/main/java/discord4j/core/spec/GuildCreateSpec.java, core/src/main/java/discord4j/core/spec/GuildEmojiCreateSpec.java, core/src/main/java/discord4j/core/spec/GuildEmojiEditSpec.java, core/src/main/java/discord4j/core/spec/InviteCreateSpec.java, core/src/main/java/discord4j/core/spec/MessageEditSpec.java, core/src/main/java/discord4j/core/spec/UserEditSpec.java, core/src/main/java/discord4j/core/spec/WebhookCreateSpec.java, core/src/main/java/discord4j/core/spec/WebhookEditSpec.java, rest/src/main/java/discord4j/rest/entity/RestChannel.java, rest/src/main/java/discord4j/rest/entity/RestRole.java, rest/src/main/java/discord4j/rest/entity/RestUser.java, rest/src/test/java/discord4j/rest/service/ChannelServiceTest.java, rest/src/test/java/discord4j/rest/service/UserServiceTest.java
**Description:** Use Builder inside Spec::asRequest for forward-compatibility.
**Justification:** Fix https://github.com/Discord4J/Discord4J/issues/652
=> Forward-compatibility of Spec::asRequest by using Builder

rest/src/main/java/discord4j/rest/request/DiscardedRequestException.java, rest/src/main/java/discord4j/rest/request/ProcessorRequestQueueFactory.java, rest/src/main/java/discord4j/rest/request/RequestStream.java
Added doOnDiscard operator to properly terminate the requests when they are discarded due to backpressure. I had to slightly change the implementation of processor request queue factory to make this operator work (basically I wrapped the processor in a `Flux.create` that drains the processor and forwards onNext signals to a sink that has access to the onDiscard callback, unlike the processor's own sink). When a request is discarded I made it so the response completes empty, but I wouldn't mind changing it to make it error with an exception, I'm open to discussion regarding this. 
Currently there's a bug that causes REST requests to never complete if the request gets discarded by the overflow strategy. Talked with @quanticc about it on Discord and we had a hard time finding a solution, but …
=> Fix requests never completing when discarded by backpressure

common/src/main/java/discord4j/common/operator/RateLimitOperator.java, rest/src/main/java/discord4j/rest/request/BucketGlobalRateLimiter.java, rest/src/test/java/discord4j/rest/request/GlobalRateLimiterTest.java, rest/src/test/resources/logback.xml
Fixes a bug in the current implementation of `RateLimitOperator` that causes it to get stuck when acquiring/releasing a permit. It was caused by the processor not using a FluxSink, and was most likely triggered by the parallel scheduler being on high load (testing revealed that tokens were all published on the parallel scheduler).
This fix changes the processor implementation to `ReplayProcessor#cacheLastOrDefault` with LATEST overflow strategy, and publishes tokens on a dedicated single scheduler to relieve parallel scheduler while still properly handling concurrent requests.
`BucketGlobalRateLimiter` also had a minor fix by avoiding delaying the Duration object via this operator. It instead applies the operator on a placeholder value first, then it handles the `getRemaining()`, to be …
=> Fix rate limiter deadlock on high parallel load

core/src/main/java/discord4j/core/retriever/FallbackEntityRetriever.java
**Description:** Make FallbackEntityRetriever class and constructor public.
**Justification:** This is useful if we want to create a custom entity retriever strategy using the already-defined FallbackEntityRetriever.
=> Make FallbackEntityRetriever public

core/src/main/java/discord4j/core/event/dispatch/GuildDispatchHandlers.java, core/src/test/java/discord4j/core/support/VoiceSupport.java
**Description:** This PR wraps generated VoiceStateData objects created on a guild create event in such a way that said objects will contain the guild id from the primary event.
**Justification:** Getting the Guild ID from a pre-existing voice state no longer throws an exception. This pull request fixes #658
=> Fix support for VoiceState.getGuildId; closes #658

core/src/main/java/discord4j/core/event/dispatch/DispatchEventMapper.java
**Description:** Added a NoOp DispatchEventMapper as default implementation, this EventMapper doesn't do any JSON serialization and saves tons of performance on gateway-level when **NO** event processing is required.
**Justification:** Performance issues on gateway level
=> NoOp DispatchEventMapper

core/src/main/java/discord4j/core/object/entity/Guild.java, rest/src/main/java/discord4j/rest/entity/RestGuild.java
Add `getSelfMember()` to Guild and RestGuild classes. 
This provides an easier and clearer way of getting the bot user's Member  and MemberData from a guild or RestGuild entity respectively.
=> Add `getSelfMember()` to Guild and RestGuild classes

core/src/main/java/discord4j/core/GatewayResources.java, core/src/main/java/discord4j/core/event/dispatch/GuildDispatchHandlers.java, core/src/main/java/discord4j/core/shard/GatewayBootstrap.java, core/src/main/java/discord4j/core/shard/MemberRequestFilter.java
**Description:** Initial work to resolve issues described in #660. Provide API to customize the member request behavior.
Example usage:
```java
DiscordClient.create(System.getenv("token"))
.gateway()
.setMemberRequestFilter(MemberRequestFilter.all().as(m -> m.delayElement(Duration.ofSeconds(10))))
.login().block();
```
The idea @danthonywalker had is to make this filter return `Mono` so users can inject a delay or perform any kind of async logic.
**Justification:** Looking for ways to mitigate members not being sent under some intent configurations. Covering said ticket entirely is not a goal of this PR.
=> Add MemberRequestFilter to control member loading

gateway/src/main/java/discord4j/gateway/DefaultGatewayClient.java, gateway/src/main/java/discord4j/gateway/GatewayWebsocketHandler.java, gateway/src/main/java/discord4j/gateway/PayloadHandlers.java, gateway/src/main/java/discord4j/gateway/retry/ReconnectException.java
**Description:** Issue #655
**Justification:** Reconnects happen quite often but aren't really an error since latest changes
=> Not printing reconnect-event as error

core/src/main/java/discord4j/core/event/dispatch/GuildDispatchHandlers.java, core/src/main/java/discord4j/core/event/domain/guild/MemberChunkEvent.java
- Adds `chunk_index` field
- Adds `chunk_count` field
- Adds `not_found` field
- Adds `nonce` field
https://github.com/discord/discord-api-docs/pull/1545
https://github.com/discord/discord-api-docs/pull/1549
=> Update MemberChunkEvent fields

core/src/main/java/discord4j/core/object/entity/channel/AllowedMentions.java, core/src/main/java/discord4j/core/spec/MessageCreateSpec.java, core/src/test/java/discord4j/core/ExampleAllowedMentions.java
Implements the allowed_mentions json object to Discord4J with a static builder factory
Refers to #629 
**Justification:** allowed_mentions as new field in the message create request
=> Implemented AllowedMentions 

core/src/main/java/discord4j/core/object/entity/Guild.java
- Adds `rules_channel` support
- Adds `public_updates_channel` support
- ~~Adds `owner` support~~
- Adds `embed_enabled` support
**Justification:** https://discordapp.com/developers/docs/resources/guild#guild-object
**Note:** Discord staff has never confirmed that `rules_channel` and `public_updates_channel` are only guild text channels. They could also be news channels but it is a safe assumption to think that they are at least guild text channels.
=> Update Guild fields

core/src/main/java/discord4j/core/retriever/StoreEntityRetriever.java
**Description:** In this commit <https://github.com/Discord4J/Discord4J/commit/9c93af766395e55e6a3acb8ffb3b1920035cbed6>, members are requested when not present in the cache using `StoreEntityRetriever#getGuildMembers`. This pull request does the same for `getMemberById`
**Justification:** https://github.com/Discord4J/Discord4J/issues/660
=> Request member from the gateway if missing from the cache

core/src/main/java/discord4j/core/spec/VoiceChannelJoinSpec.java
**Description:** Adds a configurable timeout to the join voice channel request. It is needed to ensure that the request does not get stuck indefinitively when the bot tries to join a voice channel without the `Permission.VIEW_CHANNEL` permission.
It could be interesting to add a note in the `VoiceChannel#join` method to mention that the method can throw a `TimeoutException`.
These changes can be tested using the following code:
```java
final GatewayDiscordClient client = DiscordClient.builder("token")
.build()
.login()
.block();
client.getEventDispatcher()
.on(MessageCreateEvent.class)
.filter(event -> event.getMessage().getContent().startsWith("!join"))
.flatMap(event -> client.getChannelById(Snowflake.of("voice-channel-id"))
.cast(VoiceChannel.class)
.flatMap(channel -> …
```
=> Adds configurable timeout to VoiceChannelJoinSpec

core/src/main/java/discord4j/core/object/entity/channel/BaseGuildMessageChannel.java, core/src/main/java/discord4j/core/object/entity/channel/GuildMessageChannel.java
**Description:** A method to get all members of a guild which have the permission to view a specific channel.
**Justification:** QoL change
=> Add method for getting all members in a guild channel

core/src/main/java/discord4j/core/object/entity/channel/TextChannel.java
**Description:** As stated by the [documentation](https://discord.com/developers/docs/resources/channel#channel-object-channel-structure), `nsfw` is a possibly absent field. It should be then considered as `false` by default to avoid `NoSuchElementException`.
https://discord.com/developers/docs/resources/channel#channel-object-channel-structure
```
java.util.NoSuchElementException: null
at discord4j.discordjson.possible.Possible.get(Possible.java:40)
at discord4j.core.object.entity.channel.TextChannel.isNsfw(TextChannel.java:59)
at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
```
=> Fix possible NoSuchElementException on TextChannel#isNsfw

core/src/main/java/discord4j/core/spec/VoiceChannelJoinSpec.java
**Description:** Double the default voice timeout value.
**Justification:** 5 seconds was a bit short, it could lead to case like this where the timeout was occurring during the session description leading to a false concurrent voice handshakes detection afterwhile.
```
2020-05-06 17:46:49.875 INFO [Thread-9/shadbot.music]: {Guild ID: 597111231035473941} Joining voice channel...
2020-05-06 17:46:50.062 INFO [d4j-events-1/shadbot.music]: {Guild ID: 597111231035473941} Voice channel joined
2020-05-06 17:46:54.512 INFO [reactor-http-epoll-3/discord4j.voice.DefaultVoiceGatewayClient]: [G:d37fb4e, S:5, guildId:597111231035473941] Identifying
2020-05-06 17:46:54.812 INFO [reactor-http-epoll-3/discord4j.voice.DefaultVoiceGatewayClient]: [G:d37fb4e, S:5, guildId:597111231035473941] Waiting for …
```
=> Change default voice timeout value

core/src/main/java/discord4j/core/object/Embed.java, core/src/main/java/discord4j/core/object/entity/Member.java, core/src/main/java/discord4j/core/object/entity/Role.java, core/src/main/java/discord4j/core/spec/EmbedCreateSpec.java, core/src/main/java/discord4j/core/spec/RoleCreateSpec.java, core/src/main/java/discord4j/core/spec/RoleEditSpec.java, rest/src/main/java/discord4j/rest/util/Color.java, rest/src/test/java/discord4j/rest/util/ColorTest.java
**Description:** An attempt to replace `java.awt.Color` with custom Color class which provides basic functionalities. Let me know if this needs more functionality like taking into account float rgb values or `brighter` and ` darker` methods for example.
**Justification:** Fix https://github.com/Discord4J/Discord4J/issues/696
=> Replace java.awt.color with custom Color class

core/src/main/java/discord4j/core/object/entity/Guild.java, rest/src/main/java/discord4j/rest/entity/RestGuild.java, rest/src/main/java/discord4j/rest/route/Routes.java, rest/src/main/java/discord4j/rest/service/GuildService.java, rest/src/test/java/discord4j/rest/service/GuildServiceTest.java
**Description:** Guild embed was renamed to widget 
https://github.com/discord/discord-api-docs/pull/1536
https://github.com/Discord4J/discord-json/pull/17
=> Deprecate embed fields

core/src/main/java/discord4j/core/object/Embed.java, core/src/main/java/discord4j/core/object/entity/Role.java, core/src/main/java/discord4j/core/spec/EmbedCreateSpec.java, core/src/main/java/discord4j/core/spec/RoleCreateSpec.java, core/src/main/java/discord4j/core/spec/RoleEditSpec.java, rest/src/main/java/discord4j/rest/util/Color.java, rest/src/test/java/discord4j/rest/util/ColorTest.java
Cleanup the implementation of Color to be simpler. A part of this was removing alpha as Discord does not use it (in fact including it breaks things!).
Removed constructors to fit the rest of how D4J plays out regarding constructors and static factory methods. Additionally added static constants you'd see on `java.awt.Color`
=> Cleanup Color and Add Constants

core/src/main/java/discord4j/core/GatewayDiscordClient.java, core/src/main/java/discord4j/core/util/ValidationUtil.java, core/src/test/java/discord4j/core/ExampleIntents.java, core/src/test/java/discord4j/core/util/ValidationUtilTest.java
**Description:** Adds validation for the `requestMembers()` function.
**Justification:** For https://github.com/Discord4J/Discord4J/issues/684
=> Validate intents for GatewayDiscordClient::requestMembers

rest/src/main/java/discord4j/rest/entity/RestChannel.java
**Description:** Adds RestChannel#createMessage taking message content and an embed only
**Justification:** It's annoying having to use EmbedData#builder every time for simple messages like content only or embed only.
=> RestChannel#createMessage for content and embed only

core/src/main/java/discord4j/core/event/dispatch/ChannelDispatchHandlers.java, core/src/main/java/discord4j/core/event/dispatch/MessageDispatchHandlers.java, core/src/main/java/discord4j/core/event/domain/channel/PinsUpdateEvent.java, core/src/main/java/discord4j/core/event/domain/message/MessageDeleteEvent.java, core/src/main/java/discord4j/core/object/entity/Message.java
**Description:** Adds `getGuildId` and `getGuild` methods to PinsUpdateEvent and MessageDeleteEvent, and a `getGuildId` method to the Message entity.
**Justification:** Discord sends the `guildId` on PinsUpdateEvent and MessageDeleteEvent,
so expose them too. The `getGuildId` method was absent in the Message entity despite the presence of a `getGuild` method.
=> Add getGuildId and getGuild to classes missing them

core/src/main/java/discord4j/core/event/dispatch/GuildDispatchHandlers.java
**Description:** Ensure that `guild_id` fields are named `guildId()`.
**Justification:** https://github.com/Discord4J/discord-json/pull/22
=> Ensure that guild_id fields are named guildId()

core/src/main/java/discord4j/core/object/entity/channel/VoiceChannel.java
**Description:** Adds a method inside `VoiceChannel` to detect if a member is connected to the voice channel.
**Justification:** This is frequently asked and the solution is not trivial, it can be a good QOL improvement to add this.
=> Adds VoiceChannel#isMemberConnected

rest/src/main/java/discord4j/rest/entity/RestGuild.java, rest/src/test/java/discord4j/rest/util/RouteUtilsTest.java
**Description:** Rename `delete-message-days` to `delete_message_days`.
**Justification:** Some fields have not been updated during https://github.com/Discord4J/Discord4J/pull/730 merge.
=> Rename delete-message-days to delete_message_days

core/src/main/java/discord4j/core/object/entity/channel/BaseGuildMessageChannel.java, core/src/main/java/discord4j/core/object/entity/channel/GuildMessageChannel.java, rest/src/main/java/discord4j/rest/entity/RestChannel.java
**Description:** Documentation on `GuildMessageChannel#bulkDelete` was improved to show an example of more streamlined and intended usage. Additionally the implementation has been greatly improved by fixing multiple subscription bug, removing external `Collection`, and properly encapsulating everything as a chain.
This does float a subscribe, but the subscription is tightly coupled to the sink it is providing values to.
**Justification:** I've known about the multiple subscription bug for a while and I wanted to fix it and greatly improve the implementation (could of just easily slap on a `Flux.defer` around the whole thing). Documentation could also be a little better to showcase the streamline usage of `transform` in combination of expected method pairings.
=> Improve bulkDelete implementation and documentation

core/src/main/java/discord4j/core/object/Embed.java, core/src/main/java/discord4j/core/object/MessageReference.java, core/src/main/java/discord4j/core/object/VoiceState.java, core/src/main/java/discord4j/core/object/entity/GuildEmoji.java, core/src/main/java/discord4j/core/object/entity/channel/TextChannel.java
Replace many uses of Possible::get with explicit `orElseThrow`. These were mostly in places in `core` entities where it wasn't clear previously if the fields actually had the potential to be absent. I have included comments to explain where the equivalent `get()` would have been safe. 
In the case of `Embed`, many of the uses of `get()` were not safe and resulted in errors. For now, they have been updated to return `null` instead. A following PR targeted to 3.2 will make them `Optional`. 
Fixes #747
=> Fix some problematic uses of Possible::get

core/src/main/java/discord4j/core/object/FollowedChannel.java, core/src/main/java/discord4j/core/object/entity/channel/NewsChannel.java, rest/src/main/java/discord4j/rest/entity/RestChannel.java, rest/src/main/java/discord4j/rest/route/Routes.java, rest/src/main/java/discord4j/rest/service/ChannelService.java
:warning: **Depends on https://github.com/Discord4J/discord-json/pull/27**
* Add `NewsChannel#follow(Snowflake)` - Follow the news channel, creating webhook to target channel given in argument
* Create `FollowedChannel` class which is the response returned when following a channel (allows to retrieve the news channel instance and the newly created webhook)
* Added corresponding routes and requests in the rest module
**Justification:** There is this PR on discord docs repo: https://github.com/discord/discord-api-docs/pull/1692/files
The /crosspost endpoint was already implemented via https://github.com/Discord4J/Discord4J/pull/665 but not the /followers one.
=> Add support for channel following

core/src/main/java/discord4j/core/event/dispatch/GuildDispatchHandlers.java, core/src/main/java/discord4j/core/event/domain/guild/MemberUpdateEvent.java
**Description:** Add `joined_at` field to `GuildMemberUpdate` event.
**Justification:** https://github.com/Discord4J/discord-json/pull/28
=> Add joined_at field to GuildMemberUpdate

core/src/main/java/discord4j/core/event/dispatch/GuildDispatchHandlers.java, core/src/main/java/discord4j/core/event/domain/guild/EmojisUpdateEvent.java
**Description:** Add getOld function to EmojisUpdateEvent
**Justification:** From [Issue#734](https://github.com/Discord4J/Discord4J/issues/734). EmojisUpdateEvent was missing a getOld() function while other update events have it.
=> Add getOld function to EmojisUpdateEvent

core/src/main/java/discord4j/core/GatewayDiscordClient.java, core/src/main/java/discord4j/core/object/presence/Activity.java, core/src/main/java/discord4j/core/object/presence/Presence.java
**Description:** Support for the new Activity type for presence the "Competing", this can be used by bots.
**Justification:** https://github.com/discord/discord-api-docs/commit/cd6c72a9a297c32ef59f3243eaddd9167fb4e1c3
=> Support for the COMPETING Activity type

core/src/main/java/discord4j/core/object/entity/Message.java, core/src/main/java/discord4j/core/object/entity/channel/NewsChannel.java, rest/src/main/java/discord4j/rest/entity/RestMessage.java, rest/src/main/java/discord4j/rest/route/Routes.java, rest/src/main/java/discord4j/rest/service/ChannelService.java
**Description:** Discord release in docs the crosspost and follow endpoints, in the case of crosspost now confirm the endpoint return the Message published (when make the PR only return a empty). Then i change the returns and remove the experimental annotation.
**Justification:** https://github.com/discord/discord-api-docs/commit/960a8eaf13a55453e9a5aeafb1086645906d25ec
=> Changes in Crosspost and Follow methods

core/src/main/java/discord4j/core/object/entity/Guild.java, core/src/main/java/discord4j/core/object/entity/channel/VoiceChannel.java
**Description:** Adds method to obtain a VoiceConnection registered to a guild snowflake through VoiceConnectionRegistry directly to Guild. Also adds a method to obtain a registered VoiceConnection from a VoiceChannel.
**Justification:** https://discordapp.com/channels/208023865127862272/451125724766535710/758786914496151562
=> Add methods for obtaining an existing, registered VoiceConnection to associated entities

core/src/main/java/discord4j/core/event/domain/channel/PrivateChannelCreateEvent.java
**Description:** Deprecate `PrivateChannelCreateEvent`.
**Justification:** [DAPI v8 Changelog](https://github.com/discord/discord-api-docs/blob/master/docs/Change_Log.md)
=> Deprecate PrivateChannelCreateEvent

core/src/main/java/discord4j/core/object/entity/Webhook.java, rest/src/main/java/discord4j/rest/entity/RestGuild.java, rest/src/main/java/discord4j/rest/service/GuildService.java
**This PR depends on https://github.com/Discord4J/discord-json/pull/32**
- Adds `Webhook#getApplicationId()`
- Supports `include_applications` when requestions integrations
**Justification:** https://github.com/discord/discord-api-docs/pull/1886
=> Update Integration support

core/src/main/java/discord4j/core/event/domain/VoiceStateUpdateEvent.java
**Description:** This pull request is a draft because I'm not really satisfied with the javadoc and the method naming. Anyway, this PR is open to discuss the usefulness of these changes.
**Justification:** Discord API only provides one event to all voice state updates. It may be hard to determine if the event is related to a user joining, leaving or moving voice channel. This PR tries to improve that.
=> Add VoiceStateUpdateEvent utility functions

rest/src/main/java/discord4j/rest/entity/RestGuild.java, rest/src/main/java/discord4j/rest/service/GuildService.java
- Remove `include_applications` field when getting guild integrations because it is no longer taken into account in V8.
**Justification:** https://github.com/discord/discord-api-docs/pull/2175
=> Remove include_applications when getting guild integrations

core/src/main/java/discord4j/core/event/dispatch/GuildDispatchHandlers.java, core/src/main/java/discord4j/core/event/domain/guild/MemberUpdateEvent.java
- Rename the element `currentRoles` to `currentRoleIds` in `MemberUpdateEvent`, along with all other references to this collection, including the event's constructor, the getter, the `toString()` implementation, and the guild dispatch handler.
- Update the collection from `List` to `Set` to match the getter.
- Add a new method, `getCurrentRoles()`, to return a `Flux` of the roles referenced by the `currentRoleIds`. **The way this works is that it fetches all roles for the guild and filters for only the ones that are owned by the member. If there is a way to only request the roles by their IDs directly, I assume we would prefer to do it that way instead. I don't immediately see a way to do that, however, without requesting each role individually.**
To …
=> Rename currentRoles to currentRoleIds

core/src/main/java/discord4j/core/spec/MessageReferenceSpec.java
**Description:** Fixed issue in MessageReferenceSpec calling wrong methods for MessageReferenceData
**Justification:** Calling```spec.setMessageId(messageId)```  or ```spec.setChannelId(channelId)``` would set MessageReferenceData.guildId which resulted in an error from the DiscordApi.
=> Call correct methods

core/src/main/java/discord4j/core/object/entity/Member.java
Try to get the latest bot's presence by requesting it, returns Mono.empty() otherwise.
Fix https://github.com/Discord4J/Discord4J/issues/475
=> Fix: Bot's presence is not updated using Member#getPresence

rest/src/main/java/discord4j/rest/entity/RestGuild.java, rest/src/main/java/discord4j/rest/route/Routes.java, rest/src/main/java/discord4j/rest/service/GuildService.java, rest/src/test/java/discord4j/rest/service/GuildServiceTest.java
Adds support for get guild preview in RestGuild. 
@Doc94 Is it what you were expecting?
Documentation: https://discord.com/developers/docs/resources/guild#get-guild-preview
Closes: https://github.com/Discord4J/Discord4J/issues/780
=> Support get guild preview

core/src/main/java/discord4j/core/spec/MessageEditSpec.java
Adds possibility to edit allowed mentions in MessageEditSpec.
Dapi allows to edit allowed mentions, it was implemented in discord-json repository but not in MessageEditSpec.
=> Adds setAllowedMentions to MessageEditSpec

build.gradle, gateway/src/main/java/discord4j/gateway/json/dispatch/EventNames.java, gateway/src/main/java/discord4j/gateway/json/jackson/PayloadDeserializer.java, gradle.properties, rest/src/main/java/discord4j/rest/RestClient.java, rest/src/main/java/discord4j/rest/http/ExchangeStrategies.java, rest/src/main/java/discord4j/rest/http/WebhookMultipartWriterStrategy.java, rest/src/main/java/discord4j/rest/route/Routes.java, rest/src/main/java/discord4j/rest/service/ApplicationService.java, rest/src/main/java/discord4j/rest/service/InteractionService.java, rest/src/main/java/discord4j/rest/service/WebhookService.java, rest/src/main/java/discord4j/rest/util/ApplicationCommandOptionType.java, rest/src/main/java/discord4j/rest/util/InteractionResponseType.java, rest/src/main/java/discord4j/rest/util/WebhookMultipartRequest.java
**Description:** This PR adds the necessary routes for creating and responding to slash commands.
**Justification:** #818 and [Discord API Changes](https://github.com/discord/discord-api-docs/pull/2295)
This PR depends on [Discord4J/discord-json#43](https://github.com/Discord4J/discord-json/pull/43).
This does **not** implement components in discord4j-core yet, as that will require a bit of extra work and design.
=> Add slash commands to discord4j-rest and discord4j-gateway

rest/src/main/java/discord4j/rest/entity/RestGuild.java, rest/src/main/java/discord4j/rest/service/GuildService.java, rest/src/test/java/discord4j/rest/entity/RestGuildTest.java
**Description:** This PR adds the with_counts query parameter to the GET guild request. It should fix issue #795.
**Justification:** The query parameter is given in the official Discord Developer Documentation. https://discord.com/developers/docs/resources/guild#get-guild
=> Add with_counts query param to GET guild

rest/src/main/java/discord4j/rest/entity/RestMember.java, rest/src/main/java/discord4j/rest/util/OrderUtil.java
Adds in role and hierarchy comparison to RestMember similar to the existing methods in Member to more easily check Member hierarchy through REST without needing the DiscordGatewayClient
Also added documentation to these new methods, as well as finished the documentation for RestMember as some existing methods were not yet documented.
This functionality existed in the Member class, however, it required the DiscordGatewayClient, even though these methods only need to use REST requests. This makes it significantly easier to compare users' roles without requiring a full gateway connection.
Came across the need for this while working on a section of my bot's backend that only has access to the D4J rest client (DiscordClient). Rather than re-invent the wheel to compare these roles, I added in …
=> Add role and hierarchy comparison to RestMember similar to in Member

core/src/main/java/discord4j/core/object/Embed.java, core/src/main/java/discord4j/core/object/entity/Message.java, core/src/main/java/discord4j/core/object/entity/Webhook.java
Moves the max embed characters constant into the `Message` class, since the limit applies across all embeds of a message, not just a single embed. The name has also been changed accordingly.
Fixes #832
=> Move the max embed characters constant to the proper context

core/src/main/java/discord4j/core/event/domain/PresenceUpdateEvent.java, core/src/main/java/discord4j/core/event/domain/UserUpdateEvent.java
The JavaDocs for `UserUpdateEvent` and `PrescenceUpdateEvent` should be clarified for easier understanding of when/why they are dispatched.
`UserUpdateEvent` currently states that it is dispatched when "__a__ user's presence changes." while this is not the case. @quanticc mentioned in the Discord server that this should specify it is for the Bot user.
`PrescenceUpdateEvent` implies that it is only dispatched when when the user's presence changes, it is not immediately stated that this also includes username/discriminator/avatar changes.
=> clarify UserUpdateEvent and PresenceUpdateEvent JavaDocs

core/src/main/java/discord4j/core/object/entity/Message.java
**Description:** Conserve order for user mentions, role mentions and reactions on message.
**Justification:** This is needed if you do some computations based on the order.
https://discord.com/channels/208023865127862272/451125724766535710/819270463238701057
=> Conserve order for user mentions, role mentions and reactions on message

core/src/main/java/discord4j/core/object/entity/Message.java
- `getUserMentionIds`, `getRoleMentionIds`, `getReactions` are now returning `List` instead of `Set` to simplify manipulation on the user side. For example: getting the first mentions of a message. The implementation used is a `LinkedList` to conserve the order returned by discord which is the same as the order of the message. The documentation has been updated accordingly.
- `getUserMentions` is now returning a `List` instead of a `Flux` because Discord already returns `UserData` in the message payload.
- Cherrypick of https://github.com/Discord4J/Discord4J/pull/857
- `getUserMentions` does not need to return a Flux because user data are already provided in `MessageData`
**Tests:**
- [Non DM user mentioned in DM](https://pastebin.com/CTZkAVLw)
- [Non …
=> Conserve order and use provided user data to get user mentions

rest/src/main/java/discord4j/rest/http/client/ClientException.java
This allows access to the low-level netty response in the `ClientException`
The ABI of `ClientException` already exposes netty-internal classes so I think adding another one is fine.
This allows subsequently custom implementations of a `Router` to get the reactive context from the response, which contains the request time set on it in the `DiscordWebClient`.
Example code:
```kotlin
/**
* Collect metrics about the executed web requests against the Discord API
*/
class InstrumentedRouter(private val delegate: Router, routerOptions: RouterOptions) : Router {
private val reactorResources: ReactorResources = routerOptions.reactorResources
override fun exchange(request: DiscordWebRequest): DiscordWebResponse {
val exchange = delegate.exchange(request)
val instrumentedResponse …
```
=> Access low-level response from ClientException

core/src/main/java/discord4j/core/spec/EmbedCreateSpec.java
Add a convenience method to allow populating an `EmbedCreateSpec` from an existing `EmbedData`.
It seems like a sensible convenience method, adding similar functionality in the consuming code is possible but cumbersome.
=> Allow populating EmbedCreateSpec from existing Embed

core/src/main/java/discord4j/core/object/entity/channel/BaseGuildChannel.java, core/src/main/java/discord4j/core/object/entity/channel/BaseGuildMessageChannel.java, core/src/main/java/discord4j/core/object/entity/channel/GuildChannel.java
Allow passing in a proper `Member` object into `GuildChannel#getEffectivePermissions` instead of just a `SnowflakeId`.
This allows optimizations of rest requests in certain situations.
When the GUILDS intent is used, but not the GUILD_MEMBERS intent, calling `getEffectivePermissions` with just the SnowflakeId of the user will result in a REST request to fetch the member (but no other request, as the owner, role data, etc can be served from the entity cache). In some situations it is unnecessary to fetch the member from the API. A `MessageCreateEvent` contains a `Member` object for the author, so if we wanted to check their permissions, we could avoid that API request by passing that member object to `getEffectivePermissions`, reducing the amount of …
=> Allow passing in member for calculating effective permissions

common/src/main/java/discord4j/common/store/Store.java, common/src/main/java/discord4j/common/store/legacy/LegacyStoreLayout.java, core/src/main/java/discord4j/core/event/dispatch/ChannelDispatchHandlers.java, core/src/main/java/discord4j/core/object/presence/Presence.java
Add more descriptive error messages to thrown `AssertionError`s throughout the codebase.
I got a bunch of these in my Sentry:
```
java.lang.AssertionError: null
at discord4j.common.store.legacy.LegacyStoreLayout.onChannelUpdate(LegacyStoreLayout.java:391)
at space.npstr.aki.discord.store.InstrumentedGatewayDataUpdater.lambda$onChannelUpdate$6(InstrumentedGatewayDataUpdater.java:111)
at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
at reactor.core.publisher.Operators$MonoInnerProducerBase.comple …
```
=> Improve AssertionError messages

core/src/main/java/discord4j/core/GatewayDiscordClient.java, core/src/main/java/discord4j/core/retriever/EntityRetriever.java, core/src/main/java/discord4j/core/retriever/FallbackEntityRetriever.java, core/src/main/java/discord4j/core/retriever/RestEntityRetriever.java, core/src/main/java/discord4j/core/retriever/StoreEntityRetriever.java, rest/src/main/java/discord4j/rest/RestClient.java
This adds in methods to EntityRetriever and RestClient to directly get the bot as a Member of a guild, making chains slightly easier to read when requiring the bot as a Member of the guild, rather than just a User.
For EntityRetriever, one method `getSelfMember(guildId)` was added, along with the overrides for the 4 classes implementing.
For RestClient, two methods were added `selfRestMember(guildId)` to retrieve the RestMember of the bot, and `getSelfMember(guildId)` to retrieve the MemberData of the bot, depending on which is needed by the programmer.
This is targeting the latest master branch changes as of this commit.
=> Add methods to EntityRetriever and RestClient to make getting self Member easier

rest/src/main/java/discord4j/rest/entity/RestChannel.java, rest/src/main/java/discord4j/rest/entity/RestEmoji.java, rest/src/main/java/discord4j/rest/entity/RestGuild.java, rest/src/main/java/discord4j/rest/entity/RestGuildTemplate.java, rest/src/main/java/discord4j/rest/entity/RestInvite.java, rest/src/main/java/discord4j/rest/entity/RestMember.java, rest/src/main/java/discord4j/rest/entity/RestMessage.java, rest/src/main/java/discord4j/rest/entity/RestRole.java, rest/src/main/java/discord4j/rest/entity/RestUser.java, rest/src/main/java/discord4j/rest/entity/RestWebhook.java
Adds public read-only accessors to rest* entities for convenience, and to avoid the rest request for getting the data where the ID can be obtained previously.
=> Add public accessors for IDs in rest* entities

core/src/main/java/discord4j/core/object/entity/Message.java
**Description:** Adds message types 16, 17 and 20. 
```Type `19` and `20` are only in API v8. In v6, they are still type `0`.```
**Justification:** https://github.com/discord/discord-api-docs/pull/1779
=> [3.1.x] Adds message types 16, 17 and 20

core/src/main/java/discord4j/core/object/entity/Message.java
**Description:** Adds message types 16, 17 and 20. 
I don't really know how to document this because I don't really know what it does...
**Justification:** https://github.com/discord/discord-api-docs/pull/1779
=> [3.2.x] Adds message types 16, 17 and 20

rest/src/main/java/discord4j/rest/util/Permission.java
**Description:** Adds user slash commands permissions.
**Justification:** https://github.com/discord/discord-api-docs/pull/2632/files
=> Add USE_SLASH_COMMANDS permissions

rest/src/main/java/discord4j/rest/route/Routes.java, rest/src/main/java/discord4j/rest/service/UserService.java, rest/src/test/java/discord4j/rest/service/UserServiceTest.java
**Description:** Removes `USER_DMS_GET` route. This endpoint returns an empty list and is now useless.
**Justification:** https://github.com/discord/discord-api-docs/pull/2770/files
=> Remove USER_DMS_GET

core/src/main/java/discord4j/core/object/entity/Message.java
**Description:** Apply `RestResource#getAllowedMentions` to message edit requests.
Discord API is a wonderful place where everything makes sense. 
https://github.com/discord/discord-api-docs/commit/1f6b82cf564aa34738d6e9f996275ee5c725bbb2
=> Apply RestResource#getAllowedMentions to message edit requests

core/src/main/java/discord4j/core/object/command/Interaction.java
Fixing incorrect channel type
If the interaction is called in DM, you can catch `ClassCastException` because `TextChannel` can't be assigned to `PrivateChannel`
=> Replace TextChannel to MessageChannel

core/src/main/java/discord4j/core/object/presence/ClientActivity.java, core/src/main/java/discord4j/core/object/presence/ClientPresence.java
Adds
- `ClientPresence.of(Status status, @Nullable ClientActivity activity)`
- `ClientActivity.of(Activity.Type type, String name, @Nullable String url)`
I also changed the common constructor for `ClientPresence` to always have `afk=false` and `since=0`. I tested every presence, and this works, but we might want some more confirmation that this is intended.
This allows for cleaner automatic construction (as opposed to hardcoded values which the other static factories serve perfectly).
=> Add low(er) level ClientPresence and ClientActivity factory methods

core/src/main/java/discord4j/core/object/audit/AuditLogChangeParser.java, core/src/main/java/discord4j/core/object/audit/AuditLogEntry.java, core/src/main/java/discord4j/core/object/audit/AuditLogPart.java, core/src/main/java/discord4j/core/object/audit/AuditLogRole.java, core/src/main/java/discord4j/core/object/audit/ChangeKey.java, core/src/main/java/discord4j/core/object/audit/OptionKey.java, core/src/main/java/discord4j/core/object/entity/Guild.java, core/src/main/java/discord4j/core/util/AuditLogUtil.java, core/src/test/java/discord4j/core/ExampleAuditLog.java, rest/src/main/java/discord4j/rest/util/PermissionSet.java
Fixes the parsing of audit log entries' `options` and `changes`. Thanks to @florianhartung for the initial work with `options` in #852.
In addition to parsing, this also addresses #428.
* Adds `AuditLogPart`, a "part" of the whole audit log which has all of the webhooks, users, and audit log entries returned by a single request to `/guilds/{guild.id}/audit-logs`. It has `getXById` methods which provide easier/faster access to the webhooks and users.
* Adds `AuditLogChangeParser`, a function `(AuditLogEntry, JsonNode) -> T` which parses the `JsonNode`. The `AuditLogEntry` is used to get the client `ObjectMapper` as well as the channel and guild ID for the overwrites parser. This is used by each instance of `ChangeKey`
* Adds a parsing function `String -> T` to each …
=> Fix audit log option and change parsing

common/src/main/java/discord4j/common/store/Store.java, common/src/main/java/discord4j/common/store/action/gateway/GatewayActions.java, common/src/main/java/discord4j/common/store/action/read/ReadActions.java, common/src/main/java/discord4j/common/store/legacy/LegacyStoreLayout.java, core/src/main/java/discord4j/core/event/dispatch/ChannelDispatchHandlers.java, core/src/main/java/discord4j/core/object/presence/Presence.java, gateway/src/main/java/discord4j/gateway/intent/IntentSet.java, gateway/src/main/java/discord4j/gateway/state/DispatchStoreLayer.java, rest/src/main/java/discord4j/rest/util/PermissionSet.java
Following up on quantic's comments [here](https://github.com/Discord4J/Discord4J/pull/875#pullrequestreview-622656074). Change/remove uses of `AssertionError`. Most were changed to `IllegalArgumentException`, but some were just removed without a change in behavior.
Semantically, `AssertionError` isn't the correct exception to use for most of these cases. This is especially true for the ones relating to Discord types where we get new ones all the time/with no warning.
Ultimately, this is really a nitpick with no real consequences, because Reactor won't handle these any differently, and no one should really be trying to handle these themselves anyways. 
Also note that if/when we upgrade to a more recent minimum java version, we can replace _some_ (not the …
=> Use better exception types than AssertionError

core/src/main/java/discord4j/core/object/reaction/ReactionEmoji.java
Adds `ReactionEmoji#unicodeCodepoints(String...)`, a convenience method for constructing a `ReactionEmoji` from Unicode codepoints using the "U+" notation. Also improves the docs for the existing `ReactionEmoji.unicode(String)` method, providing examples, and pointing to this new method for alternate inputs.
Confusion with the existing `ReactionEmoji.unicode(String)` method is common-enough, that I think this solution is worth trying.
Fixes #765
=> Add method for constructing ReactionEmoji from codepoints using "U+" notation

core/src/main/java/discord4j/core/event/domain/InteractionCreateEvent.java, rest/src/main/java/discord4j/rest/interaction/InteractionOperations.java, rest/src/main/java/discord4j/rest/interaction/InteractionResponse.java
**Description:** Removes `createFollowUp#wait` parameter because it will not be taken into account.
According to the documentation: `wait is always true`
https://discord.com/developers/docs/interactions/slash-commands#create-followup-message
=> Remove createFollowUp#wait parameter

core/src/main/java/discord4j/core/object/entity/Guild.java
**Description:** Adds a way to use `RestGuild#searchMembers` from Guild core object. This endpoint does not need the `GUILD_MEMBERS` intent to be enabled.
#888
https://github.com/Discord4J/Discord4J/issues/894
=> Adds Guild#searchMembers(String, int)

rest/src/main/java/discord4j/rest/util/ApplicationCommandOptionType.java
**Description:** Adds `ApplicationCommandOptionType#MENTIONABLE`. This is a draft because this option is not currently live, it is only available on canary API.
**Justification:** https://github.com/discord/discord-api-docs/pull/2853
=> Add ApplicationCommandOptionType#MENTIONABLE

core/src/main/java/discord4j/core/object/Invite.java, core/src/main/java/discord4j/core/object/entity/channel/PrivateChannel.java
- `PrivateChannel#getRecipients` returns `Set<User>` instead of `Flux<User>`
- `Invite#getInviter` returns `Optional<User>` instead of `Mono<User>`
- `Inviter#getTargetUser` returns `Optional<User>` instead of `Mono<User>`
**Justification:** There were already commits adressing the fact that UserData or MemberData are thrown away to just use the ID and request the full object to the gateway. This pull request aims to fix the last methods (that I could find) that do this. This is a breaking change without deprecation but I think it will be easier for users to manipulate Set and Optional rather than Flux and Mono.
=> Use UserData when possible

core/src/main/java/discord4j/core/object/presence/ClientPresence.java
When using the `ClientPresence` factory methods that don't accept a `ClientActivity`, build a `StatusUpdate` with `activities: []` instead of `activities: null`.
Sending null results in an invalid session. https://github.com/Discord4J/discord-json/pull/96 makes the field no longer nullable, but this PR is not blocked by that one. Fixes https://github.com/Discord4J/Discord4J/issues/932
=> Send empty activities array instead of null for status update

rest/src/main/java/discord4j/rest/request/DefaultRouter.java, rest/src/main/java/discord4j/rest/request/RequestStream.java, rest/src/main/java/discord4j/rest/request/ResponseHeaderStrategy.java
This adds a housekeeping mechanic for ratelimit buckets.
The `DefaultRouter` has a Map of `RequestStream` (ratelimit buckets) that only ever grows.
On a large enough bot, the map can take up several hundred MBs of memory after a few days.
We don't need to hold the ratelimit information in memory forever, once a bucket has no pending requests and is not ratelimited, we can safely get rid of it.
Implementation notes:
- housekeeping is done on the threads of the callers that send requests
- the first thread to send a request past a certain housekeeping period is assigned housekeeping duties
- both the housekeeping and the creation of new buckets take advantage of `ConcurrentHashMap#compute` to keep the changes to the map concurrent and thread-safe
I'm …
=> Evict stale `RequestStream`s to reduce memory usage over time

rest/src/main/java/discord4j/rest/request/DefaultRouter.java, rest/src/main/java/discord4j/rest/request/RequestStream.java
* When evicting a RequestStream, call a `.stop()` method that will trigger a callback terminating the underlying `RequestSubscriber`
* Fix race condition where the in-flight request counter could be zero when there could be actually one.
#924 introduces eviction of unused request streams, but when using it in my bot I came across an issue where an in-flight request would be stuck forever. After some testing I realized the `RequestSubscriber` subscription was still alive for evicted request streams, so each eviction-recreation would spawn a new subscription and would end up creating congestion / thread starvation on the scheduler, which explains why my requests ended up hanging.
=> Properly terminate RequestSubscriber when a RequestStream is evicted

core/src/main/java/discord4j/core/event/domain/InteractionCreateEvent.java, rest/src/main/java/discord4j/rest/interaction/InteractionOperations.java, rest/src/main/java/discord4j/rest/interaction/InteractionResponse.java
Adds the ability to send ephemeral followup messages for interactions.
#905 
This depends on https://github.com/Discord4J/discord-json/pull/85
=> Allow for ephemeral followup messages

core/src/main/java/discord4j/core/object/entity/Message.java
**Description:** Conserve order for `Message#getAttachments`.
**Justification:** Fix https://github.com/Discord4J/Discord4J/issues/928
=> Conserve order for Message#getAttachments

core/src/main/java/discord4j/core/object/Region.java, core/src/main/java/discord4j/core/object/entity/Guild.java, core/src/main/java/discord4j/core/object/entity/channel/VoiceChannel.java, core/src/main/java/discord4j/core/spec/GuildCreateSpec.java, core/src/main/java/discord4j/core/spec/GuildEditSpec.java
- Some regions are marked as `deprecated` by Discord, should they be included in the enum?
- Is it ok to return `null` for `UNKNOWN` enum?
- The solution does not seem really future proof, if Discord releases a new region, we will have to update the enum. Maybe we can change the `setRegion` to take a String instead? But it will probably be confusing.
- `rtc_region` can be  empty when set to `automatic`, is it ok to return an empty mono in this case for `public Mono<Region> getRegion()`?
- Should these change be ported to `3.1.x`?
**Justification:** Fix https://github.com/Discord4J/Discord4J/issues/910
=> Improve Region usage in specs

core/src/main/java/discord4j/core/spec/MessageCreateSpec.java, core/src/main/java/discord4j/core/spec/MessageEditSpec.java, gradle.properties
* Deprecates `MessageCreateSpec#setEmbed(Consumer)`
* Adds `MessageCreateSpec#addEmbed(Consumer)`
* Deprecates `MessageEditSpec#setEmbed(Consumer)`
* Adds `MessageEditSpec#addEmbed(Consumer)`
The docs of for carefully explain its potentially-counter-intuitive behavior.
* Adds `MessageEditSpec#removeEmbeds()`
This is an alternative to `setEmbed(null)`.
I'm not entirely satisfied with the naming/behavior of `MessageEditSpec#addEmbed(Consumer)` or the existence of `MessageEditSpec#removeEmbeds()`, but I don't think it's worth trying to improve with new specs coming soon.
Depends on https://github.com/Discord4J/discord-json/pull/99
https://github.com/discord/discord-api-docs/pull/3105
=> Add support for multiple embeds in a message

core/src/main/java/discord4j/core/spec/MessageEditSpec.java, gradle.properties
Add `MessageEditSpec#setComponents()` to support editing components in messages outside of an interaction callback.
Depends on https://github.com/Discord4J/discord-json/pull/100
Missing feature.
=> Add MessageEditSpec#setComponents()

core/src/main/java/discord4j/core/event/domain/interaction/ComponentInteractEvent.java
Add `ComponentInteractEvent#getMessage()`.
This is a convenience method like those in `SlashCommandEvent` which simply unwraps an `Optional` that should always be present. In this case, `Interaction#getMessage()` is always present for component interactions.
User convenience.
=> Add ComponentInteractEvent#getMessage()

core/src/main/java/discord4j/core/object/Region.java
Add nullability annotations for the value in the Region enum.
The `UNKNOWN` and `AUTOMATIC` regions have a null value.
=> Region value can be null

core/src/main/java/discord4j/core/spec/MessageCreateSpecGenerator.java, core/src/main/java/discord4j/core/spec/MessageEditSpecGenerator.java
**Description:** Add components field to the new MessageCreateSpec and MessageEditSpec
**Justification:** They are only present in legacy specs currently
=> Add missing components field to new specs

core/src/main/java/discord4j/core/spec/InteractionApplicationCommandCallbackSpecGenerator.java, core/src/main/java/discord4j/core/spec/WebhookExecuteSpecGenerator.java
Description: Add components field to the new `WebhookExecuteRequestSpec`
Justification: Components field is present on WebhookExecuteRequest, but not on the new spec.
=> Add missing components field to WebhookExecuteSpec

core/src/main/java/discord4j/core/event/domain/interaction/ComponentInteractEvent.java, core/src/main/java/discord4j/core/object/command/Interaction.java, gradle.properties
Makes `Interaction#getMessage()` filter out ephemeral messages, because Discord doesn't send a full message object. This also means `ComponentInteractEvent#getMessage()` is now `Optional`. `getMessageId()` has been added to both, and is always present for component interactions.
Fixes #963
Depends on https://github.com/Discord4J/discord-json/pull/101
=> Deserialize interaction message on demand

gateway/src/main/java/discord4j/gateway/json/dispatch/EventNames.java, gateway/src/main/java/discord4j/gateway/json/jackson/PayloadDeserializer.java
Closes #967
**Description:** Add the "GUILD_JOIN_REQUEST_DELETE" event to explicitly ignored events
**Justification:** As mentionned on #967, "has existed for a while, but Discord hasn't documented it"
=> Added GUILD_JOIN_REQUEST_DELETE event to explicitly ignored events

core/src/main/java/discord4j/core/spec/TextChannelCreateSpecGenerator.java
Description: Changes channel type in TextChannelCreateSpecGenerator.java from news to text
Justification: Fixes issue #969
=> fix channel type in text channel request builder

core/src/main/java/discord4j/core/object/command/ApplicationCommandInteractionOptionValue.java, core/src/main/java/discord4j/core/object/command/ApplicationCommandOptionChoice.java, rest/src/main/java/discord4j/rest/util/ApplicationCommandOptionType.java
**Description:** Adds `ApplicationCommandOptionType#NUMBER`, `ApplicationCommandInteractionOptionValue#asDouble()` and `ApplicationCommandOptionChoice#asDouble()` to support floating point numbers as an option for Slash Commands.
**Justification:** https://github.com/discord/discord-api-docs/pull/3455
=> Add ApplicationCommandOptionType#NUMBER, ApplicationCommandInteractionOptionValue#asDouble() and ApplicationCommandOptionChoice#asDouble()

rest/src/main/java/discord4j/rest/interaction/Interactions.java
Fix some `equals` checks in `Interactions.java`
At the moment the equals checks are broken (comparing `Possible<String>` to `String`) so registered slash commands do not get invoked, as they are not found.
=> Fix interaction matching

core/src/main/java/discord4j/core/object/component/SelectMenu.java
**Description:** Fixes an incorrect method return value
**Justification:** Method `#getPlaceholder` returns select menu's `customId` instead of `placeholder`
=> Fix SelectMenu#getPlaceholder return value

core/src/main/java/discord4j/core/event/domain/interaction/InteractionCreateEvent.java, rest/src/main/java/discord4j/rest/interaction/InteractionOperations.java, rest/src/main/java/discord4j/rest/interaction/InteractionResponse.java, rest/src/main/java/discord4j/rest/route/Routes.java, rest/src/main/java/discord4j/rest/service/WebhookService.java
**Description:** Adds the [Get Webhook Message](https://discord.com/developers/docs/resources/webhook#get-webhook-message) route, which is used to [get the initial response](https://discord.com/developers/docs/interactions/receiving-and-responding#get-original-interaction-response) for interactions. 
**Justification:** This is necessary to filter for component interactions that occurred on slash command responses, for instance, responding to a button press on a slash command response.
Sorry about opening two PR's, I didn't know that I was supposed to target the oldest relevant branch.
=> Add 'Get Original Interaction Response' endpoint

core/src/main/java/discord4j/core/event/domain/interaction/ComponentInteractEvent.java, core/src/main/java/discord4j/core/event/domain/interaction/InteractionCreateEvent.java, core/src/main/java/discord4j/core/spec/InteractionApplicationCommandCallbackSpecGenerator.java
Previously, `InteractionApplicationCommandCallbackMono` always used `InteractionCreateEvent#reply` when subscribed to. This meant that `ComponentInteractEvent#edit()` (which returned `InteractionApplicationCommandCallbackMono`) would actually reply to the interaction (use `CHANNEL_MESSAGE_WITH_SOURCE`) instead of editing (use `UPDATE_MESSAGE`). 
This PR solves this by
* Renaming `InteractionApplicationCommandCallbackMono` to `InteractionApplicationCommandCallbackReplyMono`
* Adding `InteractionApplicationCommandCallbackEditMono`
Fixes #987
=> Fix component interaction edit being sent as reply

core/src/main/java/discord4j/core/object/command/ApplicationCommandInteraction.java, core/src/main/java/discord4j/core/object/command/ApplicationCommandInteractionResolved.java, core/src/main/java/discord4j/core/object/command/ResolvedChannel.java, core/src/main/java/discord4j/core/object/command/ResolvedMember.java
**Description:** Add `ApplicationCommandInteraction::getResolved` so we can access the users, channels and roles that are resolved by Discord from the user input when receiving a command interaction
**Justification:** `ApplicationCommandInteractionData::resolved` currently does not have an equivalent in d4j-core. The only way to get a channel, role or user from a command option value is to use the getters available in `ApplicationCommandInteractionOptionValue`, but those return a `Mono`, however by accessing the `resolved` field we can access those values without having to make additional requests.
=> Add ApplicationCommandInteraction::getResolved

core/src/main/java/discord4j/core/event/domain/interaction/ComponentInteractionEvent.java, core/src/main/java/discord4j/core/event/domain/interaction/InteractionCreateEvent.java, core/src/main/java/discord4j/core/object/entity/Message.java, core/src/main/java/discord4j/core/object/entity/channel/MessageChannel.java
**Description:** Fixes #1014 
**Justification:** Global allowed mentions always overrides spec's setting.
=> Fix global allowed mentions behavior with new specs

core/src/main/java/discord4j/core/util/EntityUtil.java
**Description:** Adds missed switch branches to `#getChannel` factory method.
**Justification:** If send message in the channel thread throws `java.lang.UnsupportedOperationException` exception.
=> Add missed channel thread types to #getChannel

common/src/main/java/discord4j/common/store/impl/LocalStoreLayout.java, common/src/main/java/discord4j/common/store/impl/WrappedGuildData.java
**Description:** Fix a performance issue in the store implementation that was caused by adding elements to large immutable list. It was more specifically affecting member list for large guilds.
**Justification:** store updates should run in constant time, especially since they are currently running on the same thread where gateway dispatches are emitted.
**Note:** this PR doesn't fix the requestMembers() never completing when a gateway error is received while processing chunks, that's a separate issue.
=> Fix performance issue when adding list elements to cached guilds

common/src/main/java/discord4j/common/store/impl/LocalStoreLayout.java
**Description:** Fixes message id usage as user cache key
**Justification:** On message create events, the user cache is constantly replenished with new identical users, since the message id is used as key
=> Fix message id usage as user cache key

core/src/main/java/discord4j/core/object/entity/Message.java
**Description:** This PR add Missings Flags (HAS_THREAD) and Types (THREAD_CREATED,THREAD_STARTER_MESSAGE and CONTEXT_MENU_COMMAND)
**Justification:** N/A
**Others:** This PR is for 3.2.x but this version is only for API v8 then dont know if need include THREAD_STARTER_MESSAGE because this only work in the v9 API (3.3.x)
=> Add Missing Flags and Types of Message

rest/src/main/java/discord4j/rest/entity/RestChannel.java, rest/src/main/java/discord4j/rest/entity/RestEmoji.java, rest/src/main/java/discord4j/rest/entity/RestGuild.java, rest/src/main/java/discord4j/rest/entity/RestGuildTemplate.java, rest/src/main/java/discord4j/rest/entity/RestInvite.java, rest/src/main/java/discord4j/rest/entity/RestMember.java, rest/src/main/java/discord4j/rest/entity/RestMessage.java, rest/src/main/java/discord4j/rest/entity/RestRole.java, rest/src/main/java/discord4j/rest/entity/RestUser.java, rest/src/main/java/discord4j/rest/entity/RestWebhook.java
Add equals and hashCode to rest entities. 
Instead of using 
`if (restMessage1.getId().equals(restMessage2.getId()))`
one can use 
`if (restMessage1.equals(restMessage2))` 
now!
=> Add equals and hashcode to rest entities

core/src/main/java/discord4j/core/object/audit/ChangeKey.java, core/src/main/java/discord4j/core/object/entity/Sticker.java
**Description:** This PR adds a few missing ChangeKey for AuditLog, the ChangeKey related to Scheduled Events are not added here because already are in https://github.com/Discord4J/Discord4J/pull/1046
**Justification:** https://discord.com/developers/docs/resources/audit-log#audit-log-change-object-audit-log-change-key
=> Add missing ChangeKey for AuditLog

core/src/main/java/discord4j/core/object/entity/User.java
Fixed an reference error for getBannerUrl with no parameter returning the user avatar url instead of banner url.
The changed corrects the getBannerUrl() to return the same url as getBannerUrl(Image.Format) instead o the user avatar as getUserAvatar() would also return the same url.
=> fixed wrong reference for User.getBannerUrl() method

core/src/main/java/discord4j/core/object/entity/Integration.java
**Description:** This PR use the optional return based in another PR in discord-json for enabled field in Integration for AuditLogs, the only case where is field not show is for bots added... then by logic the default return can be true?
**Justification:** https://github.com/Discord4J/discord-json/pull/119
=> Update Integration#isEnabled for Optional data.

core/src/main/java/discord4j/core/util/AuditLogUtil.java
**Description:** Fixed an incorrect key in `AuditLogUtil#createOptionMap()` for `OptionKey#MESSAGE_ID`
=> Fix audit log `messageId` option

core/src/main/java/discord4j/core/object/command/ApplicationCommand.java, core/src/main/java/discord4j/core/object/command/ApplicationCommandInteraction.java, core/src/main/java/discord4j/core/object/command/ApplicationCommandInteractionOption.java, core/src/main/java/discord4j/core/object/command/ApplicationCommandInteractionResolved.java, core/src/main/java/discord4j/core/object/command/ApplicationCommandOption.java
**Description:** Replace current variants of the `getX(id/name)` methods in application commands objects to faster and creating less garbage
**Justification:** Current implementations recollect lists and maps which is often redundant, especially in `ApplicationCommandInteractionResolved`
=> Change implemenetations of `getX(id/name)` methods in application commands objects

core/src/main/java/discord4j/core/object/ExtendedInvite.java
…bership attribute
Fixed ExtendedInvite.getExpiration() falsely depending on the temporary membership flag on the invite.
It seems that the temporary keyword has been misinterpreted.
https://discord.com/developers/docs/resources/invite#invite-metadata-object-invite-metadata-structure
`
Invite Metadata Structure
[...]
temporary | boolean | whether this invite only grants temporary membership`
=> fixed ExtendedInvite.getExpiration falsely depending on temporary membership

rest/src/main/java/discord4j/rest/util/Permission.java
**Description:** Fixes issues in Permission enum:
* Wrong value for USE_EXTERNAL_STICKERS
* Wrong name for USE_SLASH_COMMANDS instead of USE_APPLICATION_COMMANDS in official doc
* Missing enum constants: MANAGE_EVENTS, MANAGE_THREADS, SEND_MESSAGES_IN_THREADS and USE_EMBEDDED_ACTIVITIES (MANAGE_THREADS exists in 3.3.x)
* Missing enum constants: CREATE_PUBLIC_THREADS and CREATE_PRIVATE_THREADS, they exist in 3.3.x, but have wrong names (USE_PUBLIC_THREADS and USE_PRIVATE_THREADS)
* Bad location of USE_EXTERNAL_STICKERS enum constant, according to value numerical order.
**Justification:** The relevant issue is here: https://github.com/Discord4J/Discord4J/issues/1098
=> Fix Permission enum according to official discord doc

core/src/main/java/discord4j/core/event/dispatch/DispatchHandlers.java, core/src/main/java/discord4j/core/event/domain/interaction/SelectMenuInteractionEvent.java, core/src/main/java/discord4j/core/object/component/MessageComponent.java, core/src/main/java/discord4j/core/object/component/SelectMenu.java, core/src/test/java/discord4j/core/ExampleSelectMenu.java
**Description:** Add new factory methods for role, user and other types of select menu components.
Since now `MessageComponent.Type.SELECT_MENU` is not the only one, it's maybe better to rename it to `SELECT_MENU_TEXT`
Depends on https://github.com/Discord4J/discord-json/pull/129
**Justification:** https://discord.com/developers/docs/change-log#new-select-menu-components
=> Add support for new select menu components

core/src/main/java/discord4j/core/event/ReactiveEventAdapter.java, core/src/main/java/discord4j/core/event/dispatch/DispatchHandlers.java, core/src/main/java/discord4j/core/event/domain/AuditLogEntryCreateEvent.java, core/src/main/java/discord4j/core/object/audit/AuditLogEntry.java, gateway/src/main/java/discord4j/gateway/intent/Intent.java, gateway/src/main/java/discord4j/gateway/json/dispatch/EventNames.java, gateway/src/main/java/discord4j/gateway/json/jackson/PayloadDeserializer.java
This resolve #1112 
- Implement a new event for AuditLog Entry created 
- Make Nullable the getParent of the EntryAuditLog because the event use this object but with not parent
- Add the new intent GUILD_MODERATION and deprecate the old GUILD_BANS for the rename in intent docs
**Justification:** https://github.com/discord/discord-api-docs/pull/5849
**Needs of:** https://github.com/Discord4J/discord-json/pull/132
=> Implement AuditLogEntryCreateEvent

gateway/src/main/java/discord4j/gateway/intent/Intent.java
The Intents enum is out of date. The following changes have been made:
- Some javadocs were modified to reference additional gateway events.
- `GUILD_EMOJIS` is now `GUILD_EMOJIS_AND_STICKERS`, so `GUILD_EMOJIS` was marked as `@Deprecated` to preserve backwards compatibility, and `GUILD_EMOJIS_AND_STICKERS` was added with the same shift count.
- The following new values were added:
- `MESSAGE_CONTENT(15)`
- `GUILD_SCHEDULED_EVENTS(16)`
- `AUTO_MODERATION_CONFIGURATION(20)`
- `AUTO_MODERATION_EXECUTION(21)`
To match the current set of Intents described here: https://discord.com/developers/docs/topics/gateway#list-of-intents
=> Update javadocs, and add missing Intents

build.gradle
**Description:** This set all URL in docs to https for remove a minor warning
=> Fix insecure url docs in build.gradle

core/src/main/java/discord4j/core/event/dispatch/ApplicationCommandDispatchHandlers.java, core/src/main/java/discord4j/core/event/dispatch/DispatchHandlers.java, core/src/main/java/discord4j/core/event/domain/command/ApplicationCommandPermissionUpdateEvent.java, core/src/main/java/discord4j/core/object/command/ApplicationCommandGuildPermissions.java, core/src/main/java/discord4j/core/object/command/ApplicationCommandPermission.java, core/src/test/java/discord4j/core/ExampleSoundboard.java, gateway/src/main/java/discord4j/gateway/json/dispatch/EventNames.java, gateway/src/main/java/discord4j/gateway/json/jackson/PayloadDeserializer.java
Supersedes #1117 from @dominoxp , I was unable to commit changes to it.
--
Requires Pull Request in discord-json: https://github.com/Discord4J/discord-json/pull/136
Added Missing Event handling from Command Permission Update Event Data
https://discord.com/developers/docs/topics/gateway-events#application-commands
https://discord.com/developers/docs/interactions/application-commands#application-command-permissions-object-guild-application-command-permissions-structure
=> Add Discord Application Command Permissions Update Event

core/src/main/java/discord4j/core/object/entity/GuildEmoji.java, core/src/main/java/discord4j/core/object/reaction/ReactionEmoji.java
**Description/Justification:** This pull request does two things:
- promotes the `ReactionEmoji.Custom#asFormat` method to `ReactionEmoji` to simplify converting a `ReactionEmoji` to a `String` displayable in the client
- standardizes the creation of a displayable `String` for custom emoji across `GuildEmoji` and `ReactionEmoji.Custom` to reduce duplication
=> Promote and standardize the creation of displayable strings for emoji

common/src/main/java/discord4j/common/store/action/read/GetAutoModRuleByIdAction.java
This PR fixes tiny error about the name of a field in `GetAutoModRuleByIdAction`.
The field has been renamed from `stickerId` to `autoModRuleId`.
I suspect this typo comes from a copy-paste from the [`GetStickerByIdAction`](https://github.com/Discord4J/Discord4J/blob/3.2.x/common/src/main/java/discord4j/common/store/action/read/GetStickerByIdAction.java) file and the author forgot to change it. The name I put comes from it's usage [here](https://github.com/Discord4J/Discord4J/blob/3.2.x/common/src/main/java/discord4j/common/store/action/read/ReadActions.java#L276):
```java
public static GetAutoModRuleByIdAction getAutoModRuleById(long guildId, long autoModRuleId) {
return new GetAutoModRuleByIdAction(guildId, autoModRuleId);
}
```
=> Fix wrong variable name in GetAutoModRuleByIdAction

core/src/main/java/discord4j/core/event/domain/automod/AutoModActionExecutedEvent.java
**Description:** This pull request fixes the `getMessageId`, `getMessage`, and `getSystemMessageId` accessors.
**Justification:** `getMessageId` and `getSystemMessageId` returned an incorrect value (the channel id), while `getMessage` used an incorrect operator when checking if a `Message` is retrievable.
=> fix(core): return proper values in `AutoModActionExecutedEvent` accessors

core/src/main/java/discord4j/core/spec/BanQuerySpecGenerator.java
**Description:** Support `delete_message_seconds`, and deprecate `delete_message_days`.
**Justification:** https://discord.com/developers/docs/resources/guild#create-guild-ban
=> feat(core): support delete_message_seconds in guild bans

core/src/main/java/discord4j/core/spec/EmbedCreateSpecGenerator.java, core/src/main/java/discord4j/core/spec/InternalSpecUtils.java
**Description:** Introduces a method to allow populating a ´EmbedCreateSpec.Builder´ from an existing `EmbedData`.
**Justification:** Restores functionality originally introduced in #868 but lost in #927.
=> feat(core): allow populating EmbedCreateSpec$Builder from existing EmbedData

.github/workflows/gradle.yml
**Description:** This PR aims to make a few improvements to the current workflow and close #1056
The changes in the workflow are...
- If the PR has the label 'PR depends on PR' the workflow are skipped because in the most of cases the PR cannot be builded until another necesary PR is merged
- If the repository not has the secrets for publish then this job is skipped, currently in any fork when a push event is handled (like a sync of master) the workflow try to publish
- Update dependencies of actions most of then has deprecation messages for any build based in a few changes by github
This workflow maybe can be improvement a few more but currently works :3
=> [ci skip] Improvement of Workflow

core/src/main/java/discord4j/core/object/entity/Message.java, rest/src/main/java/discord4j/rest/route/Routes.java, rest/src/main/java/discord4j/rest/service/ChannelService.java
Closes #1045 
The `Route` for `suppress-embeds` has been marked as `@Deprecated`, as well as the methods that use it.
This satisfies the concerns outlined in #1045 for 3.2.x. I will also submit a PR that removes these references targeted for 3.3.x.
=> Mark the suppress-embeds Route as deprecated, along with all of its usages.

core/src/main/java/discord4j/core/object/automod/AutoModRuleTriggerMetaData.java, core/src/main/java/discord4j/core/object/entity/Guild.java, core/src/main/java/discord4j/core/spec/GuildEditSpecGenerator.java, gradle.properties
**Description:** Implement the alert channel defined in guild for notice safety things by discord, also this PR include a new field for automod metadata related to raid mention protection.
**Justification:** https://github.com/discord/discord-api-docs/commit/7467461237468e01f79ec2d88bcb8b77a024ea34
**Depends:** https://github.com/Discord4J/discord-json/pull/148
=> Implement fields for raid mention and safety alerts

gateway/src/main/java/discord4j/gateway/DefaultGatewayClient.java, rest/src/main/java/discord4j/rest/http/client/DiscordWebClient.java, voice/src/main/java/discord4j/voice/DefaultVoiceGatewayClient.java
**Description:** Inserts a missing space in the `User-Agent` header sent to Discord.
**Justification:** As per https://discord.com/developers/docs/reference#http-api, a `User-Agent` header must be provided following a specific format. This works as is, luckily, but Discord4J should follow the exact format provided by Discord.
=> follow the specified user-agent format exactly

common/src/main/java/discord4j/common/retry/ReconnectContext.java, rest/src/main/java/discord4j/rest/http/client/ClientException.java, rest/src/main/java/discord4j/rest/request/RequestStream.java, rest/src/main/java/discord4j/rest/response/ResponseFunction.java, rest/src/main/java/discord4j/rest/response/RetryingTransformer.java, rest/src/test/java/discord4j/rest/request/ClockGlobalRateLimiter.java
**Description:** I tried to migrate from the old reactor Retry<?> interface to the abstract class reactor.util.retry.Retry and its two subclasses RetrySpec and RetryBackoffSpec.
I tried to refactor only, but it seems we have 2 functionnal changes that I'm going to describe in review below for feedback. 
**Justification:** This PR fixes the issue #1125
=> Migration to reactor.util.retry.Retry after old retry deprecation (#1125)

common/src/main/java/discord4j/common/store/selective/SelectiveDataAccessor.java, common/src/main/java/discord4j/common/store/selective/SelectiveGatewayDataUpdater.java, common/src/main/java/discord4j/common/store/selective/SelectiveStoreLayout.java, common/src/main/java/discord4j/common/store/selective/StoreFlag.java, common/src/main/java/discord4j/common/store/selective/package-info.java
Add a decorator for the new Store API that conveniently allows users to select which entities should be served by a store.
I found this useful in my own implementation of the new Store API. Given that it is fairly generic and a bit of an annoyance to type it all down, I think having such a Store decorator in the lib itself might be of value to other devs.
=> Add selective store decorator

core/src/main/java/discord4j/core/object/entity/channel/CategorizableChannel.java, core/src/main/java/discord4j/core/object/entity/channel/TextChannel.java, core/src/main/java/discord4j/core/object/entity/channel/ThreadChannel.java, core/src/main/java/discord4j/core/object/entity/channel/TopLevelGuildMessageChannel.java, core/src/main/java/discord4j/core/spec/NewsChannelCreateSpecGenerator.java, core/src/main/java/discord4j/core/spec/NewsChannelEditSpecGenerator.java, core/src/main/java/discord4j/core/spec/StageChannelCreateSpecGenerator.java, core/src/main/java/discord4j/core/spec/StageChannelEditSpecGenerator.java, core/src/main/java/discord4j/core/spec/VoiceChannelCreateSpecGenerator.java, core/src/main/java/discord4j/core/spec/VoiceChannelEditSpecGenerator.java, core/src/main/java/discord4j/core/spec/legacy/LegacyTextChannelCreateSpec.java
**Description:** Based in a previous issue all guild channel with messages allow set a rate limit per user in messages send, this currently in code are only for normal messages, things like news channel or voice channel dont allow this, this PR allow get the value and also set also update the docs to reflect the new max value allowed by docs.
**Justification:** This close https://github.com/Discord4J/Discord4J/issues/1111
**Note:** the structure of channel classes is a little mess for me.. then i hope move the method to the correct place.
=> Support rateLimitPerUser for every Guild Message Channel type

.github/workflows/gradle.yml, rest/src/main/java/discord4j/rest/request/DefaultRouter.java, rest/src/main/java/discord4j/rest/request/RequestCorrelation.java, rest/src/main/java/discord4j/rest/request/RequestStream.java, rest/src/test/java/discord4j/rest/http/WebClientTest.java
**Description:** If a user cancels a request under rate-limit, it is propagated to the RequestStream subscription and avoids running extra requests.
**Justification:** Cancelling an API request under rate-limit should not hit the API after it completes.
=> Propagate request cancellation to HttpClient

core/src/main/java/discord4j/core/object/entity/Attachment.java
**Description:** Adds missing fields on attachments.
https://github.com/discord/discord-api-docs/pull/6082 & https://github.com/discord/discord-api-docs/pull/6272
Requires https://github.com/Discord4J/discord-json/pull/152 to be merged
=> Added missing methods getDurationSeconds, getWaveform and getFlags for Attachment

core/src/main/java/discord4j/core/event/dispatch/MessageDispatchHandlers.java, core/src/main/java/discord4j/core/event/domain/message/ReactionAddEvent.java
**Description:** Add the method getMessageAuthorId on the ReactionAddEvent class
**Justification:** https://github.com/discord/discord-api-docs/pull/6102
Requires https://github.com/Discord4J/discord-json/pull/153 to be merged
=> feat: add ReactionAddEvent#getMessageAuthorId method

core/src/main/java/discord4j/core/object/entity/channel/ThreadChannel.java
**Description:** Fix wrong cast target when fetching a Thread channel parent. This change implies a breaking change from previous development version, as `ThreadChannel#getParent` methods will now return a `Mono<TopLevelGuildChannel>` instead of a `Mono<TopLevelGuildMessageChannel>`.
**Justification:** Issue #1173 
**Quick test:** Here is a snapshot usable for this fix, use this Gradle DSL :
```Gradle
repositories {
mavenCentral()
maven { url("https://nexus.klutometis.net/repository/maven-public") }
}
dependencies {
testImplementation(platform("org.junit:junit-bom:5.9.1"))
testImplementation("org.junit.jupiter:junit-jupiter")
implementation("com.discord4j:discord4j-core:3.3.0-FIX-1173-SNAPSHOT")
}
```
I tested it using the same code as in #1173 and this is working well :
```
> Task …
```
=> Fix ThreadChannel#getParent causing ClassCastException when parent channel is a forum channel

core/src/main/java/discord4j/core/object/command/ResolvedChannel.java, core/src/main/java/discord4j/core/object/command/ResolvedMember.java
**Description:** This PR (which requires https://github.com/Discord4J/discord-json/pull/161 to be merged and released) is a fix of resolved objects in application command interactions.
The commit adapts https://github.com/Discord4J/discord-json/pull/161 and edits the ResolvedChannel and ResolvedMember objects to include missing fields and adapt tha mandatory fields.
**Justification:** #1171 and see https://github.com/Discord4J/discord-json/pull/161 for other changes
**Changelog notes**:
- Updates discord-json to `1.7.8`
- `ResolvedChannel#getName` now returns an `Optional<String>` instead of a `String`
- `ResolvedChannel#getPermissions` now returns an `Optional<PermissionSet>` instead of a `PermissionSet`
- `ResolvedChannel` now supports `getThreadMetadata` and `getParentId` methods if …
=> Fix Jackson parsing in application commands when channels are DM channels

core/src/main/java/discord4j/core/object/ApplicationTeamMember.java
**Description:** Implement the roles for team members. this PR ignore the "OWNER" role based in this role are never used because for know the owner you need check another field in the team.
=> Implement TeamMemberRole for Teams

rest/src/main/java/discord4j/rest/util/Permission.java
**Description:** Handle 2 new permission derivated from another to expresions and events
**Justification:** https://github.com/discord/discord-api-docs/commit/ff5e9d56f83fb2fb6d5183629bcd79461d2d24fc
=> Permission split for expressions and events

core/src/main/java/discord4j/core/event/dispatch/ThreadDispatchHandlers.java, core/src/main/java/discord4j/core/event/domain/thread/ThreadChannelCreateEvent.java
**Description:** This PR pass the field newly_created to the ThreadChannelCreateEvent for allow users know if the thread was created or not.
NOTE: This require another PR for the other case because can get a threadmember...
**Justification:** https://canary.discord.com/channels/208023865127862272/451125724766535710/1239362437690425385
=> Add ThreadChannelCreateEvent#NewlyCreated

README.md, core/src/main/java/discord4j/core/object/entity/Message.java
**Description:** Throw an UnsupportedOperationException when calling `Message#getContent` without the `MESSAGE_CONTENT` intent enabled.
**Justification:** Currently, this just returns an empty string, which users don't understand and might complain about it being a bug. This exception provides a detailed message, redirecting the user to this project's README, where a section has been added to address this issue.
=> feat: throw exception when trying to access message content without MESSAGE_CONTENT intent

common/build.gradle
**Description:** Change scope of com.discord4j:stores-api from implementation to api.
**Justification:** Fix #1200 according to [gradle official doc](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_recognizing_dependencies).
=> Change scope of com.discord4j:stores-api from implementation to api.

core/src/main/java/discord4j/core/object/entity/Guild.java
**Description:** Close #1194 adding a utility enum for the resource navigation.
**Justification:** https://discord.com/developers/docs/reference#message-formatting-guild-navigation-types
=> Support for the Guild Resource Navigation

rest/src/main/java/discord4j/rest/route/Routes.java, rest/src/main/java/discord4j/rest/service/StickerService.java
**Description:** This PR solves the issue #1192  by renaming the package into STICKER_PACKS_GET since a nitro subscription is not needed anymore. The Docu was adjusted accordingly
**Justification:** PR solves the issue #1192
note: old PR #1218 was closed since rebase did not work as expected
=> refactor: adjusted naming of NITRO_STICKER_PACKS_GET 

core/src/main/java/discord4j/core/object/entity/Message.java
**Description:** This PR add missing messages types and also include the field in docs for define if that type is deletable or not.
**Justification:** Changes in https://discord.com/developers/docs/resources/channel#message-object-message-types
- https://github.com/discord/discord-api-docs/commit/174c1a18933e068d70d56c2340b9936eed8b366a
- https://github.com/discord/discord-api-docs/commit/e5cd463cd1412df2e55fce8ecb81e7d1ed5755b0
=> Add news Message.Type for INCIDENT/PURCHASE and include if are deletable

core/src/main/java/discord4j/core/event/domain/interaction/ChatInputInteractionEvent.java
**Description:** Add shortcut methods to the `ChatInputInteractionEvent` class to retrieve option values easily.
**Justification:** Many users write such methods to get the values; an implementation directly in D4J can benefit everyone.
**Additions:**
- `Optional<String> getOptionAsString(final String name)`
- `Optional<Boolean> getOptionAsBoolean(final String name)`
- `Optional<Long> getOptionAsLong(final String name)`
- `Optional<Double> getOptionAsDouble(final String name)`
- `Optional<Snowflake> getOptionAsSnowflake(final String name)`
- `Optional<Attachment> getOptionAsAttachment(final String name)`
- `Mono<User> getOptionAsUser(final String name)`
- `Mono<Role> getOptionAsRole(final String name)`
- `Mono<Channel> getOptionAsChannel(final String name)`
=> feat: add shortcut methods for ChatInputInteractionEvent to get option values

build.gradle, core/build.gradle, core/src/main/java/discord4j/core/spec/SpecStyle.java, core/src/main/java/discord4j/core/spec/package-info.java, gradle.properties
---
:warning: **This PR depends on https://github.com/Discord4J/discord-json/pull/172 and assumes that the `1.6.20` version is already tagged and published to Maven Central.**
---
Updates the import of `@MetaEncodingEnabled` in the `package-info.java` of immutable specs, after updating to discord-json 1.6.20
The discord-json encoding module was completely unusable in a project declaring a `module-info.java` requiring the encoding module because of a package name clash. The package has been moved in the PR linked above to address this.
=> Migrate to discord-json encoding 1.6.20

core/src/main/java/discord4j/core/object/entity/Message.java, core/src/main/java/discord4j/core/object/entity/channel/ForumChannel.java, core/src/main/java/discord4j/core/object/entity/channel/NewsChannel.java, core/src/main/java/discord4j/core/object/entity/channel/TextChannel.java, core/src/main/java/discord4j/core/object/entity/channel/ThreadChannel.java, core/src/main/java/discord4j/core/object/entity/channel/TopLevelGuildMessageChannel.java, core/src/main/java/discord4j/core/object/entity/channel/TopLevelGuildMessageWithThreadsChannel.java, core/src/main/java/discord4j/core/object/entity/channel/VoiceChannel.java, core/src/main/java/discord4j/core/spec/StartThreadFromMessageSpecGenerator.java, core/src/main/java/discord4j/core/spec/StartThreadWithoutMessageSpecGenerator.java, core/src/main/java/discord4j/core/spec/ThreadChannelEditSpecGenerator.java, core/src/test/java/discord4j/core/ExampleThread.java, rest/src/main/java/discord4j/rest/entity/RestChannel.java, rest/src/main/java/discord4j/rest/service/ChannelService.java, rest/src/main/java/discord4j/rest/util/PaginationUtil.java
Closes #1223 
- Add missing `flags` and `appliedTags` methods to `ThreadChannelEditSpec` and `ThreadChannelEditMono`
- Created a new interface, `TopLevelGuildMessageWithThreadsChannel` that extends `TopLevelGuildMessageChannel`, used for `TextChannel` and `NewsChannel`. This interface represents text channels that can have threads (A `VoiceChannel` is also a `TopLevelGuildMessageChannel` but cannot have threads). This interface has the following methods:
- `Flux<ThreadChannel> getAllThreads()`
- `Flux<ThreadChannel> getPublicArchivedThreads()`
- `Mono<ThreadChannel> startPublicThreadWithoutMessage(StartThreadWithoutMessageSpec spec)`
- `Mono<ThreadChannel> startPublicThreadWithMessage(Message message, StartThreadFromMessageSpec spec)`
- `StartThreadWithoutMessageMono …
=> feat: improvements on threads and forums

.github/workflows/check_pr.yml
**Description:** This PR try to add a workflow to check Pull Request and avoid the use of release branchs
**Justification:** The use of this branchs make difficult for maintenance of the PR in case of rebase
=> Implement Pull Request check for avoid the use of release branches

core/src/main/java/discord4j/core/object/reaction/ReactionEmoji.java
**Description:** This fixs a issue where try to parse a EmojiData can throw an exception if the name is null, the current behaviour for throw a exception cause issues in https://github.com/Discord4J/Discord4J/pull/1231 where the emoji in prompts can contain null names.
**Justification:** https://discord.com/developers/docs/resources/emoji#emoji-object-emoji-structure
=> Fix ReactionEmoji.Custom name can be null

common/src/main/java/discord4j/common/store/legacy/LegacyStoreLayout.java
**Description:** Recently, I got IllegalStateExceptions when using the LegacyStoreLayout and managing ReactionEvent, because it does not provide required fields for building a ReactionData.
**Justification:** IllegalStateException when using LegacyStoreLayout and having the required conditions regarding the previous state.
Here's an example of one IllegalStateException.
```
2024-07-15 10:12:31:990 [reactor-http-epoll-3] ERROR DispatchStoreLayer - Error when executing store action on dispatch MessageReactionAdd{userId=<REDACTED>, channelId=<REDACTED>, messageId=<REDACTED>, guildId=Possible{<REDACTED>}, member=Possible{MemberData{nick=Possible{Optional[<REDACTED>]}, roles=[J@1de5bff0, joinedAt=2020-11-06T05:24:51.771000+00:00, premiumSince=Possible{Optional.empty}, deaf=false, mute=false, …
```
=> Fix LegacyStoreLayout ReactionEvent handling not managing count_details nor me_burst fields

core/src/main/java/discord4j/core/retriever/RestEntityRetriever.java, rest/src/main/java/discord4j/rest/route/Routes.java, rest/src/main/java/discord4j/rest/service/GuildService.java
**Description:** Implement a REST behaviour for get the Role (thanks adavaith xd) from guild using Id and avoid make things like handle the whole role list in REST and set a filter
**Justification:** https://github.com/discord/discord-api-docs/pull/7074
=> Support for get role from Guild using REST

core/src/main/java/discord4j/core/object/entity/channel/BaseTopLevelGuildChannel.java, core/src/main/java/discord4j/core/object/entity/channel/ThreadChannel.java
**Justification:** The "nearest" class that we can cast to is the BaseTopLevelGuildChannel
This fix #1269
=> fix: ClassCastException if parent of ThreadMessage is a Forum

common/src/main/java/discord4j/common/store/impl/WrappedGuildData.java
**Justification:** As WrappedGuildData#getMembers (and the other getters) returns the underlying Lists that are edited on member add/remove, a call to #unwrap() at the same time raises a CME.
fix #1267
=> fix: ConcurrentModification for WrappedGuildData#unwrap in store

core/src/main/java/discord4j/core/retriever/RestEntityRetriever.java, rest/src/main/java/discord4j/rest/RestClient.java, rest/src/main/java/discord4j/rest/entity/RestGuild.java
Update the paged request sizes of discord guilds per user and members per guild according to discords documentation.
Limitation documented by discord:
https://discord.com/developers/docs/resources/guild#list-guild-members
https://discord.com/developers/docs/resources/user#get-current-user-guilds
=> update retrieve limits for guilds and guild members according to docs

core/src/main/java/discord4j/core/object/entity/IntegrationApplication.java
**Description:** This PR just deprecate the summary method based in how discord just return an empty string
**Justification:** https://github.com/discord/discord-api-docs/commit/a36e8112a7e63b8105be54fea3d18611552fedb4
=> Feat: deprecate IntegrationApplication#getSummary

core/src/main/java/discord4j/core/event/dispatch/MessageDispatchHandlers.java, gradle.properties
**Description:** This handle a case where the messageAuthorId can not be set in the gateway, for reduce breaking things this fix just handle the missing case with a 0 ID like currently the D4J docs mention in the method. For 3.3.x this can be a Optional.
**Justification:** https://github.com/discord/discord-api-docs/commit/26b95485354b4d583b35f6dd5b149d1ab0ff42ae and close #1273
=> Fix: Nullable messageAuthorId for Reaction Add Event

core/src/main/java/discord4j/core/object/entity/Guild.java, core/src/main/java/discord4j/core/object/entity/Role.java
**Description:** Add support for the linked role mention for guild and role.
**Justification:** https://github.com/discord/discord-api-docs/pull/7105
=> Add support for linked role mention

build.gradle
**Description:** Update reactor to 2023.0.17
**Justification:** Keep updated and handle minor fixes in netty like the logger warning
=> Bump Reactor to 2023.0.17

core/src/main/java/discord4j/core/object/entity/channel/ThreadChannel.java
**Description:** As discussed a few month ago on the Discord4J Discord server (and I'm sorry I forgot this PR), some methods regarding Forum tags were missing in the ForumChannel class.
I first added some documentation within the Thread Channel class, then I implemented two methods : 
* `getAppliedTagsIds()`: Gets an Optional list of the applied tags on the thread channel. The returned optional is empty if the applied_tags field was not sent by Discord, which is when the thread channel is not from a Forum or media channel.
* `getAppliedTags()`: Another method that does the same job but instead of returning the applied tags identifiers, a Flux emits the ForumTag objects directly. Note that, currently, only the forum channels are supported even if the media channels are documented on the …
=> Feat: Add missing ThreadChannel#getAppliedTags method

core/src/main/java/discord4j/core/object/entity/Webhook.java, core/src/main/java/discord4j/core/spec/InteractionReplyEditSpecGenerator.java, gradle.properties, rest/src/main/java/discord4j/rest/service/WebhookService.java
**Description:** This PR fix an issue where edit a reply or modify a webhook not handle the components v2, this was caused by a missing flags field not documented by discord in the release.
**Justification:** https://github.com/discord/discord-api-docs/pull/7507
=> fix: allow components v2 in Webhook edit

core/src/main/java/discord4j/core/spec/InteractionApplicationCommandCallbackSpecGenerator.java, core/src/main/java/discord4j/core/spec/InteractionFollowupCreateSpecGenerator.java, core/src/main/java/discord4j/core/spec/InteractionReplyEditSpecGenerator.java, core/src/main/java/discord4j/core/spec/InternalMessageSpecUtils.java, core/src/main/java/discord4j/core/spec/MessageCreateSpecGenerator.java, core/src/main/java/discord4j/core/spec/MessageEditSpecGenerator.java, rest/src/main/java/discord4j/rest/entity/RestChannel.java
**Description:** Make the ofRequest for the specs related to create or edit a message add the CV2 flag if any of the components require that
**Justification:** Make this follow the same behaviour than Interaction Messages where this flag is added internally, this can reduce users confusing about when need add or not the flag, the bad thing with this is users can get errors if try things not allowed by discord like using content and adding components, that require a way to make the spec generator add docs about that.
=> feat: make Create/Edit Message Spec include the CV2 flag if can

core/src/main/java/discord4j/core/event/domain/interaction/ModalSubmitInteractionEvent.java, core/src/main/java/discord4j/core/object/command/ApplicationCommandInteraction.java, core/src/main/java/discord4j/core/object/component/FileUpload.java, core/src/main/java/discord4j/core/object/component/MessageComponent.java, core/src/test/java/discord4j/core/ExampleModal.java
**Description:** This PR add support for file uploads in modals and also add in ModalSubmitInteractionEvent a method for get the resolved data (works like the same than other interactions but the IDs need to be get from the values in the components supported)
**Justification:** Components V2 Phase 3
=> feat: Support File Upload and Resolved Data in Modals
